// AUTO-GENERATED by scripts/translate-content.mjs (locale: IT)
// Source: src/lib/about-content.ts
// DO NOT EDIT BY HAND — re-run the script to regenerate.
// Generated: 2026-05-25T08:53:04.593Z

/**
 * about-content.ts — All copy + structured data for the /about-us page.
 *
 * Mirror files (about-content.ar.ts / about-content.it.ts) are generated by
 *   node scripts/translate-content.mjs src/lib/about-content.ts <ar|it> src/lib/about-content.<loc>.ts
 *
 * Keep image paths, hrefs, and proper-noun stat values in shape — the translator
 * skips fields named `image`, `icon`, `logo`, `href`, `photo`, `linkedin`, `slug`,
 * `value`, `src`, and any string that looks like a URL / path.
 */

export const aboutContent = {
  ui: {
    home: 'Casa',
    breadcrumb: 'Chi siamo',
    eyebrow: 'Chi siamo',
    heading: 'Siamo i tuoi partner tecnologici digitali.',
    body: 'Dal 2022 aiutiamo aziende come la tua ad accelerare il loro percorso verso il successo, supportate dalle giuste soluzioni trasformative.',
    primaryCta: 'Esplora di più',
    heroImageAlt: 'Elchai Spazio di lavoro dell\'ufficio di gruppo',

    trustedEyebrow: 'Scelto dai marchi leader a livello mondiale',
    trustedAlt: 'Marchio affidabile',

    statsEyebrow: 'Abbiamo potenziato',

    teamEyebrow: 'La nostra squadra',
    teamHeading: 'Siamo un team in crescita di menti innovative, appassionati del tuo successo.',
    linkedinLabel: 'LinkedIn',
    linkedinAria: 'su LinkedIn',

    widerTeamEyebrow: 'La squadra più ampia',
    widerTeamHeading: 'Oltre 500 specialisti in quattro discipline.',

    midCtaA: 'Lavoriamo insieme per costruire il tuo successo.',
    midCtaB: 'Hai un\'idea straordinaria? Trasformiamolo adesso.',
    midCtaButton: 'Inizia',

    journeyEyebrow: 'Il nostro viaggio',
    journeyHeading: 'Esplora oltre 4 anni di ideazione. Innovazione. Trasformazione.',
    journeyBody: 'Le cose si sono evolute rapidamente negli ultimi dieci anni, ma c’è una cosa che è rimasta la stessa: il nostro obiettivo di offrire esperienze digitali trasformative.',

    promiseEyebrow: 'La nostra promessa',
    promiseHeading: 'Partner di successo per alcune ragioni davvero buone.',
    promiseBody: 'Quando scegli Elchai come partner, hai alle spalle un team dedicato che si prende davvero cura delle tue idee uniche.',
    getInTouch: 'Mettiti in contatto',
    counterSuffix: '/ 04',

    caseStudiesEyebrow: 'Casi di studio',
    caseStudiesHeading: 'Cattura l\'innovazione in azione con noi.',
    caseStudiesBody: 'Sbircia nel futuro con i nostri progetti all\'avanguardia che stanno ridefinendo i settori.',
    downloadCs: 'Scarica il caso di studio',

    partnersEyebrow: 'Clienti e partner',
    partnersHeading: 'Partner orgogliosi di successo per aziende di tutte le dimensioni.',
    partnersBody: 'Siamo stati la spina dorsale tecnologica sia per le startup che per le imprese, guidando l\'innovazione su ogni scala.',
    partnersAlt: 'Logo del partner',

    closingEyebrow: 'Connettiamoci',
    closingHeading: 'Pronto per iniziare il tuo viaggio di trasformazione?',
    closingBody: 'Aiutiamo le aziende a spostarsi da dove sono a dove devono essere.',
    closingCta: 'Esplora di più',
    closingGhost: 'Vedi casi di studio',
  },

  statsTop: [
    { value: '10,000+', label: 'Imprese' },
    { value: '150+',    label: 'Paesi' },
  ],

  statsBottom: [
    { value: '2,000+', label: 'Soluzioni aziendali fornite', icon: '/elchai/about/about-counter-icn_1.svg' },
    { value: '6,000+', label: 'Potenziamento delle startup',             icon: '/elchai/about/about-counter-icn_2.svg' },
    { value: '120+',   label: 'Startup da milioni di finanziamenti',        icon: '/elchai/about/about-counter-icn_3.svg' },
  ],

  team: [
    { name: 'Flavio Elia',          role: 'Fondatore',                                    photo: '/elchai/about/Flavio_Elia2.webp',       linkedin: 'https://www.linkedin.com/in/flavio-elia/' },
    { name: 'Konstantin Kirchfeld', role: 'Socio amministratore e COO',                     photo: '/elchai/about/Konstantin_Kirchfeld.webp', linkedin: 'https://www.linkedin.com/in/konstantin-kirchfeld-9b71975a/' },
    { name: 'Stefano Curzio',       role: 'Socio amministratore e CFO',                     photo: '/elchai/about/1Stefano-Curzio.webp',    linkedin: 'https://www.linkedin.com/in/stefanocurzio/' },
    { name: 'Corrado Salmè',        role: 'CEO nazionale, Belgium',                       photo: '/elchai/about/Corrado_Salme.jpeg',      linkedin: 'https://www.linkedin.com/in/corrado-salm%C3%A9-688215401/' },
    { name: 'Aseem Ghavri',         role: 'Responsabile dei partenariati strategici',             photo: '/elchai/about/Aseem_CTO.webp',          linkedin: 'https://ae.linkedin.com/in/aseemghavri' },
    { name: 'GiorgiaCristina',     role: 'Analista finanziario',                          photo: '/elchai/about/Giorgia-Cristina.jpeg',   linkedin: 'https://www.linkedin.com/in/giorgia-cristina-panico-7b4a1b171/' },
    { name: 'Sukhchain Singh',      role: 'CTO',                                        photo: '/elchai/about/Sukhchain_Singh1.webp',   linkedin: 'https://www.linkedin.com/in/sukhchainsingh/' },
    { name: 'Jacopo Dellai',        role: 'SSA',                                        photo: '/elchai/about/Jacopo_Dellai.webp',      linkedin: 'https://www.linkedin.com/in/jacopo-dellai-a31757188/' },
    { name: 'Alberto Palay',         role: 'Partenariati strategici e responsabile dello sviluppo',  photo: '/elchai/about/Albert_Palay.webp',       linkedin: 'http://linkedin.com/in/albert-palay-a445577' },
    { name: 'Carlo Davide',        role: 'Responsabile AI',                                 photo: '/elchai/about/Charles_David.webp',      linkedin: 'https://www.linkedin.com/in/charlesaarondavid/' },
    { name: 'Jasna Ali',            role: 'Responsabile del progetto informatico',                         photo: '/elchai/about/Jasna.webp',              linkedin: 'https://www.linkedin.com/in/jasna-ali-2067111a1/' },
    { name: 'Florian Katiaj',       role: 'SSA (Albania)',                              photo: '/elchai/about/Florian-Katiaj.webp',     linkedin: 'https://www.linkedin.com/in/florian-katiaj-ba8406145' },
    { name: 'Diana Guevarra',       role: 'Direttore aziendale (UAE)',                     photo: '/elchai/about/Diana-Guevarra.webp',     linkedin: 'https://www.linkedin.com/in/dianna-rose-guevarra-1007a3221' },
    { name: 'Angela Cordella',      role: 'Direttore aziendale (UE)',                      photo: '/elchai/about/Angela-Cordella.webp',    linkedin: 'http://www.linkedin.com/in/angela-cordella-69112739b' },
    { name: 'Pargat Dhillon',       role: 'Responsabile tecnico',                                  photo: '/elchai/about/Pargat-Dhillon.webp',     linkedin: 'https://www.linkedin.com/in/pargatd/' },
    { name: 'Ritika Grover',        role: 'Responsabile marketing',                             photo: '/elchai/about/Ritika-Grover.webp',      linkedin: 'https://www.linkedin.com/in/ritika-grover-272301136/' },
    { name: 'Nidhi Chandel',        role: 'Responsabile risorse umane e persone',                        photo: '/elchai/about/Nidhi-Chandel.webp',      linkedin: 'https://www.linkedin.com/in/nidhi-chandel/' },
  ],

  teamComposition: [
    { value: '650+', title: 'Sviluppatori', note: 'Sviluppatori di app di alto livello', avatars: ['/elchai/about/user-1.webp','/elchai/about/user-2.webp','/elchai/about/user-3.webp','/elchai/about/user-4.webp','/elchai/about/user-5.webp'] },
    { value: '300+', title: 'Designer',  note: 'Progettisti di UI/UX',         avatars: ['/elchai/about/ds-1.webp','/elchai/about/ds-2.webp','/elchai/about/ds-3.webp','/elchai/about/ds-4.webp','/elchai/about/ds-5.webp'] },
    { value: '250+', title: 'Operatori di marketing',  note: 'Ninja del marketing',        avatars: ['/elchai/about/mn-1.webp','/elchai/about/mn-2.webp','/elchai/about/mn-3.webp','/elchai/about/mn-4.webp','/elchai/about/mn-5.webp'] },
    { value: '200+', title: 'Costruttori',   note: 'Analisti aziendali',       avatars: ['/elchai/about/bd-1.webp','/elchai/about/bd-2.webp','/elchai/about/bd-3.webp','/elchai/about/bd-4.webp','/elchai/about/bd-5.webp'] },
  ],

  journey: [
    {
      year: '2022',
      items: [
        { title: 'Settembre 2022 — L\'inizio', body: 'El Chai ha lanciato un\'idea audace: costruire il primo club automobilistico al mondo che esista sia nel mondo reale che nel metaverso.' },
        { title: 'Fine 2022: lancio del token BEC',  body: 'Abbiamo dato il via al nostro primo round di raccolta fondi con il token BEC, la tua chiave per entrare a far parte del club automobilistico virtuale.' },
      ],
    },
    {
      year: '2023',
      items: [
        { title: 'Marzo 2023 – Costruire Bluewaters', body: 'Abbiamo iniziato a ricreare l\'iconica isola Bluewaters di Dubai nel metaverso, con il nostro club automobilistico virtuale posizionato sotto la famosa ruota panoramica.' },
        { title: 'Giugno 2023 – Partenariato Nakheel',  body: 'Ha collaborato con Nakheel per costruire la nuova Palm Jebel Ali all\'interno del metaverso.' },
      ],
    },
    {
      year: '2024',
      items: [
        { title: 'Gennaio 2024: apre il primo ufficio',  body: 'Abbiamo aperto il nostro primo ufficio fisico a JLT, Dubai.' },
        { title: 'Giugno 2024 — Crescere in Dubai',        body: 'Ampliato con un secondo ufficio mentre il team continuava a crescere.' },
        { title: 'Metà 2024: piattaforma di crediti di carbonio',   body: 'Ha collaborato con The Rob Rockefeller per creare una piattaforma di scambio di crediti di carbonio.' },
        { title: 'Metà 2024: diventare globali',             body: 'Aperte filiali su Albania, Hungary, Italy, Oman, Dubai e Abu Dhabi con oltre 500 specialisti.' },
        { title: 'Novembre 2024 – Nuovo quartier generale',              body: 'Operazioni consolidate in un unico ufficio digitalizzato nella JBC 1 Tower, Dubai.' },
        { title: 'Fine 2024 — Abu Dhabi Espansione',     body: 'Lanciato strutture di investimento SPV e iniziato a tokenizzare asset reali digitali in Abu Dhabi.' },
      ],
    },
    {
      year: 'Oggi',
      items: [
        { title: 'Presente', body: 'Opera in sei paesi con oltre 500 membri del team che creano ecosistemi digitali in Web3.' },
      ],
    },
  ],

  reasons: [
    { n: '01', kicker: 'Ti aiutiamo', title: 'Vai in diretta, prima',           body: 'Non allunghiamo inutilmente le ore totali di sviluppo. Invece, il nostro processo di sviluppo basato su AI dà vita alla tua idea il prima possibile.',         icon: '/elchai/about/about-reasons-icn_1.svg' },
    { n: '02', kicker: 'Ti aiutiamo', title: 'Connettiti con gli investitori',    body: 'Negli ultimi dieci anni abbiamo costruito contatti con investitori interessati ad aziende come la tua. Con noi raccogliere fondi diventa più semplice.',                 icon: '/elchai/about/about-reasons-icn_2.svg' },
    { n: '03', kicker: 'Ti aiutiamo', title: 'Rimani nel budget, sempre',    body: 'Non solo il tuo tempo, ma diamo valore anche ai tuoi soldi. Sfrutta il nostro processo automatizzato per sapere esattamente cosa stai pagando e ottenere prezzi garantiti, senza sorprese.', icon: '/elchai/about/about-reasons-icn_3.svg' },
    { n: '04', kicker: 'Ti aiutiamo', title: 'Oggi, domani e per sempre', body: 'Effettuiamo aggiornamenti e risolviamo i bug prima che tu ti accorga che c\'è un problema. Promettiamo di offrire supporto continuo per garantire soluzioni della massima qualità senza stress.', icon: '/elchai/about/about-reasons-icn_4.svg' },
  ],

  caseStudies: [
    { label: 'AI Soluzioni', sector: 'per salute e fitness', body: 'Consigli personalizzati su alimentazione e allenamento, supportati da algoritmi AI avanzati, apprendimento automatico e analisi predittiva.', logo: '/elchai/about/smartfit-logo.svg', image: '/elchai/about/smartfit-app.webp', stats: [{ value: '80%', label: 'Tasso di fidelizzazione degli utenti' }, { value: '20K+', label: 'Piani pasto generati' }] },
    { label: 'Portafoglio',       sector: 'per il fintech',          body: 'Sviluppato un portafoglio crittografico multicatena sicuro con protocolli di sicurezza di livello istituzionale e integrazione di contratti intelligenti.',           logo: '/elchai/about/fintex-logo.svg',   image: '/elchai/about/fintex-app.webp',   stats: [{ value: '20%', label: 'Criptovalute supportate' }, { value: '$100K+', label: 'Volume delle transazioni giornaliere' }] },
    { label: 'Metaverso',    sector: 'per il settore immobiliare',      body: 'Ho creato un\'esperienza coinvolgente nel metaverso utilizzando la tecnologia AR/VR e l\'integrazione blockchain per il principale mercato immobiliare di Dubai.', logo: '/elchai/about/theuneverse-logo.svg', image: '/elchai/about/theuneverse-app.webp', stats: [{ value: '1000+', label: 'Proprietà virtuali elencate' }, { value: '45%', label: 'Aumento delle visualizzazioni delle proprietà' }] },
    { label: 'CRM',          sector: 'per i media e la ricerca', body: 'Trasformare dati multimediali complessi in informazioni utilizzabili, consentendo analisi di mercato in tempo reale e modellazione predittiva del pubblico.',  logo: '/elchai/about/nielsen-logo.svg',  image: '/elchai/about/nielsen-app.webp',   stats: [{ value: '85%', label: 'Tempi di analisi più rapidi' }, { value: '60%', label: 'Processo decisionale più rapido' }] },
  ],
} as const;

export type AboutContent = typeof aboutContent;
