/**
 * about-content.ts — All copy + structured data for the /about-us page.
 *
 * Mirror files (about-content.ar.ts / about-content.it.ts) are generated by
 *   node scripts/translate-content.mjs src/lib/about-content.ts <ar|it> src/lib/about-content.<loc>.ts
 *
 * Keep image paths, hrefs, and proper-noun stat values in shape — the translator
 * skips fields named `image`, `icon`, `logo`, `href`, `photo`, `linkedin`, `slug`,
 * `value`, `src`, and any string that looks like a URL / path.
 */

export const aboutContent = {
  ui: {
    home: 'Home',
    breadcrumb: 'About Us',
    eyebrow: 'About us',
    heading: 'We\'re Your Digital Technological Partners.',
    body: 'Since 2022, we\'ve been helping businesses like yours accelerate their journey to success, backed by the right transformative solutions.',
    primaryCta: 'Explore More',
    heroImageAlt: 'Elchai Group office workspace',

    trustedEyebrow: 'Trusted by World\'s Leading Brands',
    trustedAlt: 'Trusted brand',

    statsEyebrow: 'We\'ve Empowered',

    teamEyebrow: 'Our Team',
    teamHeading: 'We\'re A Growing Team Of Innovative Minds, Passionate About Your Success.',
    linkedinLabel: 'LinkedIn',
    linkedinAria: 'on LinkedIn',

    widerTeamEyebrow: 'The Wider Team',
    widerTeamHeading: '500+ Specialists Across Four Disciplines.',

    midCtaA: 'We Work Together To Build Success For You.',
    midCtaB: 'Have An Amazing Idea? Let\'s Transform It Now.',
    midCtaButton: 'Get Started',

    journeyEyebrow: 'Our Journey',
    journeyHeading: 'Explore 4+ Years Of Ideation. Innovation. Transformation.',
    journeyBody: 'Things have evolved quickly over the last decade, but there is one thing that stayed the same — our aim to deliver transformative digital experiences.',

    promiseEyebrow: 'Our Promise',
    promiseHeading: 'Success Partners For Some Really Good Reasons.',
    promiseBody: 'When you choose Elchai as your partner, you have a dedicated team behind that truly cares about your unique ideas.',
    getInTouch: 'Get in Touch',
    counterSuffix: '/ 04',

    caseStudiesEyebrow: 'Case studies',
    caseStudiesHeading: 'Catch Innovation in Action With Us.',
    caseStudiesBody: 'Peek into the future with our cutting-edge projects that are redefining industries.',
    downloadCs: 'Download Case Study',

    partnersEyebrow: 'Clients & Partners',
    partnersHeading: 'Proud Success Partners To Businesses Of All Sizes.',
    partnersBody: 'We\'ve been the technology backbone for startups and enterprises alike, driving innovation at every scale.',
    partnersAlt: 'Partner logo',

    closingEyebrow: 'Let\'s Connect',
    closingHeading: 'Ready To Head-Start Your Transformation Journey?',
    closingBody: 'We help businesses get from where they are, to where they need to be.',
    closingCta: 'Explore More',
    closingGhost: 'See Case Studies',
  },

  statsTop: [
    { value: '10,000+', label: 'Businesses' },
    { value: '150+',    label: 'Countries' },
  ],

  statsBottom: [
    { value: '2,000+', label: 'Enterprise Solutions Delivered', icon: '/elchai/about/about-counter-icn_1.svg' },
    { value: '6,000+', label: 'Startups Empowered',             icon: '/elchai/about/about-counter-icn_2.svg' },
    { value: '120+',   label: 'Million-Funded Startups',        icon: '/elchai/about/about-counter-icn_3.svg' },
  ],

  team: [
    { name: 'Flavio Elia',          role: 'Founder',                                    photo: '/elchai/about/Flavio_Elia2.webp',       linkedin: 'https://www.linkedin.com/in/flavio-elia/' },
    { name: 'Konstantin Kirchfeld', role: 'Managing Partner & COO',                     photo: '/elchai/about/Konstantin_Kirchfeld.webp', linkedin: 'https://www.linkedin.com/in/konstantin-kirchfeld-9b71975a/' },
    { name: 'Stefano Curzio',       role: 'Managing Partner & CFO',                     photo: '/elchai/about/1Stefano-Curzio.webp',    linkedin: 'https://www.linkedin.com/in/stefanocurzio/' },
    { name: 'Corrado Salmé',        role: 'Country CEO, Belgium',                       photo: '/elchai/about/Corrado_Salme.jpeg',      linkedin: 'https://www.linkedin.com/in/corrado-salm%C3%A9-688215401/' },
    { name: 'Aseem Ghavri',         role: 'Head of Strategic Partnerships',             photo: '/elchai/about/Aseem_CTO.webp',          linkedin: 'https://ae.linkedin.com/in/aseemghavri' },
    { name: 'Giorgia Cristina',     role: 'Financial Analyst',                          photo: '/elchai/about/Giorgia-Cristina.jpeg',   linkedin: 'https://www.linkedin.com/in/giorgia-cristina-panico-7b4a1b171/' },
    { name: 'Sukhchain Singh',      role: 'CTO',                                        photo: '/elchai/about/Sukhchain_Singh1.webp',   linkedin: 'https://www.linkedin.com/in/sukhchainsingh/' },
    { name: 'Jacopo Dellai',        role: 'SSA',                                        photo: '/elchai/about/Jacopo_Dellai.webp',      linkedin: 'https://www.linkedin.com/in/jacopo-dellai-a31757188/' },
    { name: 'Albert Palay',         role: 'Strategic Partnerships & Development Lead',  photo: '/elchai/about/Albert_Palay.webp',       linkedin: 'http://linkedin.com/in/albert-palay-a445577' },
    { name: 'Charles David',        role: 'Head of AI',                                 photo: '/elchai/about/Charles_David.webp',      linkedin: 'https://www.linkedin.com/in/charlesaarondavid/' },
    { name: 'Jasna Ali',            role: 'IT Project Manager',                         photo: '/elchai/about/Jasna.webp',              linkedin: 'https://www.linkedin.com/in/jasna-ali-2067111a1/' },
    { name: 'Florian Katiaj',       role: 'SSA (Albania)',                              photo: '/elchai/about/Florian-Katiaj.webp',     linkedin: 'https://www.linkedin.com/in/florian-katiaj-ba8406145' },
    { name: 'Diana Guevarra',       role: 'Business Manager (UAE)',                     photo: '/elchai/about/Diana-Guevarra.webp',     linkedin: 'https://www.linkedin.com/in/dianna-rose-guevarra-1007a3221' },
    { name: 'Angela Cordella',      role: 'Business Manager (EU)',                      photo: '/elchai/about/Angela-Cordella.webp',    linkedin: 'http://www.linkedin.com/in/angela-cordella-69112739b' },
    { name: 'Pargat Dhillon',       role: 'Tech Head',                                  photo: '/elchai/about/Pargat-Dhillon.webp',     linkedin: 'https://www.linkedin.com/in/pargatd/' },
    { name: 'Ritika Grover',        role: 'Marketing Head',                             photo: '/elchai/about/Ritika-Grover.webp',      linkedin: 'https://www.linkedin.com/in/ritika-grover-272301136/' },
    { name: 'Nidhi Chandel',        role: 'HR & People Manager',                        photo: '/elchai/about/Nidhi-Chandel.webp',      linkedin: 'https://www.linkedin.com/in/nidhi-chandel/' },
  ],

  teamComposition: [
    { value: '650+', title: 'Developers', note: 'Top-tier App Developers', avatars: ['/elchai/about/user-1.webp','/elchai/about/user-2.webp','/elchai/about/user-3.webp','/elchai/about/user-4.webp','/elchai/about/user-5.webp'] },
    { value: '300+', title: 'Designers',  note: 'UI/UX Designers',         avatars: ['/elchai/about/ds-1.webp','/elchai/about/ds-2.webp','/elchai/about/ds-3.webp','/elchai/about/ds-4.webp','/elchai/about/ds-5.webp'] },
    { value: '250+', title: 'Marketers',  note: 'Marketing Ninjas',        avatars: ['/elchai/about/mn-1.webp','/elchai/about/mn-2.webp','/elchai/about/mn-3.webp','/elchai/about/mn-4.webp','/elchai/about/mn-5.webp'] },
    { value: '200+', title: 'Builders',   note: 'Business Analysts',       avatars: ['/elchai/about/bd-1.webp','/elchai/about/bd-2.webp','/elchai/about/bd-3.webp','/elchai/about/bd-4.webp','/elchai/about/bd-5.webp'] },
  ],

  journey: [
    {
      year: '2022',
      items: [
        { title: 'September 2022 — The Beginning', body: 'El Chai launched with a bold idea: build the world\'s first car club that exists in both the real world and the metaverse.' },
        { title: 'Late 2022 — BEC Token Launch',  body: 'We kicked off our first fundraising round with the BEC token, your key to joining the virtual car club.' },
      ],
    },
    {
      year: '2023',
      items: [
        { title: 'March 2023 — Building Bluewaters', body: 'Started recreating Dubai\'s iconic Bluewaters Island in the metaverse, with our virtual car club positioned under the famous Ferris wheel.' },
        { title: 'June 2023 — Nakheel Partnership',  body: 'Partnered with Nakheel to build the new Palm Jebel Ali inside the metaverse.' },
      ],
    },
    {
      year: '2024',
      items: [
        { title: 'January 2024 — First Office Opens',  body: 'Opened our first physical office in JLT, Dubai.' },
        { title: 'June 2024 — Growing in Dubai',        body: 'Expanded with a second office location as the team continued to grow.' },
        { title: 'Mid-2024 — Carbon Credit Platform',   body: 'Teamed up with The Rob Rockefeller to create a carbon credit exchange platform.' },
        { title: 'Mid-2024 — Going Global',             body: 'Opened branches across Albania, Hungary, Italy, Oman, Dubai, and Abu Dhabi with over 500 specialists.' },
        { title: 'November 2024 — New HQ',              body: 'Consolidated operations into a single digitalized office in JBC 1 Tower, Dubai.' },
        { title: 'Late 2024 — Abu Dhabi Expansion',     body: 'Launched SPV investment structures and began tokenizing digital real assets in Abu Dhabi.' },
      ],
    },
    {
      year: 'Today',
      items: [
        { title: 'Present', body: 'Operating across six countries with 500+ team members building digital ecosystems in Web3.' },
      ],
    },
  ],

  reasons: [
    { n: '01', kicker: 'We Help You', title: 'Go Live, Sooner',           body: 'We don\'t stretch total hours of development unnecessarily. Instead, our AI-powered development process brings your idea to life as soon as possible.',         icon: '/elchai/about/about-reasons-icn_1.svg' },
    { n: '02', kicker: 'We Help You', title: 'Connect With Investors',    body: 'Over the last decade, we have built contacts with investors that are interested in businesses like yours. Raising funds turns easier with us.',                 icon: '/elchai/about/about-reasons-icn_2.svg' },
    { n: '03', kicker: 'We Help You', title: 'Stay In Budget, Always',    body: 'Not just your time, but we value your money too. Leverage our automated process to know exactly what you\'re paying for & get guaranteed pricing, without any surprises.', icon: '/elchai/about/about-reasons-icn_3.svg' },
    { n: '04', kicker: 'We Help You', title: 'Today, Tomorrow & Forever', body: 'We make updates and fix bugs before you realize there\'s a problem. We promise to offer everlasting support to ensure the highest quality solutions with zero stress.', icon: '/elchai/about/about-reasons-icn_4.svg' },
  ],

  caseStudies: [
    { label: 'AI Solutions', sector: 'for Health & Fitness', body: 'Personalized nutrition and workout recommendations, backed by advanced AI algorithms, machine learning, and predictive analytics.', logo: '/elchai/about/smartfit-logo.svg', image: '/elchai/about/smartfit-app.webp', stats: [{ value: '80%', label: 'User Retention Rate' }, { value: '20K+', label: 'Meal Plans Generated' }] },
    { label: 'Wallet',       sector: 'for Fintech',          body: 'Developed a secure multi-chain crypto wallet with institutional-grade security protocols and smart contract integration.',           logo: '/elchai/about/fintex-logo.svg',   image: '/elchai/about/fintex-app.webp',   stats: [{ value: '20%', label: 'Cryptocurrencies Supported' }, { value: '$100K+', label: 'Daily Transaction Volume' }] },
    { label: 'Metaverse',    sector: 'for Real Estate',      body: 'Created an immersive metaverse experience using AR/VR technology and blockchain integration for Dubai\'s premier real estate market.', logo: '/elchai/about/theuneverse-logo.svg', image: '/elchai/about/theuneverse-app.webp', stats: [{ value: '1000+', label: 'Virtual Properties Listed' }, { value: '45%', label: 'Increase in Property Views' }] },
    { label: 'CRM',          sector: 'for Media & Research', body: 'Transforming complex media data into actionable intelligence, enabling real-time market analysis and predictive audience modeling.',  logo: '/elchai/about/nielsen-logo.svg',  image: '/elchai/about/nielsen-app.webp',   stats: [{ value: '85%', label: 'Faster Analysis Time' }, { value: '60%', label: 'Faster Decision Making' }] },
  ],
} as const;

export type AboutContent = typeof aboutContent;
