// AUTO-GENERATED by scripts/translate-content.mjs (locale: AR)
// Source: src/lib/about-content.ts
// DO NOT EDIT BY HAND — re-run the script to regenerate.
// Generated: 2026-05-25T08:52:52.947Z

/**
 * about-content.ts — All copy + structured data for the /about-us page.
 *
 * Mirror files (about-content.ar.ts / about-content.it.ts) are generated by
 *   node scripts/translate-content.mjs src/lib/about-content.ts <ar|it> src/lib/about-content.<loc>.ts
 *
 * Keep image paths, hrefs, and proper-noun stat values in shape — the translator
 * skips fields named `image`, `icon`, `logo`, `href`, `photo`, `linkedin`, `slug`,
 * `value`, `src`, and any string that looks like a URL / path.
 */

export const aboutContent = {
  ui: {
    home: 'بيت',
    breadcrumb: 'معلومات عنا',
    eyebrow: 'معلومات عنا',
    heading: 'نحن شركاؤك التكنولوجيون الرقميون.',
    body: 'منذ عام 2022، نساعد الشركات مثل شركتك على تسريع رحلتها نحو النجاح، مدعومة بالحلول التحويلية المناسبة.',
    primaryCta: 'اكتشف المزيد',
    heroImageAlt: 'Elchai مساحة عمل مكتب المجموعة',

    trustedEyebrow: 'موثوق به من قبل العلامات التجارية الرائدة في العالم',
    trustedAlt: 'علامة تجارية موثوقة',

    statsEyebrow: 'لقد قمنا بالتمكين',

    teamEyebrow: 'فريقنا',
    teamHeading: 'نحن فريق متزايد من العقول المبتكرة، متحمسون لنجاحك.',
    linkedinLabel: 'ينكدين',
    linkedinAria: 'على لينكدإن',

    widerTeamEyebrow: 'الفريق الأوسع',
    widerTeamHeading: 'أكثر من 500 متخصص في أربعة تخصصات.',

    midCtaA: 'نحن نعمل معًا لبناء النجاح لك.',
    midCtaB: 'هل لديك فكرة مذهلة؟ دعونا تحويله الآن.',
    midCtaButton: 'ابدأ',

    journeyEyebrow: 'رحلتنا',
    journeyHeading: 'اكتشف أكثر من 4 سنوات من التفكير. ابتكار. تحويل.',
    journeyBody: 'لقد تطورت الأمور بسرعة على مدار العقد الماضي، ولكن هناك شيء واحد ظل على حاله - وهو هدفنا المتمثل في تقديم تجارب رقمية تحويلية.',

    promiseEyebrow: 'وعدنا',
    promiseHeading: 'شركاء النجاح لبعض الأسباب الوجيهة حقًا.',
    promiseBody: 'عندما تختار Elchai كشريك لك، يكون لديك فريق متخصص يهتم حقًا بأفكارك الفريدة.',
    getInTouch: 'تواصل معنا',
    counterSuffix: '/ 04',

    caseStudiesEyebrow: 'دراسات الحالة',
    caseStudiesHeading: 'استمتع بالابتكار أثناء العمل معنا.',
    caseStudiesBody: 'ألق نظرة خاطفة على المستقبل من خلال مشاريعنا المتطورة التي تعيد تعريف الصناعات.',
    downloadCs: 'تحميل دراسة الحالة',

    partnersEyebrow: 'العملاء والشركاء',
    partnersHeading: 'شركاء نجاح فخورون للشركات بجميع أحجامها.',
    partnersBody: 'لقد كنا العمود الفقري للتكنولوجيا للشركات الناشئة والمؤسسات على حد سواء، حيث نقود الابتكار على جميع المستويات.',
    partnersAlt: 'شعار الشريك',

    closingEyebrow: 'دعونا نتواصل',
    closingHeading: 'هل أنت مستعد لبدء رحلة التحول الخاصة بك؟',
    closingBody: 'نحن نساعد الشركات على الانتقال من حيث هي إلى حيث تحتاج إلى أن تكون.',
    closingCta: 'اكتشف المزيد',
    closingGhost: 'انظر دراسات الحالة',
  },

  statsTop: [
    { value: '10,000+', label: 'الشركات' },
    { value: '150+',    label: 'بلدان' },
  ],

  statsBottom: [
    { value: '2,000+', label: 'تم تسليم حلول المؤسسات', icon: '/elchai/about/about-counter-icn_1.svg' },
    { value: '6,000+', label: 'تمكين الشركات الناشئة',             icon: '/elchai/about/about-counter-icn_2.svg' },
    { value: '120+',   label: 'الشركات الناشئة الممولة بملايين الدولارات',        icon: '/elchai/about/about-counter-icn_3.svg' },
  ],

  team: [
    { name: 'فلافيو ايليا',          role: 'مؤسس',                                    photo: '/elchai/about/Flavio_Elia2.webp',       linkedin: 'https://www.linkedin.com/in/flavio-elia/' },
    { name: 'كونستانتين كيرشفيلد', role: 'الشريك الإداري والمدير التنفيذي للعمليات',                     photo: '/elchai/about/Konstantin_Kirchfeld.webp', linkedin: 'https://www.linkedin.com/in/konstantin-kirchfeld-9b71975a/' },
    { name: 'ستيفانو كورزيو',       role: 'الشريك الإداري والمدير المالي',                     photo: '/elchai/about/1Stefano-Curzio.webp',    linkedin: 'https://www.linkedin.com/in/stefanocurzio/' },
    { name: 'كورادو سالمي',        role: 'الرئيس التنفيذي للدولة، Belgium',                       photo: '/elchai/about/Corrado_Salme.jpeg',      linkedin: 'https://www.linkedin.com/in/corrado-salm%C3%A9-688215401/' },
    { name: 'عاصم الغافري',         role: 'رئيس قسم الشراكات الإستراتيجية',             photo: '/elchai/about/Aseem_CTO.webp',          linkedin: 'https://ae.linkedin.com/in/aseemghavri' },
    { name: 'جورجيا كريستينا',     role: 'محلل مالي',                          photo: '/elchai/about/Giorgia-Cristina.jpeg',   linkedin: 'https://www.linkedin.com/in/giorgia-cristina-panico-7b4a1b171/' },
    { name: 'سوخشين سينغ',      role: 'CTO',                                        photo: '/elchai/about/Sukhchain_Singh1.webp',   linkedin: 'https://www.linkedin.com/in/sukhchainsingh/' },
    { name: 'جاكوبو ديلاي',        role: 'SSA',                                        photo: '/elchai/about/Jacopo_Dellai.webp',      linkedin: 'https://www.linkedin.com/in/jacopo-dellai-a31757188/' },
    { name: 'ألبرت بالاي',         role: 'قائد الشراكات الاستراتيجية والتطوير',  photo: '/elchai/about/Albert_Palay.webp',       linkedin: 'http://linkedin.com/in/albert-palay-a445577' },
    { name: 'تشارلز ديفيد',        role: 'رئيس AI',                                 photo: '/elchai/about/Charles_David.webp',      linkedin: 'https://www.linkedin.com/in/charlesaarondavid/' },
    { name: 'ياسنا علي',            role: 'مدير مشروع تكنولوجيا المعلومات',                         photo: '/elchai/about/Jasna.webp',              linkedin: 'https://www.linkedin.com/in/jasna-ali-2067111a1/' },
    { name: 'فلوريان كاتياج',       role: 'منطقة جنوب الصحراء الكبرى (Albania)',                              photo: '/elchai/about/Florian-Katiaj.webp',     linkedin: 'https://www.linkedin.com/in/florian-katiaj-ba8406145' },
    { name: 'ديانا جيفارا',       role: 'مدير الأعمال (UAE)',                     photo: '/elchai/about/Diana-Guevarra.webp',     linkedin: 'https://www.linkedin.com/in/dianna-rose-guevarra-1007a3221' },
    { name: 'أنجيلا كورديلا',      role: 'مدير الأعمال (الاتحاد الأوروبي)',                      photo: '/elchai/about/Angela-Cordella.webp',    linkedin: 'http://www.linkedin.com/in/angela-cordella-69112739b' },
    { name: 'بارجات ديلون',       role: 'رئيس التكنولوجيا',                                  photo: '/elchai/about/Pargat-Dhillon.webp',     linkedin: 'https://www.linkedin.com/in/pargatd/' },
    { name: 'ريتيكا جروفر',        role: 'رئيس التسويق',                             photo: '/elchai/about/Ritika-Grover.webp',      linkedin: 'https://www.linkedin.com/in/ritika-grover-272301136/' },
    { name: 'نيدي شاندل',        role: 'مدير الموارد البشرية والأفراد',                        photo: '/elchai/about/Nidhi-Chandel.webp',      linkedin: 'https://www.linkedin.com/in/nidhi-chandel/' },
  ],

  teamComposition: [
    { value: '650+', title: 'المطورين', note: 'مطورو التطبيقات من الدرجة الأولى', avatars: ['/elchai/about/user-1.webp','/elchai/about/user-2.webp','/elchai/about/user-3.webp','/elchai/about/user-4.webp','/elchai/about/user-5.webp'] },
    { value: '300+', title: 'المصممين',  note: 'مصممي واجهة المستخدم/تجربة المستخدم',         avatars: ['/elchai/about/ds-1.webp','/elchai/about/ds-2.webp','/elchai/about/ds-3.webp','/elchai/about/ds-4.webp','/elchai/about/ds-5.webp'] },
    { value: '250+', title: 'المسوقين',  note: 'تسويق النينجا',        avatars: ['/elchai/about/mn-1.webp','/elchai/about/mn-2.webp','/elchai/about/mn-3.webp','/elchai/about/mn-4.webp','/elchai/about/mn-5.webp'] },
    { value: '200+', title: 'بناة',   note: 'محللي الأعمال',       avatars: ['/elchai/about/bd-1.webp','/elchai/about/bd-2.webp','/elchai/about/bd-3.webp','/elchai/about/bd-4.webp','/elchai/about/bd-5.webp'] },
  ],

  journey: [
    {
      year: '2022',
      items: [
        { title: 'سبتمبر 2022 – البداية', body: 'تم إطلاق El Chai بفكرة جريئة: بناء أول نادي سيارات في العالم موجود في كل من العالم الحقيقي والعالم.' },
        { title: 'أواخر عام 2022 – إطلاق رمز BEC',  body: 'لقد بدأنا جولتنا الأولى لجمع التبرعات باستخدام رمز BEC، وهو مفتاحك للانضمام إلى نادي السيارات الافتراضي.' },
      ],
    },
    {
      year: '2023',
      items: [
        { title: 'مارس 2023 – بناء بلوواترز', body: 'بدأنا في إعادة إنشاء جزيرة بلوواترز الشهيرة في Dubai في Metaverse، مع وضع نادي السيارات الافتراضي الخاص بنا تحت عجلة Ferris الشهيرة.' },
        { title: 'يونيو 2023 — شراكة نخيل',  body: 'عقدت شراكة مع شركة نخيل لبناء نخلة جبل علي الجديدة داخل منطقة ميتافيرس.' },
      ],
    },
    {
      year: '2024',
      items: [
        { title: 'يناير 2024 – افتتاح المكتب الأول',  body: 'افتتحنا أول مكتب فعلي لنا في أبراج بحيرات جميرا، Dubai.' },
        { title: 'يونيو 2024 – النمو في Dubai',        body: 'تم التوسع بموقع مكتب ثانٍ مع استمرار الفريق في النمو.' },
        { title: 'منتصف عام 2024 – منصة ائتمان الكربون',   body: 'تعاونت مع The Rob Rockefeller لإنشاء منصة لتبادل أرصدة الكربون.' },
        { title: 'منتصف عام 2024 – التوجه نحو العالمية',             body: 'فتح فروع في Albania وHungary وItaly وOman وDubai وAbu Dhabi مع أكثر من 500 متخصص.' },
        { title: 'نوفمبر 2024 – المقر الرئيسي الجديد',              body: 'العمليات الموحدة في مكتب رقمي واحد في برج JBC 1، Dubai.' },
        { title: 'أواخر عام 2024 – Abu Dhabi التوسع',     body: 'تم إطلاق هياكل استثمار SPV وبدأت في ترميز الأصول الرقمية الحقيقية في Abu Dhabi.' },
      ],
    },
    {
      year: 'اليوم',
      items: [
        { title: 'حاضر', body: 'نعمل في ستة بلدان مع أكثر من 500 عضو في الفريق لبناء أنظمة بيئية رقمية في Web3.' },
      ],
    },
  ],

  reasons: [
    { n: '01', kicker: 'نحن نساعدك', title: 'ابدأ البث المباشر عاجلاً',           body: 'نحن لا نقوم بتمديد إجمالي ساعات التطوير دون داع. وبدلاً من ذلك، فإن عملية التطوير التي تعتمد على AI تعمل على إضفاء الحيوية على فكرتك في أسرع وقت ممكن.',         icon: '/elchai/about/about-reasons-icn_1.svg' },
    { n: '02', kicker: 'نحن نساعدك', title: 'تواصل مع المستثمرين',    body: 'على مدى العقد الماضي، قمنا ببناء اتصالات مع المستثمرين المهتمين بالأعمال التجارية المشابهة لشركتك. جمع الأموال يصبح أسهل معنا.',                 icon: '/elchai/about/about-reasons-icn_2.svg' },
    { n: '03', kicker: 'نحن نساعدك', title: 'البقاء في الميزانية، دائما',    body: 'ليس فقط وقتك، ولكننا نقدر أموالك أيضًا. استفد من عمليتنا الآلية لتعرف بالضبط ما تدفع مقابله واحصل على أسعار مضمونة، دون أي مفاجآت.', icon: '/elchai/about/about-reasons-icn_3.svg' },
    { n: '04', kicker: 'نحن نساعدك', title: 'اليوم وغدا وإلى الأبد', body: 'نقوم بإجراء التحديثات وإصلاح الأخطاء قبل أن تدرك وجود مشكلة. نحن نعد بتقديم الدعم الدائم لضمان أعلى جودة للحلول دون أي ضغوط.', icon: '/elchai/about/about-reasons-icn_4.svg' },
  ],

  caseStudies: [
    { label: 'حلول AI', sector: 'للصحة واللياقة البدنية', body: 'توصيات مخصصة بشأن التغذية والتمارين الرياضية، مدعومة بخوارزميات AI المتقدمة والتعلم الآلي والتحليلات التنبؤية.', logo: '/elchai/about/smartfit-logo.svg', image: '/elchai/about/smartfit-app.webp', stats: [{ value: '80%', label: 'معدل الاحتفاظ بالمستخدمين' }, { value: '20K+', label: 'تم إنشاء خطط الوجبات' }] },
    { label: 'محفظة',       sector: 'للتكنولوجيا المالية',          body: 'تم تطوير محفظة تشفير آمنة متعددة السلاسل مع بروتوكولات أمان على مستوى مؤسسي وتكامل العقود الذكية.',           logo: '/elchai/about/fintex-logo.svg',   image: '/elchai/about/fintex-app.webp',   stats: [{ value: '20%', label: 'العملات المشفرة مدعومة' }, { value: '$100K+', label: 'حجم المعاملات اليومية' }] },
    { label: 'ميتافيرس',    sector: 'للعقارات',      body: 'تم إنشاء تجربة metaverse غامرة باستخدام تقنية AR/VR وتكامل blockchain لسوق العقارات الرئيسي في Dubai.', logo: '/elchai/about/theuneverse-logo.svg', image: '/elchai/about/theuneverse-app.webp', stats: [{ value: '1000+', label: 'الخصائص الافتراضية المدرجة' }, { value: '45%', label: 'زيادة في مشاهدات العقارات' }] },
    { label: 'CRM',          sector: 'للإعلام والبحوث', body: 'تحويل بيانات الوسائط المعقدة إلى معلومات استخباراتية قابلة للتنفيذ، مما يتيح تحليل السوق في الوقت الفعلي ونمذجة الجمهور التنبؤي.',  logo: '/elchai/about/nielsen-logo.svg',  image: '/elchai/about/nielsen-app.webp',   stats: [{ value: '85%', label: 'وقت تحليل أسرع' }, { value: '60%', label: 'اتخاذ القرار بشكل أسرع' }] },
  ],
} as const;

export type AboutContent = typeof aboutContent;
