// AUTO-GENERATED by scripts/translate-content.mjs (locale: IT)
// Source: src/lib/content.ts
// DO NOT EDIT BY HAND — re-run the script to regenerate.
// Generated: 2026-05-25T08:38:51.310Z

/**
 * content.ts — Single source of truth for all copy on the Elchai Group site.
 *
 * Source: elchai-content.md (Firecrawl scrape of https://www.elchaigroup.com/).
 * Every heading, paragraph, project name, stat label and FAQ answer is
 * preserved verbatim. Do not paraphrase. If a section reuses copy (e.g. the
 * industries marquee that duplicates its list), the duplication is kept so the
 * scroll behaviour matches the source.
 *
 * Structure mirrors the section order of the original homepage.
 */

// ---------------------------------------------------------------------------
// Site-wide
// ---------------------------------------------------------------------------

export const site = {
  brand: 'Elchai Group',
  url: 'https://www.elchaigroup.com/',
  email: 'info@elchaigroup.com',
  phone: '+971 4 883 7176',
  phoneHref: 'tel:+97148837176',
  whatsapp: 'https://web.whatsapp.com/send?phone=+971501080066',
  telegram: 'https://t.me/+971501080066',
  copyright: '© Elchai Tutti i diritti riservati 2022',
  languages: [
    { label: 'العربية', code: 'ar' },
    { label: 'Inglese', code: 'en' },
    { label: 'Italiano', code: 'it' },
    { label: 'Español', code: 'es' },
  ],
} as const;

// ---------------------------------------------------------------------------
// Primary navigation (mega menus)
// ---------------------------------------------------------------------------

export const nav = {
  blockchain: {
    label: 'Blockchain',
    columns: [
      {
        title: 'Blockchain',
        items: [
          { label: 'WEB3', href: '/web3-development-company/' },
          { label: 'Metaverso', href: '/metaverse-development/' },
          { label: 'Soluzioni aziendali', href: '#consultation' },
          { label: 'DeFi', href: '/defi-development/' },
          { label: 'Contratti intelligenti', href: '/smart-contract/' },
          { label: 'NFT', href: '/nft-marketplace-development/' },
          { label: 'Tokenizzazione', href: '/rwa/' },
          { label: 'Infrastrutture', href: '#consultation' },
        ],
      },
      {
        title: 'Servizi',
        items: [
          { label: 'Consultazione sulla blockchain', href: '/blockchain-consulting-services/' },
          { label: 'Sviluppo della blockchain', href: '/blockchain-development/' },
          { label: 'Tokenizzazione delle risorse nel mondo reale', href: '/rwa/' },
          { label: 'DeFi Sviluppo', href: '/defi-development/' },
          { label: 'DApp Sviluppo', href: '/dapp-development/' },
          { label: 'Layer 1', href: '/layer-1/' },
          { label: 'Layer 2', href: '/layer-2/' },
        ],
      },
    ],
  },
  cryptocurrency: {
    label: 'Criptovaluta',
    columns: [
      {
        title: 'Portafogli',
        items: [
          { label: 'Portafoglio crittografico', href: '/crypto-wallet-development-company/' },
          { label: 'Portafogli custodiali', href: '/custodial-wallet/' },
        ],
      },
      {
        title: 'Scambi',
        items: [
          { label: 'Scambi decentralizzati (DEX)', href: '/decentralized-exchange/' },
          { label: 'Scambi centralizzati (CEX)', href: '/centralized-exchange/' },
        ],
      },
      {
        title: 'Lancio',
        items: [
          { label: 'Sviluppo dell\'ICO', href: '/ico-development/' },
          { label: 'Sviluppo delle monete', href: '/meme-coin-development/' },
          { label: 'Sviluppo dell\'IDO', href: '/ido-development/' },
        ],
      },
    ],
  },
  ai: {
    label: 'Intelligenza artificiale',
    columns: [
      {
        title: 'AI Soluzioni',
        items: [
          { label: 'AI Assistenti', href: '/ai-assistant-development/' },
          { label: 'AI Integrazione', href: '/ai-integration/' },
          { label: 'AI Automazione', href: '/ai-automation/' },
          { label: 'AI Sviluppo', href: '/ai-development/' },
          { label: 'Sviluppo dello strumento AI', href: '/ai-tool/' },
          { label: 'AI Consulenza', href: '/ai-consulting-services/' },
          { label: 'Visione artificiale', href: '/computer-vision-software-development/' },
          { label: 'LLM Sviluppo', href: '/llm-development-partner/' },
          { label: 'RAG Sviluppo', href: '/rag-development-company/' },
          { label: 'RPA Sviluppo', href: '/rpa-development-partner/' },
        ],
      },
      {
        title: 'Apprendimento automatico',
        items: [
          { label: 'ML Sviluppo', href: '/machine-learning-development/' },
          { label: 'Assumi ChatGPT sviluppatore', href: '/chat-gpt/' },
          { label: 'Agentico AI', href: '/ai-agent-development/' },
          { label: 'Assistente vocale', href: '/ai-voice-assist/' },
        ],
      },
      {
        title: 'Industrie',
        items: [
          { label: 'AI nel settore sanitario', href: '/ai-healthcare-software-development/' },
          { label: 'AI nella logistica', href: '/ai-logistics-software/' },
          { label: 'AI Nel fintech', href: '/ai-fintech-solutions/' },
          { label: 'AI nel settore bancario', href: '/ai-banking-solutions/' },
          { label: 'AI/ML Per l\'istruzione', href: '/ai-education-software/' },
          { label: 'AI Nel settore immobiliare', href: '/ai-real-estate/' },
        ],
      },
      {
        title: 'AI generativo',
        items: [
          { label: 'Sviluppo generativo AI', href: '/generative-ai-development/' },
        ],
      },
    ],
  },
  topLevel: [
    { label: 'Sviluppo di app', href: '/mobile-app-development/' },
    {
      label: 'Chi siamo',
      href: '/about-us/',
      children: [{ label: 'Stagisti', href: '/interns/' }],
    },
    {
      label: 'Risorse',
      href: '#',
      children: [
        { label: 'Blog', href: '/blog-list/' },
        { label: 'Portfolio', href: '/portfolios/' },
        { label: 'Demo dal vivo', href: '/live-demo/' },
        { label: 'Caso di studio', href: '/case-study/' },
      ],
    },
  ],
} as const;

// ---------------------------------------------------------------------------
// Hero
// ---------------------------------------------------------------------------

export const hero = {
  headline: 'Promuovere la trasformazione digitale con AI e prodotti Blockchain',
  description:
    'La nostra suite di prodotti consente alle aziende di innovare, ottimizzare e scalare utilizzando tecnologie AI e blockchain sicure.',
  bullets: [
    'Applicazioni AI personalizzate su misura per le tue esigenze aziendali.',
    'Prodotti intelligenti che apprendono, adattano e automatizzano i flussi di lavoro.',
    'Prodotti blockchain sicuri che proteggono dati e transazioni.',
  ],
  cta: { label: 'Esplora la nostra suite di prodotti', href: '#solutions' },
  trustedBy: {
    label: 'Marchio affidabile', // alt text used by every logo on the marquee
    count: 16,              // number of unique trust logos on the source page
  },
  awards: [
    'Frizione Globale 2024',
    'app mobile ogni giorno',
    'sviluppo superiore',
    'Le migliori aziende di sviluppo di app nel 2025',
    'Campione della frizione',
    'Il business delle app',
  ],
} as const;

// ---------------------------------------------------------------------------
// Stats
// ---------------------------------------------------------------------------

export const stats = {
  heading: 'Progettare l\'eccellenza digitale per oltre 150 leader del settore',
  items: [
    { value: '2,600+', label: 'Iniziative imprenditoriali trasformate' },
    { value: '8+',     label: 'Iniziative governative mission-critical' },
    { value: '11+',    label: 'Anni di eccellenza nell\'ingegneria digitale' },
    { value: '50+',    label: 'Partenariati tecnologici Fortune 100' },
    { value: '25+',    label: 'Soluzioni aziendali AI progettate' },
  ],
} as const;

// ---------------------------------------------------------------------------
// Solutions tabs
// ---------------------------------------------------------------------------

export const solutions = {
  eyebrow: 'Soluzioni',
  heading:
    'Gamma completa di soluzioni basate su AI progettate per un impatto globale',
  tabs: [
    { id: 'soluzione1', short: 'Studio',       sub: 'Esperienze digitali premium' },
    { id: 'soluzione2', short: 'App',         sub: 'AI- Generatore di app potenziato' },
    { id: 'soluzione3', short: 'Intelligenza', sub: 'Il tuo AI partner di sviluppo' },
    { id: 'soluzione4', short: 'Blockchain',   sub: 'Innovazione Blockchain di nuova generazione' },
  ],
  panels: [
    {
      id: 'soluzione1',
      title: 'Studio di sviluppo tecnologico premium',
      description:
        'Fornisci soluzioni software di livello aziendale utilizzando pratiche di sviluppo comprovate.',
      cta: { label: 'Visita il sito web', href: '#consultation' },
      categories: [
        'AI-Sviluppo di app potenziato',
        'Soluzioni aziendali',
        'Sviluppo software',
      ],
      items: ['Applicazione iOS', 'Applicazione Android', 'Applicazione svolazzante', 'App React nativa', 'Applicazione PWA'],
    },
    {
      id: 'soluzione2',
      title: 'AI- Generatore di app potenziato',
      description:
        'Soluzioni tecnologiche pronte all\'uso per casi d\'uso aziendali specifici da avviare rapidamente, senza codifica.',
      cta: { label: 'Visita il sito web', href: '/cb-apps/' },
      categories: ['Risparmia tempo e costi', 'Personalizzalo a modo tuo', 'Avvia MVP in 2 giorni'],
      items: [
        'Ordinazione e servizio\nPrenotazione',
        'Consegna\nGestione',
        'Taxi e mobilità\nSoluzione',
        'In linea\nConsultazione',
        'Tutto in uno\nMercato',
      ],
    },
    {
      id: 'soluzione3',
      title: 'Il tuo AI partner di sviluppo',
      description:
        'Creazione di soluzioni AI su misura per i brand che promuovono l\'innovazione e l\'efficienza.',
      cta: { label: 'Visita il sito web', href: '#consultation' },
      categories: [
        'Automatizza i tuoi flussi di lavoro',
        'Genera informazioni preziose',
        'Migliora l\'interazione con il cliente',
      ],
      items: [
        'AI Strategia e\nConsulenza',
        'AI Integrazione',
        'Apprendimento automatico',
        'Automazione robotica dei processi',
        'Elaborazione del linguaggio naturale',
      ],
    },
    {
      id: 'soluzione4',
      title: 'Eccellenza Web3 ingegneristica',
      description:
        'Crea prodotti blockchain sicuri per dati trasparenti e scalabili.',
      cta: { label: 'Visita il sito web', href: '#consultation' },
      categories: [
        'Sicurezza di livello aziendale',
        'Contratti intelligenti robusti',
        'Soluzioni decentralizzate scalabili',
      ],
      items: [
        'Integrazione Blockchain',
        'Tokenizzazione e NFT\nSoluzioni',
        'Criptovaluta personalizzata\nSoluzioni',
        'Contratto intelligente\nProgettazione e controllo',
        'Sviluppo di dApp su vasta scala',
      ],
    },
  ],
} as const;

// ---------------------------------------------------------------------------
// Time-zone banner
// ---------------------------------------------------------------------------

export const timeZone = {
  headline: 'Il tuo fuso orario {time}, i tuoi termini.',
  description:
    'I nostri team di sviluppo globali si allineano al tuo programma per\n\nconsegna senza soluzione di continuità, 24 ore su 24.',
  cta: { label: 'Inizia la tua trasformazione', href: '#consultation' },
} as const;

// ---------------------------------------------------------------------------
// Services grid
// ---------------------------------------------------------------------------

export const services = {
  eyebrow: 'Servizi',
  heading:
    'Creiamo nuove soluzioni e trasformiamo quelle esistenti con tecnologie di nuova generazione per rendere il tuo business a prova di futuro',
  kicker: 'Problemi tecnici che ti trattengono?',
  subheading: 'Lasciaci gestire la tecnologia mentre tu ti concentri sulla creazione del tuo core business',
  cta: { label: 'Prenota una consulenza gratuita', href: '#consultation' },
  items: [
    {
      title: 'Intelligenza artificiale',
      copy: 'Progetta sistemi intelligenti che elevano le capacità decisionali e promuovono l\'eccellenza operativa su larga scala.',
    },
    {
      title: 'Gen AI',
      copy: 'Implementa soluzioni AI all\'avanguardia che rivoluzionano la creazione di contenuti e ridefiniscono i parametri di riferimento del coinvolgimento degli utenti.',
    },
    {
      title: 'Blockchain',
      copy: 'Costruisci infrastrutture digitali immutabili che garantiscano sicurezza di livello aziendale e operazioni trasparenti.',
    },
    {
      title: 'Apprendimento automatico',
      copy: 'Trasforma i dati grezzi in intelligenza predittiva che ottimizza continuamente le prestazioni aziendali.',
    },
    {
      title: 'Scienza dei dati',
      copy: 'Converti modelli di dati complessi in strategie attuabili che accelerano la leadership di mercato.',
    },
    {
      title: 'Analisi aziendale',
      copy: 'Sblocca insight operativi nascosti che promuovono il vantaggio competitivo e alimentano la crescita strategica.',
    },
  ],
  bottomCta: {
    kicker: 'I problemi tecnologici ti trattengono?',
    headline: 'Concentrati sulla crescita mentre noi guidiamo la tua innovazione tecnologica.',
    cta: { label: 'Prenota una consulenza di livello C di 30 minuti', href: '#consultation' },
  },
} as const;

// ---------------------------------------------------------------------------
// Case studies
// ---------------------------------------------------------------------------

export const caseStudies = {
  eyebrow: 'Casi di studio',
  heading: 'Cattura l\'innovazione in azione con noi',
  description:
    'Sbircia nel futuro con i nostri progetti all\'avanguardia che stanno ridefinendo i settori.',
  navigation: [
    { n: 1, title: 'AI Soluzioni', sub: 'per salute e fitness' },
    { n: 2, title: 'Portafoglio',       sub: 'per il fintech' },
    { n: 3, title: 'Metaverso',    sub: 'per il settore immobiliare' },
    { n: 4, title: 'CRM',          sub: 'per i media' },
    { n: 5, title: 'Applicazione personalizzata',   sub: 'per il gioco' },
  ],
  items: [
    {
      slug: 'smartfit',
      tag: 'per salute e fitness',
      copy: '**Nutrizione personalizzata** e consigli sull\'allenamento, supportati da **algoritmi AI avanzati, apprendimento automatico e analisi predittiva.**',
      stats: [
        { value: '80%',  label: 'Tasso di fidelizzazione degli utenti' },
        { value: '20K+', label: 'Piani pasto generati' },
      ],
      cta: { label: 'Scarica il caso di studio', href: '#consultation' },
    },
    {
      slug: 'fintex',
      tag: 'per il fintech',
      copy: 'Sviluppato **un portafoglio crittografico multicatena sicuro** con protocolli di sicurezza di livello istituzionale e integrazione di contratti intelligenti.',
      stats: [
        { value: '20%',     label: 'Criptovalute supportate' },
        { value: '$100 K+', label: 'Volume delle transazioni giornaliere' },
      ],
      cta: { label: 'Scarica il caso di studio', href: '#consultation' },
    },
    {
      slug: 'theuneverse',
      tag: 'per il settore immobiliare',
      copy: 'Ho creato un\'esperienza coinvolgente nel metaverso utilizzando la tecnologia AR/VR e l\'integrazione blockchain per il principale mercato immobiliare di Dubai.',
      stats: [
        { value: '1000+', label: 'Proprietà virtuali elencate' },
        { value: '45%',   label: 'Aumento delle visualizzazioni delle proprietà' },
      ],
      cta: { label: 'Scarica il caso di studio', href: '#consultation' },
    },
    {
      slug: 'nielsen',
      tag: 'per i media e la ricerca',
      copy: 'Trasformare dati multimediali complessi in informazioni utilizzabili, consentendo analisi di mercato in tempo reale e modellazione predittiva del pubblico.',
      stats: [
        { value: '85%', label: 'Tempi di analisi più rapidi' },
        { value: '60%', label: 'Processo decisionale più rapido' },
      ],
      cta: { label: 'Scarica il caso di studio', href: '#consultation' },
    },
    {
      slug: 'grintafy',
      tag: 'per il gioco',
      copy: 'Piattaforma di gioco unica con funzionalità social che consente tornei dal vivo, statistiche dei giocatori e coinvolgimento della comunità.',
      stats: [
        { value: '1M+', label: 'Download degli utenti' },
        { value: '90%', label: 'Coinvolgimento degli utenti' },
      ],
      cta: { label: 'Scarica il caso di studio', href: '#consultation' },
    },
  ],
} as const;

// ---------------------------------------------------------------------------
// Industries (the source duplicates the list to fuel a marquee — we keep the
// canonical list and let the renderer duplicate at the DOM level.)
// ---------------------------------------------------------------------------

export const industries = {
  eyebrow: 'Industrie',
  heading: 'Eccellenza specifica del settore ingegneristico con AI e innovazione',
  cta: { label: 'Dimostrazione dal vivo', href: '#consultation' },
  items: [
    { title: 'Automobilistico',        copy: 'Abilita logistica predittiva, reti di mobilità connessa e intelligence operativa in tempo reale attraverso le catene di fornitura globali.' },
    { title: 'Assistenza sanitaria',        copy: 'Proteggi i flussi di dati sanitari interoperabili, migliora i risultati dei pazienti e rafforza la conformità e la fiducia istituzionale.' },
    { title: 'Finanza',           copy: 'Fornisci un\'infrastruttura finanziaria resiliente con transazioni verificabili, conformità automatizzata e analisi in tempo reale per i mercati digitali.' },
    { title: 'Assicurazione',         copy: 'Ottimizza la sottoscrizione, i sinistri e la gestione del rischio con processi automatizzati e reti di dati trasparenti e affidabili.' },
    { title: 'Commercio elettronico',        copy: 'Fornisci un commercio senza intoppi con approvvigionamento verificato, personalizzazione intelligente e operazioni omnicanale senza interruzioni.' },
    { title: 'Divertimento',     copy: 'Proteggi la proprietà digitale, monitora lo scambio di valore e migliora gli ecosistemi creatore-pubblico con strutture sicure e trasparenti.' },
    { title: 'Produzione',     copy: 'Unifica produzione, operazioni e catene di fornitura con informazioni predittive sulle prestazioni e pipeline di dati verificabili' },
    { title: 'Petrolio e gas',         copy: 'Aumenta l\'efficienza operativa e la responsabilità attraverso il monitoraggio delle risorse in tempo reale e flussi di lavoro energetici tracciabili.' },
    { title: 'Immobiliare',       copy: 'Digitalizza il ciclo di vita degli immobili con proprietà verificata, transazioni trasparenti e infrastrutture di mercato connesse.' },
    { title: 'Governo',        copy: 'Rafforzare la fiducia del pubblico con una governance basata sui dati, servizi sicuri per i cittadini e infrastrutture digitali interoperabili.' },
    { title: 'Viaggi e turismo',  copy: 'Offri esperienze di viaggio fluide con operazioni intelligenti, identità verificabili e coordinamento dell\'ecosistema in tempo reale.' },
    { title: 'Istruzione',         copy: 'Abilitare reti di apprendimento affidabili, credenziali verificabili ed ecosistemi accademici interoperabili.' },
    { title: 'Cibo e ristorante', copy: 'Garantire tracciabilità, autenticità e operazioni sostenibili della catena di fornitura dalla fonte al consumatore.' },
  ],
} as const;

// ---------------------------------------------------------------------------
// Marquee text band (between industries and "Why")
// ---------------------------------------------------------------------------

export const marqueeText = [
  'Tokenizzazione delle risorse nel mondo reale (RWA)',
  'Decentralizzazione e sistemi trustless',
  'Economia digitale guidata dal metaverso',
  'Infrastruttura Blockchain scalabile',
  'Contratti intelligenti e proprietà digitale',
] as const;

// ---------------------------------------------------------------------------
// Why Elchai
// ---------------------------------------------------------------------------

export const why = {
  eyebrow: 'Perché Elchai gruppo?',
  heading: 'Come guidiamo una trasformazione digitale di successo per te?',
  description:
    'Combiniamo le funzionalità AI di nuova generazione con la nostra comprovata esperienza per catapultare la tua attività a nuovi livelli, offrendo:',
  pillars: [
    {
      title: 'AI-Trasformazione potenziata',
      copy: 'Dall\'analisi predittiva all\'automazione intelligente, implementiamo AI per risolvere sfide aziendali complesse e scoprire nuove opportunità.',
    },
    {
      title: 'Approccio centrato sull’uomo',
      copy: 'Mentre AI accelera i processi, i nostri sviluppatori esperti garantiscono che il tocco umano rimanga al centro, creando esperienze utente eccezionali.',
    },
    {
      title: 'Scalabilità a prova di futuro',
      copy: 'Realizziamo soluzioni in grado di adattarsi e crescere insieme alla tua azienda. La nostra architettura basata su AI garantisce che le tue piattaforme si adattino perfettamente alle esigenze future.',
    },
    {
      title: 'Comunicazione e collaborazione trasparenti',
      copy: 'Rimani informato durante l\'intero processo di sviluppo con tempistiche chiare, aggiornamenti regolari e comunicazione aperta.',
    },
  ],
} as const;

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------

export const events = {
  eyebrow: 'Eventi',
  heading: 'Dimostrazione di soluzioni tecnologiche di prossima generazione su piattaforme globali',
  description:
    'Presentare gli ultimi progressi nella tecnologia di prossima generazione su piattaforme globali di prim\'ordine come GITEX Global. Esplora innovazioni rivoluzionarie in AI, IoT, blockchain e altro ancora, mentre i leader del settore dimostrano applicazioni reali che stanno rivoluzionando le aziende di tutto il mondo.',
  imagesLabel: '4+ immagini',
} as const;

// ---------------------------------------------------------------------------
// Clients & partners
// ---------------------------------------------------------------------------

export const partners = {
  eyebrow: 'Clienti e partner',
  heading:
    'Dalle startup alle imprese, trasformiamo le visioni digitali su ogni scala',
  description:
    'Collabora con esperti che trasformano le idee in soluzioni leader di mercato, indipendentemente dalle dimensioni della tua azienda o dal settore.',
  logos: [
    'Autorità per l\'assistenza familiare',
    'Grintafy',
    'Logistica',
    'NAFFCO',
    'ISUZU',
    'Zajel',
    'Strutture degli Emirati',
    'REDTAG',
    'Cura del dottor Hakeem',
    'du Pay',
    'SOBHA Immobiliare',
    'AW ROSTAMANI',
    'INGENI Salute',
    'u-vault',
    'Fedex',
    'assoli',
  ],
} as const;

// ---------------------------------------------------------------------------
// Closing CTA banner
// ---------------------------------------------------------------------------

export const closingCta = {
  heading: 'È tempo di accelerare il tuo percorso di trasformazione digitale',
  cta: { label: 'Costruiamo insieme', href: '#consultation' },
} as const;

// ---------------------------------------------------------------------------
// Resources / blog
// ---------------------------------------------------------------------------

export const resources = {
  eyebrow: 'Risorse',
  heading: 'Risorse per alimentare il tuo percorso di innovazione incentrato sul digitale',
  cta: { label: 'Più risorse', href: '/blog-list/' },
  posts: [
    {
      tag: 'blog',
      title:
        'NFT Applicazioni aziendali: innovazione delle risorse digitali oltre l\'arte e gli oggetti da collezione',
      readTime: '3 minuti di lettura',
      href: '/blog/nft-business-applications',
    },
    {
      tag: 'blog',
      title:
        'AI Soluzioni di machine learning: trasformare i dati in competitività...',
      readTime: '3 minuti di lettura',
      href: '/blog/ai-machine-learning-solutions',
    },
    {
      tag: 'blog',
      title:
        'Web3 Trasformazione digitale: soluzioni decentralizzate per...',
      readTime: '5 minuti di lettura',
      href: '/blog/web3-digital-transformation',
    },
  ],
} as const;

// ---------------------------------------------------------------------------
// FAQ
// ---------------------------------------------------------------------------

export const faq = {
  eyebrow: 'FAQ',
  heading: 'Domande frequenti',
  items: [
    {
      n: '01',
      q: 'Quali servizi di sviluppo blockchain offrite?',
      a: 'Forniamo soluzioni blockchain end-to-end dalla consulenza all\'implementazione. La nostra esperienza spazia dallo sviluppo di contratti intelligenti con verifica formale e audit di sicurezza, tokenizzazione delle risorse reali per una trasformazione digitale conforme e servizi infrastrutturali tra cui soluzioni di scalabilità Layer 1 e Layer 2, ponti cross-chain e infrastruttura di nodi. Lavoriamo in diversi settori tra cui sanità, finanza, settore immobiliare e istruzione per fornire applicazioni blockchain sicure e scalabili su misura per le tue esigenze aziendali.',
    },
    {
      n: '02',
      q: 'Quali DeFi e servizi di criptovaluta fornite?',
      a: 'Le nostre capacità DeFi coprono l\'intero spettro della finanza decentralizzata. Costruiamo protocolli personalizzati, piattaforme di yield farming e staking, soluzioni di prestito e prestito e sistemi di trading di derivati. Per quanto riguarda le criptovalute, sviluppiamo portafogli sicuri (custodiali, non custoditi e multi-firma), piattaforme di trading inclusi scambi centralizzati e decentralizzati e soluzioni complete di lancio di token per progetti ICO, STO, IDO e IGO. Creiamo inoltre bot di trading automatizzati, piattaforme di market-making e soluzioni di scambio white-label per le aziende che entrano nel settore delle criptovalute.',
    },
    {
      n: '03',
      q: 'Costruisci Web3 applicazioni e piattaforme metaverse?',
      a: 'Assolutamente. Siamo specializzati nella creazione di esperienze Web3 coinvolgenti, tra cui applicazioni decentralizzate (DApp), marketplace NFT e piattaforme metaverse complete. Le nostre soluzioni metaverse includono mondi virtuali, spazi di collaborazione 3D, sistemi di monetizzazione delle risorse digitali e applicazioni specifiche del settore per settori come la sanità, l\'istruzione e il settore immobiliare. Garantiamo un\'integrazione perfetta del portafoglio e un\'esperienza utente intuitiva che rendono la complessa tecnologia Web3 accessibile agli utenti tradizionali.',
    },
    {
      n: '04',
      q: 'Quali soluzioni AI e di machine learning offrite?',
      a: 'Trasformiamo le operazioni aziendali attraverso l\'automazione intelligente e AI avanzati. I nostri servizi includono sviluppo e integrazione AI personalizzati, modelli di machine learning per l\'analisi predittiva, soluzioni generative AI comprese implementazioni ChatGPT personalizzate e strumenti specializzati come assistenti AI, interfacce vocali e sistemi di visione artificiale. Sviluppiamo inoltre sistemi AI ad agenti autonomi, sistemi di generazione aumentata con recupero (RAG) e soluzioni di automazione dei processi robotici (RPA). La nostra esperienza AI si estende a tutti i settori con implementazioni comprovate nella diagnostica sanitaria, nella valutazione del rischio finanziario, nel rilevamento delle minacce alla sicurezza informatica, nella personalizzazione del marketing, nell\'ottimizzazione della logistica e altro ancora.',
    },
    {
      n: '05',
      q: 'Puoi integrare AI con la tecnologia blockchain?',
      a: 'Sì, eccelliamo nel combinare blockchain e AI per creare applicazioni di prossima generazione. Sviluppiamo contratti intelligenti intelligenti che utilizzano l\'apprendimento automatico per un processo decisionale dinamico, analisi basate su AI per dati on-chain, modelli predittivi per la valutazione delle risorse nel mondo reale e sistemi di trading automatizzati per protocolli DeFi. Il nostro approccio integrato include anche AI generativi per la creazione dinamica di NFT e assistenti AI incorporati in applicazioni decentralizzate, offrendoti il ​​meglio di entrambe le tecnologie rivoluzionarie.',
    },
    {
      n: '06',
      q: 'Offrite una consulenza gratuita?',
      a: 'SÌ! Forniamo una chiamata conoscitiva gratuita di 30 minuti in cui discutiamo in dettaglio del tuo progetto blockchain, Web3, DeFi, NFT o AI. Successivamente, riceverai una proposta completa che include l\'ambito del progetto, lo stack tecnologico consigliato, una tempistica dettagliata e una ripartizione trasparente dei costi. Conduciamo anche analisi di fattibilità tecnica per garantire che la vostra visione possa essere implementata con successo. Pianifica oggi stesso la tua consulenza gratuita per scoprire come possiamo trasformare la tua attività.',
    },
  ],
} as const;

// ---------------------------------------------------------------------------
// Contact
// ---------------------------------------------------------------------------

export const contact = {
  eyebrow: 'Contattaci',
  heading: 'Hai un\'idea di progetto? Contattaci!',
  presenceLabel: 'La nostra presenza',
  primary: {
    flag: 'UAE',
    city: 'Dubai',
    address:
      '2008, Jumeirah Business Center 1 - Cluster G - Al Thanyah Fifth - Jumeirah Lakes Towers - Dubai - Emirati Arabi Uniti',
    addressHref: 'https://maps.app.goo.gl/2Hm2K5nvS7sVFrxz7?g_st=ic',
    email: 'info@elchaigroup.com',
    phone: '+971 4 883 7176',
    pitch:
      'Collabora con i nostri esperti e trasforma le tue idee visionarie in soluzioni scalabili e leader di mercato',
    cta: { label: 'Connettiamoci', href: '#consultation' },
  },
  legend: [
    { label: 'Operazioni dirette e controllo strategico', href: '#Strategic' },
    { label: 'Sedi di partner e affiliati attivi',  href: '#Affiliate' },
  ],
  offices: [
    { country: 'Emirati Arabi Uniti', city: 'Dubai',     flag: 'United-Arab-Emirates' },
    { country: 'Belgium',              city: 'Brussels',  flag: 'Belgium' },
    { country: 'Albania',              city: 'Tirana',    flag: 'Albania' },
    { country: 'Sultanato di Oman',    city: 'Muscat',    flag: 'Sultanate-of-Oman' },
    { country: 'Emirati Arabi Uniti', city: 'Abu Dhabi', flag: 'United-Arab-Emirates' },
    { country: 'Hungary',              city: 'Budapest',  flag: 'Hungary' },
    { country: 'Italy',                city: 'Milan',     flag: 'Italy' },
  ],
} as const;

// ---------------------------------------------------------------------------
// Footer
// ---------------------------------------------------------------------------

export const footer = {
  columns: [
    {
      title: 'Blockchain e Web3',
      items: [
        { label: 'Sviluppo della blockchain',      href: '/blockchain-development/' },
        { label: 'DeFi Sviluppo',            href: '/defi-development/' },
        { label: 'Contratti intelligenti',             href: '/smart-contract/' },
        { label: 'NFT Sviluppo del mercato', href: '/nft-marketplace-development/' },
        { label: 'Soluzioni di tokenizzazione',      href: '/token-development/' },
        { label: 'DApp Sviluppo',            href: '/dapp-development/' },
        { label: 'Web3 Sviluppo',            href: '/web3-development-company/' },
        { label: 'Layer 1',                     href: '/layer-1/' },
        { label: 'Layer 2',                     href: '/layer-2/' },
        { label: 'Tokenizzazione delle risorse nel mondo reale', href: '/rwa/' },
      ],
    },
    {
      title: 'Criptovaluta',
      items: [
        { label: 'Sviluppo del portafoglio crittografico', href: '/crypto-wallet-development-company/' },
        { label: 'Piattaforme ICO/STO/IDO',     href: '/ico-development/' },
      ],
    },
    {
      title: 'Soluzioni del Metaverso',
      items: [
        { label: 'Sviluppo del metaverso', href: '/metaverse-development/' },
      ],
    },
    {
      title: 'AI Sviluppo',
      items: [
        { label: 'AI Consulenza',              href: '/ai-consulting-services/' },
        { label: 'Sviluppo generativo AI',  href: '/generative-ai-development/' },
        { label: 'AI Integrazione e automazione', href: '/ai-automation/' },
        { label: 'AI Sviluppo dell\'assistente',   href: '/ai-assistant-development/' },
        { label: 'Agentico AI',                 href: '/ai-agent-development/' },
      ],
    },
    {
      title: 'ML e AI avanzato',
      items: [
        { label: 'Sviluppo dell\'apprendimento automatico', href: '/machine-learning-development/' },
        { label: 'Visione artificiale',              href: '/computer-vision-software-development/' },
        { label: 'LLM Sviluppo',              href: '/llm-development-partner/' },
        { label: 'RAG Sistemi',                  href: '/rag-development-company/' },
        { label: 'RPA Soluzioni',                href: '/rpa-development-partner/' },
        { label: 'Assistenti vocali',             href: '/ai-voice-assist/' },
      ],
    },
    {
      title: 'Sviluppo di app',
      items: [
        { label: 'Sviluppo di app mobili', href: '/mobile-app-development/' },
      ],
    },
    {
      title: 'Azienda',
      items: [
        { label: 'Chi siamo',       href: '/about-us/' },
        { label: 'Blog',          href: '/blog-list/' },
        { label: 'Portafogli',     href: '/portfolios/' },
        { label: 'Demo dal vivo',     href: '/live-demo/' },
        { label: 'Caso di studio',     href: '/case-study/' },
        { label: 'politica sulla riservatezza', href: '/privacy-policy/' },
      ],
    },
  ],
  social: {
    heading: 'Seguici su',
    links: [
      { label: 'Facebook',  href: 'https://www.facebook.com/profile.php?id=100089887845364' },
      { label: 'twitter',   href: 'https://x.com/elchaigroup' },
      { label: 'linkedin',  href: 'https://www.linkedin.com/company/elchai-group/' },
      { label: 'instagram', href: 'https://www.instagram.com/elchaigroup/#' },
    ],
  },
  copyright: '© Elchai Tutti i diritti riservati 2022',
} as const;

// ---------------------------------------------------------------------------
// Modals
// ---------------------------------------------------------------------------

export const modals = {
  whatsapp: {
    heading: 'Aggiornamenti Whatsapp',
    defaultDial: '+971',
    submit: 'Invia',
  },
  consultation: {
    pretitle: 'Pianifica la tua consulenza oggi!',
    heading: 'Costruisci il tuo prossimo progetto con esperti del settore',
    description:
      'Sfrutta la tecnologia all\'avanguardia e la comprovata esperienza per trasformare il tuo business.',
    email: 'info@elchaigroup.com',
    formHeading:
      '**Compila il modulo sottostante** e il nostro team ti contatterà per discutere del tuo progetto.',
    confidentialityNote:
      'Tutte le informazioni fornite rimarranno confidenziali.',
    quickActions: [
      { label: 'Whatsapp', href: 'https://web.whatsapp.com/send?phone=+971501080066' },
      { label: 'Telegramma', href: 'https://t.me/+97150108%200066' },
    ],
  },
} as const;

// ---------------------------------------------------------------------------
// Interns — verbatim from elchaigroup.com/interns/
// ---------------------------------------------------------------------------

export const interns = {
  hero: {
    eyebrow: 'Benvenuto a Elchai Stage mondiali',
    heading: 'Avvia la tua carriera con Elchai stage mondiali',
    body: 'Acquisisci esperienza nel mondo reale, lavora a fianco di esperti del settore e sviluppa competenze che contano davvero.',
    primaryCta: { label: 'Candidati ora', href: 'https://www.elchaigroup.com/?page_id=30951' },
    ghostCta: { label: 'Esplora il programma', href: '#programmes' },
    stats: [
      { value: '12+', label: 'Stagisti attivi' },
      { value: '6+',  label: 'Dipartimenti' },
      { value: '5+',  label: 'Nazionalità' },
      { value: '3',   label: 'Lotti di stagisti' },
    ],
  },
  overview: {
    eyebrow: 'Dettagli del tirocinio',
    heading: 'Panoramica del programma di tirocinio',
    body: 'Il nostro programma di tirocinio è progettato per offrirti un\'esperienza pratica in un ambiente reale e frenetico. Fin dal primo giorno, contribuirai a progetti significativi, collaborerai con professionisti esperti e svilupperai competenze che ti prepareranno per la tua futura carriera.',
    items: [
      {
        value: '3 Months (Flexible Start)',
        title: 'Durata',
        desc: 'Durata dello stage con lotti di assunzione flessibili durante tutto l\'anno.',
      },
      {
        value: 'Dubai HQ',
        title: 'Posizione',
        desc: 'Con sede nel quartier generale Dubai con flessibilità di lavoro ibrida a seconda del ruolo.',
      },
      {
        value: '6+ Departments',
        title: 'Dipartimenti',
        desc: 'Marketing, design, tecnologia, finanza, operazioni, ricerca',
      },
      {
        value: 'Open Intake',
        title: 'Idoneità',
        desc: 'Aperto a studenti universitari e neolaureati di tutte le discipline',
      },
    ],
  },
  programmes: {
    eyebrow: 'I nostri programmi',
    heading: 'Esplora i nostri programmi di tirocinio',
    body: 'Sei percorsi specializzati che ti offrono un\'esperienza pratica nelle competenze di cui il settore ha effettivamente bisogno.',
    tracks: [
      { title: 'Marketing e crescita',          desc: 'Marketing digitale, campagne a performance, branding e strategia dei contenuti.' },
      { title: 'Design e creatività',           desc: 'UI/UX, progettazione grafica, branding e narrazione visiva.' },
      { title: 'Tecnologia e sviluppo',    desc: 'Sviluppo Web, creazione di prodotti e test di controllo qualità.' },
      { title: 'Finanza e strategia',          desc: 'Analisi finanziaria, strategia aziendale e ricerca.' },
      { title: 'Operazioni',                  desc: 'Operazioni aziendali, gestione dei processi ed esecuzione.' },
      { title: 'Ricerca e innovazione',       desc: 'Ricerche di mercato, validazione di idee e progetti di innovazione.' },
      { title: 'AI e apprendimento automatico',       desc: 'Creazione di modelli, analisi dei dati, automazione e applicazioni AI nel mondo reale.' },
      { title: 'Web3 e Blockchain',           desc: 'Contratti intelligenti, dApp, ecosistemi crittografici e tecnologie decentralizzate.' },
      { title: 'Analisi dei dati e business intelligence', desc: 'Visualizzazione dei dati, dashboard, reporting e processo decisionale basato sugli insight.' },
      { title: 'Sicurezza informatica e hacking etico',        desc: 'Fondamenti di sicurezza, analisi delle minacce e protezione dei sistemi digitali.' },
      { title: 'Gestione del prodotto',          desc: 'Strategia di prodotto, percorsi degli utenti, pianificazione della roadmap ed esecuzione tra team.' },
      { title: 'Cloud computing e DevOps',    desc: 'Piattaforme cloud, pipeline di distribuzione, infrastruttura e scalabilità del sistema.' },
    ],
  },
  why: {
    eyebrow: 'Perché unirti a noi',
    heading: 'Perché scegliere Elchai Mondo?',
    body: 'Molto più di un semplice stage: un trampolino di lancio per la tua carriera costruito su lavoro reale, mentori reali e impatto reale.',
    pillars: [
      { title: 'Progetti reali',     desc: 'Lavora su sfide aziendali dal vivo e di grande impatto che fanno una differenza misurabile fin dalla prima settimana.' },
      { title: 'Tutoraggio',        desc: 'Impara direttamente da professionisti esperti che investono nella tua crescita e nello sviluppo della tua carriera.' },
      { title: 'Sviluppo delle competenze', desc: 'Sviluppa competenze pratiche e pronte per il lavoro nella tua disciplina attraverso attività pratiche e apprendimento strutturato.' },
      { title: 'Esposizione globale',   desc: 'Collabora con un team internazionale diversificato che abbraccia più nazionalità, background e discipline.' },
    ],
  },
  meet: {
    eyebrow: 'Incontra gli stagisti',
    heading: 'Incontra i nostri stagisti',
    body: 'Un gruppo eterogeneo di individui ambiziosi che apportano nuove idee, creatività ed energia ai nostri team.',
    profiles: [
      { name: 'Abhishek Aju',   role: 'Crescita e marketing',      photo: '/elchai/interns/team/Abisheik-1.jpeg' },
      { name: 'Sanjula Hewage', role: 'Tester del controllo qualità',               photo: '/elchai/interns/team/Sanjula.jpeg' },
      { name: 'Hajara',         role: 'AI Automazione e ricerca', photo: '/elchai/interns/team/Hajra-1.jpeg' },
      { name: 'Tamara',         role: 'AI Automazione e ricerca', photo: '/elchai/interns/team/Tamara.jpeg' },
      { name: 'Rubino',          role: 'AI Automazione e ricerca', photo: '/elchai/interns/team/Rubin-1.jpeg' },
      { name: 'Sara',           role: 'AI Automazione e ricerca', photo: '/elchai/interns/team/Sara.jpeg' },
      { name: 'Naseeha',        role: 'AI Automazione e ricerca', photo: '/elchai/interns/team/Naseeha.jpeg' },
      { name: 'Shazin',         role: 'AI Automazione e ricerca', photo: '/elchai/interns/team/Shahzin.jpeg' },
    ],
    linkedinUrl: 'https://www.linkedin.com/company/86452260/',
  },
  life: {
    heading: 'La vita a Elchai',
    body: 'Da hackathon e workshop a sessioni di tutoraggio ed eventi di gruppo, i nostri stagisti imparano, costruiscono e crescono costantemente.',
    photos: [
      { alt: 'Riunione di squadra',       src: '/elchai/interns/activities/Team.jpg' },
      { alt: 'Lavoro d\'ufficio',        src: '/elchai/interns/activities/Brainstorm-session.jpg' },
      { alt: 'Sessione di brainstorming', src: '/elchai/interns/activities/Mentor-session.jpeg' },
      { alt: 'Lavorare alla scrivania',    src: '/elchai/interns/activities/Working-at-desk.jpeg' },
      { alt: 'Giornata di laboratorio',       src: '/elchai/interns/activities/Workshop-day.jpeg' },
      { alt: 'Lavoro di collaborazione',        src: '/elchai/interns/activities/Collab-work.jpeg' },
      { alt: 'Evento in ufficio',       src: '/elchai/interns/activities/IMG_4495-scaled.jpg' },
      { alt: 'Evento relatore',      src: '/elchai/interns/activities/IMG_4378-scaled.jpg' },
    ],
  },
  internLife: {
    eyebrow: 'Vita da stagista',
    heading: 'Cosa fanno i nostri stagisti',
    body: 'Dagli hackathon alle sessioni di tutoraggio: uno sguardo alla vita quotidiana dei tirocinanti.',
    pillars: [
      { title: 'Costruisci e crea',         desc: 'Hackathon e sfide di innovazione, oltre all\'esecuzione di progetti dal vivo su problemi aziendali reali fin dal primo giorno.' },
      { title: 'Impara e cresci',           desc: 'Sessioni settimanali di tutoraggio con dirigenti senior e workshop strutturati per lo sviluppo delle competenze in tutte le discipline.' },
      { title: 'Connettiti e collabora',  desc: 'Attività di collaborazione tra team e sessioni mensili di relatori di settore con leader provenienti da tutto il mondo degli affari.' },
    ],
  },
  activities: {
    eyebrow: 'Attività',
    heading: 'Cosa fanno i nostri stagisti',
    body: 'Dagli hackathon alle sessioni di tutoraggio: ecco uno sguardo a cosa sta succedendo nel programma.',
    items: [
      {
        n: '01',
        title: 'Evento Hackathon per stagisti',
        body: 'Uno sprint di progettazione e sviluppo di 48 ore in cui i team stagisti propongono soluzioni alle reali sfide aziendali. Il team vincitore si presenta direttamente al comitato esecutivo e ha l\'opportunità di vedere il proprio concetto messo in produzione.',
      },
      {
        n: '02',
        title: 'Workshop settimanale sulle sessioni di tutoraggio',
        body: 'Ogni settimana, gli stagisti vengono abbinati a un membro senior del team per una sessione strutturata individuale incentrata sullo sviluppo della carriera, feedback sui progetti e approfondimenti pratici del settore su misura per la loro disciplina.',
      },
      {
        n: '03',
        title: 'Progetto di campagna di marca dal vivo',
        body: 'Gli stagisti collaborano in modo interfunzionale per pianificare ed eseguire una vera campagna di brand, coprendo strategia, creazione di contenuti, esecuzione del canale e analisi delle prestazioni post-lancio.',
      },
      {
        n: '04',
        title: 'Evento della serie di relatori del settore',
        body: 'Sessioni mensili con relatori ospiti provenienti da imprenditoria, tecnologia, finanza e leadership creativa, che offrono prospettive sincere e consigli pratici da parte di professionisti ai vertici dei loro campi.',
      },
    ],
  },
  closing: {
    eyebrow: 'Partecipa al programma',
    heading: 'Pronto per iniziare il tuo viaggio?',
    body: 'Le candidature sono aperte. Fai il primo passo verso l\'esperienza nel mondo reale, il tutoraggio e la costruzione di qualcosa che conta.',
    primaryCta: { label: 'Candidati ora', href: 'https://www.elchaigroup.com/?page_id=30951' },
    contactCta: { label: 'Contattaci', href: 'mailto:careers@elchaigroup.com' },
  },
} as const;

// ---------------------------------------------------------------------------
// Aggregate export — single source of truth
// ---------------------------------------------------------------------------

const content = {
  site, nav, hero, stats, solutions, timeZone, services,
  caseStudies, industries, marqueeText, why, events, partners, closingCta,
  resources, faq, contact, footer, modals, interns,
} as const;

export type SiteContent = typeof content;
export default content;
