// AUTO-GENERATED by scripts/translate-content.mjs (locale: IT)
// Source: src/lib/services/ai-vertical.ts
// DO NOT EDIT BY HAND — re-run the script to regenerate.
// Generated: 2026-05-25T08:38:52.686Z

// AUTO-GENERATED by scripts/split-registry.mjs.
// Edits to this file may be overwritten — edit the legacy file and re-run
// `node scripts/split-registry.mjs` to regenerate.

import type { ServiceDetailContent } from "../service-detail-types";

export const aiBankingSolutions: ServiceDetailContent = {
  slug: "ai-banking-solutions",
  category: 'Intelligenza Artificiale · Bancario',
  hideTrustedPartners: true,
  hero: {
    eyebrow: 'AI in Banca',
    heading: 'AI nelle soluzioni bancarie',
    body:
      'Sistemi bancari intelligenti che automatizzano le operazioni, rafforzano la conformità e migliorano il coinvolgimento dei clienti attraverso un processo decisionale sicuro e basato sui dati.',
    primaryCta: { label: 'Parla con un esperto', href: "#consultation" },
    ghostCta: { label: 'Vedi Funzionalità', href: "#capabilities" },
  },
  stats: [
    { value: "4+",   label: 'Anni di esperienza',   icon: "/elchai/ai-development/ai-achievement-icn_1.svg" },
    { value: "200+", label: 'AI Soluzioni consegnate', icon: "/elchai/ai-development/ai-achievement-icn_2.svg" },
    { value: "100+", label: 'AI sviluppatori',         icon: "/elchai/ai-development/ai-achievement-icn_3.svg" },
    { value: "22+",  label: 'Paesi serviti',      icon: "/elchai/ai-development/ai-achievement-icn_4.svg" },
  ],
  capabilities: {
    eyebrow: 'Servizi',
    heading: 'AI Soluzioni bancarie create per operazioni finanziarie sicure e scalabili',
    body:
      'Dall\'automazione all\'analisi, ogni soluzione è progettata per migliorare l\'accuratezza, la conformità e la soddisfazione del cliente nei moderni ecosistemi bancari.',
    items: [
      { title: 'Sviluppo di software bancario AI personalizzato', desc: 'Costruisci sistemi AI su misura che automatizzano i flussi di lavoro, migliorano la precisione delle decisioni e supportano operazioni finanziarie complesse.',                       icon: "/elchai/ai-voice/Workflow_icons1.svg" },
      { title: 'Sistemi di rilevamento e prevenzione delle frodi',   desc: 'Rileva anomalie, segnala attività sospette e previeni crimini finanziari utilizzando modelli AI adattivi e in tempo reale.',                                  icon: "/elchai/ai-voice/Workflow_icons2.svg" },
      { title: 'Automazione del servizio clienti',            desc: 'Distribuisci AI chatbot e assistenti vocali per gestire le query di routine, aumentare la velocità di risposta e migliorare la soddisfazione degli utenti.',                         icon: "/elchai/ai-voice/Workflow_icons3.svg" },
      { title: 'Punteggio del credito e analisi del rischio',         desc: 'Analizza i profili dei mutuatari, valuta l\'affidabilità creditizia e prevedi i rischi di default utilizzando la modellazione del rischio basata su AI.',                                   icon: "/elchai/ai-voice/Workflow_icons4.svg" },
      { title: 'Automazione della conformità normativa',       desc: 'Automatizza i flussi di lavoro KYC, AML e di monitoraggio delle transazioni per garantire la piena conformità normativa con una supervisione manuale minima.',                       icon: "/elchai/ai-voice/Workflow_icons5.svg" },
      { title: 'Automazione di prestiti e mutui',             desc: 'Accelera l\'elaborazione dei prestiti, i controlli di idoneità e la verifica dei documenti attraverso l\'automazione intelligente e algoritmi predittivi.',             icon: "/elchai/ai-voice/Workflow_icons6.svg" },
      { title: 'AI-Gestione patrimoniale potenziata',           desc: 'Fornisci approfondimenti personalizzati sugli investimenti e strategie di ottimizzazione del portafoglio tramite motori di consulenza e raccomandazione basati su AI.',            icon: "/elchai/ai-voice/Workflow_icons7.svg" },
      { title: 'Approfondimenti predittivi sui clienti',           desc: 'Sfrutta l\'analisi comportamentale per identificare i rischi di abbandono, le opportunità di upsell e migliorare il valore della vita del cliente.',                                icon: "/elchai/ai-voice/Workflow_icons8.svg" },
      { title: 'Sistemi bancari vocali e chat',           desc: 'Consenti esperienze bancarie naturali e conversazionali attraverso interfacce vocali e di chat basate su AI integrate con piattaforme sicure.',                icon: "/elchai/ai-voice/Workflow_icons9.svg" },
      { title: 'Soluzioni di intelligence dei documenti',        desc: 'Automatizza l\'elaborazione dei documenti per KYC, onboarding e conformità tramite l\'estrazione e la verifica dei dati guidata da AI.',                                icon: "/elchai/ai-voice/Workflow_icons1.svg" },
      { title: 'Crimine finanziario e intelligence antiriciclaggio',            desc: 'Rileva modelli di transazioni insoliti, gestisci gli avvisi e rafforza le capacità antiriciclaggio attraverso l\'apprendimento adattivo.',                 icon: "/elchai/ai-voice/Workflow_icons2.svg" },
      { title: 'Reporting e analisi basati su AI',       desc: 'Genera report di business intelligence e conformità in tempo reale con precisione utilizzando l\'analisi AI e la visualizzazione dei dati.',                        icon: "/elchai/ai-voice/Workflow_icons3.svg" },
    ],
  },
  featureSections: [
    {
      position: "after-capabilities",
      layout: "no-image",
      eyebrow: 'Trasformazione bancaria',
      heading: 'Accelera la trasformazione bancaria con soluzioni AI personalizzate',
      body:
        'Collabora con esperti AI per progettare sistemi sicuri e scalabili che automatizzano le decisioni bancarie e migliorano la redditività.',
      cta: { label: 'Discuti il ​​tuo progetto', href: "#consultation" },
    },
    {
      position: "after-industries",
      layout: "no-image",
      eyebrow: 'Operazioni',
      heading: 'Trasforma le operazioni bancarie con sistemi AI intelligenti e affidabili',
      body:
        'Collabora con specialisti bancari AI per migliorare l\'efficienza, ridurre le frodi e offrire ai clienti esperienze eccezionali.',
      cta: { label: 'Inizia il tuo progetto bancario', href: "#consultation" },
    },
  ],
  solutions: {
    eyebrow: 'Caratteristiche',
    heading: 'AI Funzionalità bancarie progettate per precisione, conformità ed efficienza',
    body:
      'Ciascuna funzionalità migliora la trasparenza, riduce gli attriti operativi e rafforza la fiducia tra i clienti e le interazioni normative.',
    displayStyle: "photo",
    items: [
      { title: 'Rilevamento delle frodi e monitoraggio delle minacce',   desc: 'Identifica e mitiga le attività sospette in tempo reale attraverso la sorveglianza AI adattiva e il riconoscimento dei modelli.',                  image: "/elchai/banking/fraud-detection-threat-monitoring.webp" },
      { title: 'Sottoscrizione automatizzata di prestiti',           desc: 'Semplifica la valutazione del credito utilizzando l\'apprendimento automatico per analizzare in modo accurato documenti, punteggi di rischio e potenziale di rimborso.',          image: "/elchai/banking/automated-loan-underwriting.webp" },
      { title: 'Esperienze bancarie personalizzate',      desc: 'Offri consigli personalizzati sui prodotti, consulenza finanziaria e avvisi su misura per i profili e i comportamenti dei clienti.',                  image: "/elchai/banking/personalized-banking-experiences.webp" },
      { title: 'Informazioni sulla conformità normativa',    desc: 'Monitora automaticamente le transazioni e le soglie normative per soddisfare KYC, AML e altri mandati di conformità.',                       image: "/elchai/banking/regulatory-compliance-intelligence.webp" },
      { title: 'Automazione dell\'assistenza clienti',           desc: 'Fornisci risposte istantanee tramite agenti vocali e chat integrati con i dati bancari principali per la massima precisione.',                            image: "/elchai/banking/customer-support-automation.webp" },
      { title: 'Analisi predittiva per rischi e ricavi', desc: 'Prevedi il rischio di credito, liquidità e mercato identificando al contempo nuove opportunità di guadagno attraverso l\'analisi basata sui dati.',             image: "/elchai/banking/predictive-analytics-risk-revenue.webp" },
    ],
  },
  industries: {
    eyebrow: 'Settori',
    heading: 'AI Soluzioni bancarie per ogni settore',
    body: 'Progettato per servire ambienti bancari diversi con precisione, sicurezza e affidabilità.',
    items: [
      { title: 'Banche al dettaglio' },
      { title: 'Banche commerciali' },
      { title: 'Banche esclusivamente digitali' },
      { title: 'Cooperative di credito' },
      { title: 'Società bancarie private' },
      { title: 'Banche d\'investimento' },
      { title: 'Istituti di credito e mutui' },
      { title: 'Società di gestione patrimoniale' },
      { title: 'Reti di pagamento e carte' },
      { title: 'Fornitori di RegTech' },
    ],
  },
  process: {
    eyebrow: 'Processo',
    heading: 'Il processo comprovato di Elchai per lo sviluppo di soluzioni bancarie AI',
    body: 'Un flusso di lavoro strutturato e incentrato sulla conformità che garantisce affidabilità, scalabilità e allineamento con le normative bancarie globali.',
    displayStyle: "slider",
    steps: [
      { title: 'Scoperta del progetto',          desc: 'Definisci obiettivi bancari, esigenze di conformità e disponibilità dei dati per stabilire una chiara roadmap di sviluppo AI.' },
      { title: 'Preparazione dei dati',           desc: 'Aggrega e struttura i set di dati bancari per mantenere l\'accuratezza, la coerenza e la conformità agli standard finanziari.' },
      { title: 'Sviluppo e formazione del modello', desc: 'Costruisci modelli AI per il rilevamento delle frodi, l\'automazione, l\'analisi dei clienti e la valutazione del credito.' },
      { title: 'Test e convalida',       desc: 'Valuta l\'affidabilità del sistema utilizzando dati finanziari in tempo reale per garantire conformità e precisione operativa.' },
      { title: 'Distribuzione del sistema',          desc: 'Integra i modelli AI all\'interno dell\'infrastruttura bancaria esistente mantenendo le prestazioni e l\'integrità dei dati.' },
      { title: 'Ottimizzazione continua',    desc: 'Monitora i risultati del sistema, riqualifica i modelli e perfeziona i processi per garantire accuratezza e conformità costanti.' },
    ],
  },
  techStack: {
    eyebrow: 'Pila',
    heading: 'Stack tecnologico dietro le nostre soluzioni bancarie AI',
    body: 'Tecnologie sicure, scalabili e conformi che alimentano ogni fase dello sviluppo del sistema bancario intelligente.',
    displayStyle: "checklist-grid",
    groups: [
      { title: 'AI e apprendimento automatico', items: ["TensorFlow", "PyTorch", 'Transformers con volti abbracciati', 'Panda'] },
      { title: 'Sviluppo back-end',   items: ['Pitone', 'Giava', "Django", "Node.js"] },
      { title: 'Sviluppo frontend',  items: ["React.js", 'Angolare', 'Svolazzare', 'Reagire nativo'] },
      { title: 'Cloud e DevOps',        items: ["AWS", 'GoogleNuvola', 'Azioni GitHub', "Docker"] },
    ],
  },
  whyChoose: {
    eyebrow: 'Perché Elchai',
    heading: 'Partner AI di fiducia per i leader bancari globali',
    body: 'Combina una profonda conoscenza del settore con la precisione tecnica per fornire sistemi AI sicuri e pronti per la produzione per il settore bancario moderno.',
    items: [
      { title: 'Competenza bancaria a livello di settore', desc: 'Conoscenza approfondita dei quadri normativi, dei flussi di lavoro di conformità e della trasformazione digitale nel settore bancario.',        icon: "/elchai/ai-voice/ai_assist_choose_icn_1.svg" },
      { title: 'Funzionalità AI comprovate',           desc: 'Vasta esperienza nella modellazione predittiva, nel rilevamento delle frodi e nell\'automazione per sistemi finanziari su larga scala.',  icon: "/elchai/ai-voice/ai_assist_choose_icn_2.svg" },
      { title: 'Framework di sviluppo scalabili',  desc: 'Architetture flessibili progettate per adattarsi alla crescita del settore bancario, al volume dei dati e ai cambiamenti normativi.',                icon: "/elchai/ai-voice/ai_assist_choose_icn_3.svg" },
      { title: 'Collaborazione dedicata',          desc: 'Supporto continuo, visibilità condivisa e comunicazione proattiva dalla progettazione all\'implementazione e all\'ottimizzazione.',      icon: "/elchai/ai-voice/ai_assist_choose_icn_4.svg" },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    heading: 'Domande frequenti',
    items: [
      { q: 'In che modo AI migliora le operazioni bancarie?',
        a: 'AI automatizza i flussi di lavoro manuali, migliora la precisione e consente un processo decisionale in tempo reale in materia di rischio, conformità ed esperienza del cliente.' },
      { q: 'Queste soluzioni AI sono conformi alle normative bancarie?',
        a: 'Sì, tutti i sistemi seguono rigorosi standard globali, tra cui KYC, AML, GDPR, PCI-DSS e ISO 27001.' },
      { q: 'AI può integrarsi con i sistemi bancari legacy?',
        a: 'I nostri moduli AI si collegano perfettamente ai sistemi bancari, CRM e di conformità attraverso integrazioni API sicure.' },
      { q: 'Quanto tempo è necessario per lanciare una soluzione bancaria AI?',
        a: 'La distribuzione richiede in genere 6-10 settimane, a seconda dell\'ambito, della profondità di integrazione e della disponibilità dei dati.' },
      { q: 'Come viene gestita la privacy dei dati in queste soluzioni?',
        a: 'I dati sono crittografati end-to-end, con protocolli di accesso sicuri e monitoraggio continuo per garantire la conformità normativa.' },
      { q: 'Offrite supporto continuo dopo la distribuzione?',
        a: 'Sì, forniamo ottimizzazione continua, riqualificazione e aggiornamenti di conformità per mantenere l\'accuratezza e l\'affidabilità.' },
    ],
  },
  closing: {
    heading: 'Trasforma le operazioni bancarie con sistemi AI intelligenti e affidabili',
    body: 'Collabora con ingegneri che comprendano AI e il contesto normativo in cui opera la tua banca.',
    cta: { label: 'Pianifica una consulenza', href: "#consultation" },
  },
};

export const aiFintechSolutions: ServiceDetailContent = {
  slug: "ai-fintech-solutions",
  category: 'Intelligenza Artificiale · Industrie',
  hero: {
    eyebrow: 'AI nel Fintech',
    heading: 'Soluzioni Fintech basate su AI',
    subheading: 'AI Soluzioni fintech progettate per un\'innovazione finanziaria sicura e intelligente',
    body:
      'AI personalizzato progettato per casi d\'uso fintech (prestiti, pagamenti, tecnologia patrimoniale e finanza incorporata) con conformità, sicurezza e spiegabilità integrate.',
    primaryCta: { label: 'Prenota una consulenza gratuita', href: "#consultation" },
    ghostCta: { label: 'Vedi Funzionalità', href: "#capabilities" },
  },
  capabilities: {
    eyebrow: 'Caratteristiche',
    heading: 'AI Funzionalità fintech progettate per garantire precisione, conformità e scalabilità',
    items: [
      { title: 'Punteggio di credito alternativo',   desc: 'Modelli che combinano dati tradizionali e alternativi con spiegabilità e controlli equi sul prestito.' },
      { title: 'Intelligenza sui pagamenti',         desc: 'Punteggio in tempo reale per storni di addebito, falsi positivi e rischio del commerciante nei flussi di pagamento di volumi elevati.' },
      { title: 'Robo-Advisory e ricchezza AI',    desc: 'Costruzione, ribilanciamento e consulenza personalizzata del portafoglio con audit trail di livello normativo.' },
      { title: 'Finanza incorporata AI',          desc: 'API di rischio, sottoscrizione e personalizzazione per piattaforme fintech e partner BaaS.' },
      { title: 'Automazione RegTech',           desc: 'KYC, KYB, AML e monitoraggio continuo automatizzato con AI ed eccezioni human-in-the-loop.' },
      { title: 'Finanza conversazionale',       desc: 'Assistenti AI rivolti al cliente integrati con dati di account, transazioni e prodotti in modo sicuro.' },
    ],
  },
  industries: {
    eyebrow: 'Verticali',
    heading: 'AI Soluzioni Fintech progettate per ogni settore finanziario',
    items: [
      { title: 'Prestito' },
      { title: 'Pagamenti' },
      { title: "Insurtech" },
      { title: "Wealthtech" },
      { title: "RegTech" },
      { title: "BNPL" },
      { title: 'Criptofinanza' },
      { title: 'Finanza B2B' },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    heading: 'AI per Fintech: domande comuni',
    items: [
      { q: 'Come viene utilizzato AI oggi all\'interno del fintech e delle banche?',
        a: 'Automazione dei documenti (estratti conto, ID, KYC), monitoraggio delle frodi e delle transazioni antiriciclaggio, sottoscrizione e scoring del credito, agenti dell\'assistenza clienti, copiloti di tesoreria e FP&A e assistenti di conformità/revisione legale. Tanto lavoro di back-office ad alto indebitamento.' },
      { q: 'AI nel fintech è conforme a UAE?',
        a: 'Può essere, ma il lavoro è conformarsi. CBUAE si aspetta governance del rischio modello, spiegabilità e piste di controllo. Le licenze fintech DFSA richiedono controlli documentati. Mappiamo ogni implementazione al quadro normativo pertinente prima della spedizione.' },
      { q: 'Come gestite le PII e i dati dei clienti?',
        a: 'Tokenizzazione all\'acquisizione, redazione PII prima delle chiamate LLM, residenza dei dati regionali (UAE / EU), distribuzioni VPC private, crittografia BYOK e registrazione di controllo di ogni interazione del modello. La conformità è collegata all\'architettura, non fissata.' },
      { q: 'AI può sostituire il nostro team antifrode?',
        a: 'Non del tutto, ma viene valutato e intensificato. In genere riduciamo il carico di revisione manuale del 40-70% evidenziando i casi a rischio più elevato con spiegazioni, mentre i casi di routine vengono cancellati automaticamente. Gli analisti si concentrano sul centro ambiguo.' },
      { q: 'Come si misura il ROI su AI nelle operazioni finanziarie?',
        a: 'Tasso di automazione per caso, riduzione dei falsi positivi, tempo necessario per prendere una decisione, tempo medio di gestione, recuperi dalla riduzione delle frodi e costo per documento elaborato. Li strumentiamo fin dal primo giorno con report settimanali.' },
      { q: 'Ti integri con il nostro sistema bancario principale?',
        a: 'SÌ. Obiettivi comuni includono Temenos, Finacle, Mambu, Thought Machine, Fiserv DNA e core sviluppati internamente, tramite API, rilascio di file o middleware. La profondità dell\'integrazione varia in base al coinvolgimento.' },
    ],
  },
  closing: {
    heading: 'Migliora le operazioni finanziarie con una tecnologia AI intelligente e affidabile',
    body: 'Parla con i nostri ingegneri fintech AI dei sistemi di cui ha effettivamente bisogno la tua roadmap.',
    cta: { label: 'Pianifica una consulenza', href: "#consultation" },
  },
};

export const aiLogisticsSoftware: ServiceDetailContent = {
  slug: "ai-logistics-software",
  category: 'Intelligenza Artificiale · Logistica',
  hideTrustedPartners: true,
  hero: {
    eyebrow: 'AI nella logistica',
    heading: 'AI Sviluppo per la logistica',
    body:
      'Elchai progetta sistemi intelligenti che ottimizzano le reti logistiche attraverso l\'applicazione AI. Dalla modellazione predittiva della domanda all\'ottimizzazione dei percorsi in tempo reale, la nostra esperienza nello sviluppo garantisce precisione, scalabilità ed efficienza misurabile in tutte le catene di fornitura.',
    primaryCta: { label: 'Richiedi una dimostrazione', href: "#consultation" },
    ghostCta: { label: 'Vedi Funzionalità', href: "#capabilities" },
  },
  stats: [
    { value: "35%",  label: 'Riduzione dei costi operativi', icon: "/elchai/ai-development/ai-achievement-icn_1.svg" },
    { value: "42%",  label: 'Tempi di consegna più rapidi',          icon: "/elchai/ai-development/ai-achievement-icn_2.svg" },
    { value: "100+", label: 'AI Esperti',                     icon: "/elchai/ai-development/ai-achievement-icn_3.svg" },
    { value: "10+",  label: 'Anni di esperienza',            icon: "/elchai/ai-development/ai-achievement-icn_4.svg" },
  ],
  capabilities: {
    eyebrow: 'Servizi',
    heading: 'Sistemi guidati da AI per la logistica moderna',
    body:
      'Costruire sistemi logistici adattivi attraverso AI applicata, automazione e ottimizzazione intelligente dei processi.',
    items: [
      { title: 'AI-Sistemi di gestione dei trasporti ottimizzati', desc: 'Semplifica il routing, l\'invio e il bilanciamento del carico utilizzando algoritmi adattivi addestrati su dati operativi in ​​tempo reale.',            icon: "/elchai/ai-voice/Workflow_icons1.svg" },
      { title: 'Piattaforme operative di magazzino autonome',      desc: 'Coordina i sistemi robotici, il flusso di inventario e l\'automazione del prelievo attraverso modelli di apprendimento per rinforzo e visione artificiale.', icon: "/elchai/ai-voice/Workflow_icons2.svg" },
      { title: 'AI-Gestione della flotta e degli autisti infusi',         desc: 'Analizza il comportamento del conducente, la telemetria del veicolo e i parametri prestazionali per ottimizzare i cicli di utilizzo, conformità e manutenzione.', icon: "/elchai/ai-voice/Workflow_icons3.svg" },
      { title: 'AI conversazionale per operazioni logistiche',     desc: 'Consente comunicazioni in tempo reale, aggiornamenti di stato e approfondimenti operativi attraverso modelli di comprensione del linguaggio naturale addestrati sul dominio.', icon: "/elchai/ai-voice/Workflow_icons4.svg" },
      { title: 'Sistemi di intelligence sul rischio basati su AI',            desc: 'Rileva anomalie operative, prevede interruzioni e quantifica l\'esposizione al rischio utilizzando la modellazione probabilistica e l\'analisi delle tendenze storiche.', icon: "/elchai/ai-voice/Workflow_icons5.svg" },
      { title: 'Modellazione predittiva della domanda logistica',           desc: 'Prevedi i volumi delle spedizioni e le fluttuazioni della domanda regionale con previsioni di serie temporali e modelli di regressione con apprendimento automatico.', icon: "/elchai/ai-voice/Workflow_icons6.svg" },
      { title: 'Monitoraggio intelligente di risorse e veicoli',         desc: 'Combina la telemetria IoT e l\'analisi AI per una visibilità precisa sul movimento, sulle condizioni e sull\'efficienza operativa delle risorse.',     icon: "/elchai/ai-voice/Workflow_icons7.svg" },
      { title: 'Pipeline di elaborazione documenti basate su AI',         desc: 'Automatizza l\'estrazione delle fatture, la convalida delle polizze di carico e i controlli di conformità tramite pipeline OCR e NLP.',                     icon: "/elchai/ai-voice/Workflow_icons8.svg" },
      { title: 'Motori di simulazione della catena di fornitura in tempo reale',      desc: 'Replica le condizioni della rete e i vincoli dinamici per testare scenari di ottimizzazione in ambienti operativi simulati.', icon: "/elchai/ai-voice/Workflow_icons9.svg" },
    ],
  },
  featureSections: [
    {
      position: "after-capabilities",
      layout: "no-image",
      eyebrow: 'Interagisci con gli esperti',
      heading: 'Pronto a progettare AI sistemi per la tua rete logistica?',
      body:
        'Collabora con gli esperti di Elchai per progettare un\'infrastruttura logistica AI su misura per prestazioni, scalabilità e precisione.',
      cta: { label: 'Prenota una consulenza AI gratuita', href: "#consultation" },
    },
  ],
  process: {
    eyebrow: 'Processo',
    heading: 'Processo di sviluppo AI di Elchai per sistemi logistici',
    body: 'Seguiamo un processo chiaro, incentrato sulla progettazione, che trasforma le sfide logistiche in soluzioni AI scalabili e pronte per la produzione.',
    displayStyle: "slider",
    steps: [
      { title: 'Analisi dei requisiti',              desc: 'Esamina i flussi di lavoro logistici e individua le aree per l\'ottimizzazione delle prestazioni.' },
      { title: 'Valutazione di fattibilità',            desc: 'Valutare l\'ambito tecnico e il potenziale ROI per la distribuzione AI applicata.' },
      { title: 'Architettura dell\'interfaccia',            desc: 'Progetta pannelli di controllo intuitivi per la gestione e la supervisione della logistica.' },
      { title: 'Ingegneria e formazione dei modelli',      desc: 'Sviluppa e addestra architetture AI utilizzando set di dati logistici specifici del dominio.' },
      { title: 'Sviluppo e integrazione del sistema',  desc: 'Costruisci piattaforme scalabili e connettiti perfettamente con l\'infrastruttura logistica esistente.' },
      { title: 'Convalida e test delle prestazioni',  desc: 'Esegui test multilivello per garantire stabilità, affidabilità ed efficienza del throughput.' },
      { title: 'Distribuzione e lancio operativo',   desc: 'Implementa la soluzione con tempi di inattività pari a zero e piena continuità del processo.' },
      { title: 'Monitoraggio e ottimizzazione continua', desc: 'Tieni traccia dei parametri prestazionali e perfeziona il comportamento AI per un\'eccellenza operativa sostenuta.' },
    ],
  },
  impact: {
    eyebrow: 'Vantaggi',
    heading: 'In che modo AI può aiutarti nella logistica?',
    body: 'AI introduce accuratezza predittiva, automazione e intelligenza adattiva che ridefiniscono velocità, affidabilità ed efficienza delle risorse.',
    items: [
      { title: 'Accedi ai dati in tempo reale',         desc: 'Ottieni visibilità operativa immediata attraverso flussi di dati logistici sincronizzati e dashboard di analisi basati su AI.' },
      { title: 'Eliminare i rischi operativi',      desc: 'Rileva tempestivamente le interruzioni con modelli predittivi e meccanismi automatizzati di risposta al rischio nelle reti logistiche.' },
      { title: 'Garantire sicurezza e conformità',     desc: 'Sfrutta il monitoraggio AI per mantenere gli standard normativi, prevenire violazioni della sicurezza e applicare la disciplina operativa.' },
      { title: 'Ridurre costi ed emissioni',       desc: 'L\'ottimizzazione basata su AI riduce il consumo di carburante, lo spreco di risorse e l\'impronta di carbonio complessiva senza compromettere l\'efficienza.' },
      { title: 'Affinare la garanzia della qualità',         desc: 'I sistemi automatizzati di ispezione e rilevamento delle anomalie mantengono la coerenza e preservano l\'integrità della consegna.' },
      { title: 'Stabilizzare le operazioni di inventario',   desc: 'I modelli di inventario adattivi prevedono accuratamente la domanda per prevenire scorte insufficienti, eccedenti e ritardi nell\'evasione.' },
      { title: 'Semplificare l\'efficienza del percorso',      desc: 'Algoritmi di routing avanzati riducono i tempi di transito e migliorano il risparmio di carburante attraverso una pianificazione intelligente delle spedizioni.' },
      { title: 'Manutenzione predittiva avanzata',   desc: 'La diagnostica AI tiene traccia delle prestazioni delle apparecchiature per pianificare la manutenzione proattiva e prevenire tempi di fermo non pianificati.' },
      { title: 'Automatizza i flussi di lavoro della documentazione', desc: 'I sistemi OCR e NLP intelligenti digitalizzano, convalidano e gestiscono la documentazione logistica con elevata precisione.' },
    ],
  },
  techStack: {
    eyebrow: 'Pila',
    heading: 'Stack tecnologico di Elchai per lo sviluppo logistico di AI',
    body: 'Creazione di intelligence logistica con framework AI avanzati, livelli di orchestrazione e infrastruttura dati ad alte prestazioni.',
    displayStyle: "checklist-grid",
    groups: [
      { title: 'Visione artificiale',    items: ['Riconoscimento delle immagini', 'Rilevamento oggetti', 'Ispezione della qualità visiva'] },
      { title: "PyTorch",            items: ['Modelli di apprendimento profondo', 'Architetture neurali personalizzate', 'Formazione accelerata dalla GPU'] },
      { title: 'Automazione robotica', items: ['Robotica di magazzino', 'Automazione pick-and-pack', 'Coordinamento autonomo'] },
      { title: 'IoT Tecnologie',   items: ['Telemetria del sensore', 'Monitoraggio delle risorse in tempo reale', 'Intelligenza dei dispositivi edge'] },
      { title: "NLP",                items: ['Elaborazione dei documenti', 'Interfacce conversazionali', 'Supporto multilingue'] },
      { title: 'Calcolo della nuvola',    items: ['AWS/Azure/GCP', 'Inferenza scalabile', 'Orchestrazione senza server'] },
    ],
  },
  caseStudies: {
    eyebrow: 'Soluzioni in azione',
    heading: 'La nostra soluzione logistica AI in azione',
    body: 'Casi di implementazione reali che dimostrano efficienza, precisione e scalabilità misurabili negli ecosistemi logistici.',
    items: [
      {
        tabLabel: "SmartRoute AI",
        brand: 'SmartRoute AI – Ottimizzazione intelligente del percorso',
        description: 'Motore di routing adattivo che acquisisce segnali di traffico, meteo e ordini in tempo reale per ricalcolare percorsi di consegna ottimali in tempo reale tra le flotte.',
        image: "/elchai/logistics/smartroute-ai.webp",
        stats: [
          { value: "42%", label: 'Consegna più veloce' },
          { value: "35%", label: 'Risparmio di carburante' },
          { value: "98%", label: 'Consegna puntuale' },
        ],
        cta: { label: 'Richiedi una dimostrazione', href: "#consultation" },
      },
      {
        tabLabel: 'Magazzino automatizzato',
        brand: 'Gestione del magazzino automatizzato',
        description: 'Piattaforma di visione artificiale e apprendimento per rinforzo che coordina i raccoglitori robotici, l\'ottimizzazione degli slot e l\'inventario in tempo reale nei centri di distribuzione.',
        image: "/elchai/logistics/automated-warehouse.webp",
        stats: [
          { value: "50%", label: 'Evasione più rapida' },
          { value: "97%", label: 'Riduzione degli errori' },
          { value: "33%", label: 'Riduzione dei costi' },
        ],
        cta: { label: 'Richiedi una dimostrazione', href: "#consultation" },
      },
      {
        tabLabel: "FleetGuard AI",
        brand: 'FleetGuard AI – Gestione predittiva della flotta e della manutenzione',
        description: 'AI basato sulla telemetria che monitora lo stato del veicolo, prevede le esigenze di manutenzione e ottimizza l\'utilizzo per mantenere le flotte in funzione alla massima efficienza.',
        image: "/elchai/logistics/fleetguard-ai.webp",
        stats: [
          { value: "40%", label: 'Meno tempi di inattività' },
          { value: "28%", label: 'Risparmio sulla manutenzione' },
          { value: "41%", label: 'Migliore utilizzo' },
        ],
        cta: { label: 'Richiedi una dimostrazione', href: "#consultation" },
      },
    ],
  },
  whyChoose: {
    eyebrow: 'Perché Elchai',
    heading: 'Perché scegliere Elchai per lo sviluppo logistico AI?',
    body: 'Collabora con ingegneri AI applicati che decodificano la complessità logistica e forniscono precisione operativa misurabile.',
    items: [
      { title: 'Architetture AI personalizzate',   desc: 'AI sistemi progettati per i tuoi processi logistici, personalizzati per soddisfare gli obiettivi di scala, dati e prestazioni.', icon: "/elchai/ai-voice/ai_assist_choose_icn_1.svg" },
      { title: 'Integrazione di sistema semplice',   desc: 'Connettiti perfettamente con l\'infrastruttura logistica esistente garantendo al contempo una continuità operativa ininterrotta.', icon: "/elchai/ai-voice/ai_assist_choose_icn_2.svg" },
      { title: 'Collaborazione di ingegneria agile', desc: 'Sviluppo iterativo con comunicazione trasparente, convalida continua e cicli di distribuzione adattivi.',     icon: "/elchai/ai-voice/ai_assist_choose_icn_3.svg" },
      { title: 'Sicurezza e conformità innanzitutto',   desc: 'Crittografia di livello aziendale, governance dei dati e aderenza agli standard globali di logistica e protezione dei dati.',  icon: "/elchai/ai-voice/ai_assist_choose_icn_4.svg" },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    heading: 'Domande frequenti',
    items: [
      { q: 'Cosa comporta lo sviluppo logistico AI?',
        a: 'Lo sviluppo logistico AI si concentra sulla creazione di piattaforme intelligenti che automatizzano i flussi di lavoro, ottimizzano le prestazioni della catena di fornitura e ricavano informazioni utili dai dati operativi. Questi sistemi migliorano l’efficienza, riducono i costi e migliorano la precisione delle decisioni in tempo reale attraverso le reti logistiche.' },
      { q: 'In che modo AI può rafforzare le operazioni logistiche?',
        a: 'AI applica la modellazione predittiva, l\'automazione e l\'ottimizzazione adattiva ai processi logistici. Consente previsioni accurate della domanda, pianificazione efficiente dei percorsi, sincronizzazione dell\'inventario e visibilità operativa che migliorano le prestazioni e l\'efficienza dei costi.' },
      { q: 'Quali settori traggono maggiori benefici dalla logistica basata su AI?',
        a: 'Settori quali e-commerce, manifatturiero, vendita al dettaglio, automobilistico, sanitario e farmaceutico ottengono risultati misurabili dai sistemi logistici basati su AI attraverso migliori previsioni, controllo dell\'inventario e automazione operativa.' },
      { q: 'Qual è la tempistica di sviluppo tipica?',
        a: 'Lo sviluppo end-to-end dura da 3 a 12 mesi, a seconda della complessità del sistema, della disponibilità dei dati e dei livelli di integrazione richiesti.' },
      { q: 'Le piattaforme AI funzioneranno con i sistemi esistenti?',
        a: 'SÌ. Le nostre piattaforme AI si integrano perfettamente con gli ecosistemi ERP, WMS e TMS tramite API e middleware, garantendo una continuità logistica ininterrotta.' },
      { q: 'Quali guadagni aziendali ci si possono aspettare?',
        a: 'Le organizzazioni in genere ottengono una riduzione dei costi operativi del 15-40%, un miglioramento dell\'efficienza di consegna del 20-50% e una crescita della precisione nella gestione dell\'inventario del 25-60% entro il primo anno.' },
    ],
  },
  closing: {
    heading: 'Pronto a progettare AI sistemi per la tua rete logistica?',
    body: 'Collabora con Elchai per spedire AI che sopravvive al contatto con il molo, l\'autostrada e il pavimento del magazzino.',
    cta: { label: 'Pianifica una consulenza', href: "#consultation" },
  },
};

export const aiRealEstate: ServiceDetailContent = {
  slug: "ai-real-estate",
  category: 'Intelligenza Artificiale · Immobiliare',
  hideTrustedPartners: true,
  hero: {
    eyebrow: 'AI nel settore immobiliare',
    heading: 'Soluzioni immobiliari basate su AI',
    body:
      'Costruisci piattaforme immobiliari intelligenti che automatizzano le valutazioni, ottimizzano gli annunci e migliorano il processo decisionale attraverso l\'analisi predittiva.',
    primaryCta: { label: 'Parla con un esperto', href: "#consultation" },
    ghostCta: { label: 'Vedi Funzionalità', href: "#capabilities" },
  },
  stats: [
    { value: "4+",   label: 'Anni di esperienza',   icon: "/elchai/ai-development/ai-achievement-icn_1.svg" },
    { value: "200+", label: 'AI Soluzioni consegnate', icon: "/elchai/ai-development/ai-achievement-icn_2.svg" },
    { value: "100+", label: 'AI sviluppatori',         icon: "/elchai/ai-development/ai-achievement-icn_3.svg" },
    { value: "22+",  label: 'Paesi serviti',      icon: "/elchai/ai-development/ai-achievement-icn_4.svg" },
  ],
  capabilities: {
    eyebrow: 'Servizi',
    heading: 'Sistemi immobiliari completi progettati per decisioni basate sui dati',
    body:
      'Progettato per automatizzare la gestione immobiliare, migliorare l\'esperienza degli acquirenti e aumentare la redditività attraverso l\'automazione e l\'intelligenza predittiva.',
    items: [
      { title: 'Valutazione immobiliare intelligente',   desc: 'Valuta istantaneamente il valore della proprietà utilizzando modelli basati su AI in base alla posizione, alla domanda e alle tendenze del mercato.',            icon: "/elchai/ai-voice/Workflow_icons1.svg" },
      { title: 'Intelligenza predittiva del mercato',   desc: 'Prevedi variazioni dei prezzi e opportunità di investimento attraverso l\'analisi del mercato in tempo reale e dei dati storici.',       icon: "/elchai/ai-voice/Workflow_icons2.svg" },
      { title: 'Operazioni immobiliari intelligenti',        desc: 'Automatizza la manutenzione, l\'uso dell\'energia e la gestione degli inquilini per migliorare l\'efficienza operativa e il risparmio sui costi.',       icon: "/elchai/ai-voice/Workflow_icons3.svg" },
      { title: 'AI Assistenti immobiliari',        desc: 'Gestisci le richieste dei clienti, pianifica le visite e gestisci i lead con l\'interazione AI in linguaggio naturale.',                icon: "/elchai/ai-voice/Workflow_icons4.svg" },
      { title: 'Tour virtuali delle proprietà in 3D',        desc: 'Offri esperienze immobiliari coinvolgenti e migliorate AI che semplificano le decisioni di acquisto e affitto a distanza.',            icon: "/elchai/ai-voice/Workflow_icons5.svg" },
      { title: 'Esperienze cliente personalizzate',  desc: 'Consigliare proprietà e offerte su misura per le preferenze dell\'acquirente o dell\'affittuario e i dati comportamentali.',                       icon: "/elchai/ai-voice/Workflow_icons6.svg" },
      { title: 'Strumenti di ottimizzazione del portafoglio',     desc: 'Utilizza l\'analisi AI per bilanciare il rischio, ottimizzare gli investimenti e massimizzare le prestazioni del portafoglio immobiliare.',            icon: "/elchai/ai-voice/Workflow_icons7.svg" },
      { title: 'Sistemi di automazione del flusso di lavoro',      desc: 'Automatizza gli aggiornamenti delle inserzioni, la gestione dei documenti e la reportistica per accelerare le vendite e ridurre le attività manuali.',            icon: "/elchai/ai-voice/Workflow_icons8.svg" },
      { title: 'Avatar AI virtuali',               desc: 'Coinvolgi gli acquirenti tramite avatar AI interattivi per presentazioni guidate e conversazionali delle proprietà.',                    icon: "/elchai/ai-voice/Workflow_icons9.svg" },
    ],
  },
  featureSections: [
    {
      position: "after-capabilities",
      layout: "image-right",
      eyebrow: 'Accelerare la crescita',
      heading: 'Accelera la crescita del settore immobiliare con soluzioni personalizzate basate su AI',
      image: "/elchai/real-estate/ctaRealEstate_AI.webp",
      body:
        'Collabora con gli ingegneri AI per creare sistemi intelligenti che automatizzano i flussi di lavoro e migliorano il processo decisionale relativo alle proprietà.',
      cta: { label: 'Inizia il tuo progetto', href: "#consultation" },
    },
  ],
  process: {
    eyebrow: 'Metodo',
    heading: 'Il metodo di Elchai per il settore immobiliare alimentato da AI',
    body: 'Un flusso di lavoro strutturato e trasparente progettato per garantire precisione, scalabilità e prestazioni reali in ogni applicazione immobiliare.',
    displayStyle: "slider",
    steps: [
      { title: 'Scoperta del progetto',        desc: 'Definisci obiettivi aziendali, utenti target e flussi di lavoro operativi per delineare una roadmap mirata per il settore immobiliare AI.' },
      { title: 'Preparazione dei dati',         desc: 'Raccogli, ripulisci e struttura i dati di proprietà, mercato e clienti per un\'accurata formazione e analisi dei modelli.' },
      { title: 'Sviluppo del modello',        desc: 'Costruisci e addestra AI modelli per la valutazione, l\'automazione, i consigli o le previsioni di mercato predittive.' },
      { title: 'Test e convalida',     desc: 'Convalida AI i risultati in termini di accuratezza, prestazioni e affidabilità utilizzando set di dati e benchmark specifici del settore immobiliare.' },
      { title: 'Distribuzione e integrazione', desc: 'Integra le soluzioni AI nei sistemi immobiliari esistenti, nelle piattaforme CRM e negli strumenti di gestione della proprietà.' },
      { title: 'Monitoraggio e ottimizzazione',desc: 'Monitora continuamente le prestazioni di AI, perfeziona gli algoritmi e aggiorna i set di dati per migliorare precisione e adattabilità.' },
    ],
  },
  impact: {
    eyebrow: 'Risultati',
    heading: 'Intelligence immobiliare che trasforma i dati in risultati misurabili',
    body: 'Dalla valutazione della proprietà alla gestione del rischio, scopri come AI automatizza le decisioni, migliora le prestazioni e personalizza le esperienze.',
    items: [
      { title: 'Valutazione immobiliare predittiva',            desc: 'Stima i prezzi degli immobili utilizzando modelli AI addestrati su indicatori di mercato storici e in tempo reale.' },
      { title: 'Generazione di lead e coinvolgimento dei clienti',    desc: 'Automatizza il contatto con gli acquirenti, coltiva i lead e fornisci comunicazioni personalizzate attraverso approfondimenti basati su AI.' },
      { title: 'Tour virtuali delle proprietà',                   desc: 'Offri procedure dettagliate coinvolgenti e interattive sulle proprietà per consentire decisioni di acquisto informate e a distanza.' },
      { title: 'Analisi predittiva del mercato',              desc: 'Anticipa le tendenze dei prezzi, i modelli della domanda e le opportunità di investimento con la modellazione avanzata dei dati.' },
      { title: 'Gestione intelligente della proprietà',                desc: 'Automatizza le richieste di manutenzione, le comunicazioni con gli inquilini e il monitoraggio della struttura per operazioni immobiliari efficienti.' },
      { title: 'Raccomandazioni personalizzate',             desc: 'Fornisci suggerimenti di proprietà selezionati da AI in base alle intenzioni, alle preferenze e al comportamento di ricerca dell\'utente.' },
      { title: 'Ottimizzazione degli investimenti e del portafoglio',      desc: 'Bilancia rischio e performance tra i portafogli utilizzando algoritmi di gestione patrimoniale basati sui dati.' },
      { title: 'Gestione del rischio e rilevamento delle frodi',        desc: 'Identifica inserzioni, transazioni o irregolarità della proprietà fraudolente attraverso il rilevamento delle anomalie e l\'analisi predittiva dei rischi.' },
      { title: 'Gestione dell\'energia e delle risorse',             desc: 'Ottimizza l\'allocazione delle risorse, monitora il consumo energetico e riduci i costi attraverso sistemi intelligenti IoT basati su AI.' },
    ],
  },
  midBanner: {
    heading: 'Realizza sistemi immobiliari più intelligenti con soluzioni AI personalizzate',
    cta: { label: 'Inizia il tuo progetto', href: "#consultation" },
  },
  caseStudies: {
    eyebrow: 'Soluzioni in azione',
    heading: 'Costruito, implementato e con un impatto misurabile nel settore immobiliare',
    body: 'Esplora progetti di successo realizzati per automatizzare la valutazione, ottimizzare i portafogli e migliorare l\'esperienza dei clienti nel settore immobiliare.',
    items: [
      {
        tabLabel: 'Valutazione intelligente',
        brand: 'Piattaforma intelligente di valutazione immobiliare',
        description: 'Sistema basato su AI che fornisce valutazioni immobiliari precise attraverso l\'analisi del mercato, della posizione e delle tendenze in tempo reale.',
        image: "/elchai/real-estate/ai_real_estate_valuation.webp",
        stats: [
          { value: "95%", label: 'Precisione della valutazione' },
          { value: "30%", label: 'Decisioni più rapide' },
          { value: "50%", label: 'Meno ricerca manuale' },
        ],
        cta: { label: 'Richiedi una dimostrazione', href: "#consultation" },
      },
      {
        tabLabel: 'Tour virtuali',
        brand: 'Tour virtuali delle proprietà e assistente AI',
        description: 'Piattaforma AI integrata che offre tour immersivi delle proprietà con assistenza immediata e conversazionale all\'acquirente.',
        image: "/elchai/real-estate/ai_virtual_property_tour.webp",
        stats: [
          { value: "3×",  label: 'Maggiore coinvolgimento dei lead' },
          { value: "40%", label: 'Conversioni più veloci' },
          { value: "24/7", label: 'Supporto all\'acquirente' },
        ],
        cta: { label: 'Richiedi una dimostrazione', href: "#consultation" },
      },
    ],
  },
  techStack: {
    eyebrow: 'Pila',
    heading: 'Framework, modelli e piattaforme alla base delle nostre soluzioni AI immobiliari',
    body: 'Uno stack tecnologico affidabile che combina apprendimento automatico, visione artificiale, PNL e infrastruttura cloud sicura per prestazioni scalabili.',
    displayStyle: "checklist-grid",
    groups: [
      { title: 'Intelligenza artificiale e apprendimento automatico', items: ['Pitone', "TensorFlow", "PyTorch", 'Scikit-impara'] },
      { title: 'Gestione e analisi dei dati',                items: ["SQL", "MongoDB", "Apache Spark", "Hadoop"] },
      { title: 'Cloud e DevOps',                             items: ["AWS", 'GoogleNuvola', 'Azzurro', "Docker"] },
      { title: 'Chatbot e assistenti virtuali',              items: ['Flusso di dialogo', "Rasa", "Microsoft Bot Framework"] },
    ],
  },
  whyChoose: {
    eyebrow: 'Perché Elchai',
    heading: 'Competenza, Precisione e Affidabilità in Ogni Soluzione AI Immobiliare',
    body: 'Combina informazioni approfondite sul settore immobiliare con l\'ingegneria AI avanzata per offrire una tecnologia immobiliare scalabile, conforme e ad alte prestazioni.',
    items: [
      { title: 'Competenza specifica del settore',        desc: 'Vasta esperienza nella creazione di soluzioni AI su misura per il settore immobiliare, la gestione immobiliare e l\'innovazione proptech.', icon: "/elchai/ai-voice/ai_assist_choose_icn_1.svg" },
      { title: 'Sistemi AI personalizzati',            desc: 'Soluzioni progettate da zero per soddisfare obiettivi aziendali, ecosistemi di dati e requisiti operativi.',          icon: "/elchai/ai-voice/ai_assist_choose_icn_2.svg" },
      { title: 'Capacità di sviluppo end-to-end',  desc: 'Supporto completo del ciclo di vita: dalla progettazione del modello all\'implementazione, al monitoraggio e all\'ottimizzazione a lungo termine.',                    icon: "/elchai/ai-voice/ai_assist_choose_icn_3.svg" },
      { title: 'Collaborazione trasparente',          desc: 'Una comunicazione chiara, il monitoraggio delle tappe fondamentali e una consegna coerente garantiscono affidabilità e allineamento durante l\'intero progetto.', icon: "/elchai/ai-voice/ai_assist_choose_icn_4.svg" },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    heading: 'Domande frequenti',
    items: [
      { q: 'Quali tipi di soluzioni AI sono sviluppate per il settore immobiliare?',
        a: 'Le soluzioni includono sistemi di valutazione immobiliare, assistenti virtuali, piattaforme di analisi predittiva e strumenti di gestione basati su AI per le operazioni immobiliari.' },
      { q: 'Le piattaforme AI possono integrarsi con i CRM immobiliari o i database immobiliari esistenti?',
        a: 'L\'integrazione è supportata per tutti i principali CRM e sistemi di elenchi tramite API sicure e connettori dati personalizzati.' },
      { q: 'Quanto sono accurati i sistemi di valutazione immobiliare basati su AI?',
        a: 'L’accuratezza della valutazione supera generalmente il 90%, a seconda della qualità dei dati, delle tendenze regionali e delle fluttuazioni del mercato.' },
      { q: 'Gli assistenti virtuali AI sono adatti sia per le proprietà commerciali che residenziali?',
        a: 'Sì, gli assistenti sono progettati per gestire domande, pianificazione e tour nei mercati residenziale, commerciale e degli affitti.' },
      { q: 'In che modo AI migliora l\'efficienza della gestione della proprietà?',
        a: 'AI automatizza la pianificazione della manutenzione, l\'ottimizzazione energetica, la comunicazione con gli inquilini e il reporting per ridurre il carico di lavoro manuale.' },
      { q: 'La manutenzione e l\'ottimizzazione continue sono incluse dopo la distribuzione?',
        a: 'Il monitoraggio continuo dei modelli, gli aggiornamenti dei dati e i miglioramenti delle prestazioni garantiscono precisione costante e stabilità della piattaforma.' },
    ],
  },
  closing: {
    heading: 'Realizza sistemi immobiliari più intelligenti con soluzioni AI personalizzate',
    body: 'Collabora con specialisti AI per creare piattaforme immobiliari in grado di prevedere tendenze, coinvolgere i clienti e automatizzare i flussi di lavoro.',
    cta: { label: 'Inizia il tuo progetto', href: "#consultation" },
  },
};

export const aiHealthcareSoftware: ServiceDetailContent = {
  slug: "ai-healthcare-software-development",
  category: 'Intelligenza Artificiale · Sanità',
  hideTrustedPartners: true,
  hero: {
    eyebrow: 'AI Sanità',
    heading: 'AI Sviluppo di software sanitario',
    body:
      'Crea software sanitario sicuro e intelligente per semplificare le operazioni, migliorare la diagnostica, potenziare la cura dei pazienti e prendere decisioni cliniche supportate dai dati.',
    primaryCta: { label: 'Inizia', href: "#consultation" },
    ghostCta: { label: 'Vedi Funzionalità', href: "#capabilities" },
  },
  stats: [
    { value: "10+",  label: 'Anni di esperienza',   icon: "/elchai/ai-development/ai-achievement-icn_1.svg" },
    { value: "120+", label: 'AI Soluzioni consegnate', icon: "/elchai/ai-development/ai-achievement-icn_2.svg" },
    { value: "100+", label: 'AI sviluppatori',         icon: "/elchai/ai-development/ai-achievement-icn_3.svg" },
    { value: "30+",  label: 'Paesi serviti',      icon: "/elchai/ai-development/ai-achievement-icn_4.svg" },
  ],
  capabilities: {
    eyebrow: 'Servizi',
    heading: 'AI Soluzioni sanitarie progettate per le moderne esigenze mediche',
    body:
      'Costruiamo sistemi intelligenti che automatizzano la diagnostica, migliorano il coinvolgimento dei pazienti e semplificano la gestione dei dati nelle reti sanitarie.',
    items: [
      { title: 'AI-Diagnostica e imaging potenziati',   desc: 'Migliora la precisione e la velocità dell\'analisi delle immagini mediche attraverso l\'automazione.',                              icon: "/elchai/ai-voice/Workflow_icons1.svg" },
      { title: 'Sviluppo della piattaforma di telemedicina',    desc: 'Fornisci consulenze virtuali sicure e in tempo reale con sistemi di triage AI avanzati.',                       icon: "/elchai/ai-voice/Workflow_icons2.svg" },
      { title: 'Chatbot di supporto ai pazienti',             desc: 'Fornire assistenza 24 ore su 24, 7 giorni su 7 per programmazione, prescrizioni e richieste di assistenza sanitaria generale.',               icon: "/elchai/ai-voice/Workflow_icons3.svg" },
      { title: 'Sistemi di monitoraggio remoto dei pazienti',    desc: 'Tieni traccia dei parametri vitali e degli avvisi in tempo reale per un intervento proattivo.',                                       icon: "/elchai/ai-voice/Workflow_icons4.svg" },
      { title: 'Automazione EHR ed EMR',                 desc: 'Semplifica l\'immissione dei dati, la gestione dei record e l\'interoperabilità tra i sistemi medici.',                icon: "/elchai/ai-voice/Workflow_icons5.svg" },
      { title: 'Piattaforme di analisi sanitaria',       desc: 'Trasforma i dati clinici e operativi in ​​informazioni predittive per decisioni migliori.',                 icon: "/elchai/ai-voice/Workflow_icons6.svg" },
      { title: 'AI Integrazione per i sistemi sanitari',desc: 'Integra l\'automazione intelligente nel software esistente per ospedali, laboratori e farmacie.',                       icon: "/elchai/ai-voice/Workflow_icons7.svg" },
      { title: 'Implementazione dell\'agente AI',            desc: 'Distribuisci agenti AI adattivi che gestiscono i flussi di lavoro e coordinano le attività sanitarie.',                       icon: "/elchai/ai-voice/Workflow_icons8.svg" },
      { title: 'Innovazione sanitaria AI di prossima generazione',    desc: 'Crea soluzioni scalabili e pronte per il futuro sfruttando le più recenti tecnologie mediche AI.',                   icon: "/elchai/ai-voice/Workflow_icons9.svg" },
    ],
  },
  midBanner: {
    heading: 'Trasforma le operazioni sanitarie con soluzioni AI intelligenti e personalizzate',
    cta: { label: 'Inizia oggi', href: "#consultation" },
  },
  solutions: {
    eyebrow: 'Caratteristiche',
    heading: 'AI Funzionalità sanitarie progettate per garantire precisione, efficienza e sicurezza',
    body:
      'Le soluzioni di Elchai combinano automazione, previsione e intelligenza per semplificare le operazioni e rafforzare l\'erogazione di cure incentrate sul paziente.',
    displayStyle: "photo",
    items: [
      { title: 'Automatizza il flusso di lavoro amministrativo',        desc: 'Semplifica la pianificazione, la fatturazione e la documentazione attraverso l\'automazione intelligente che riduce lo sforzo manuale e i ritardi operativi.', image: "/elchai/healthcare/automate-workflow.webp" },
      { title: 'Previsione della riammissione del paziente',          desc: 'Utilizza la modellazione predittiva per identificare precocemente i pazienti ad alto rischio e consentire interventi tempestivi per risultati migliori.',                image: "/elchai/healthcare/patient-readmission.webp" },
      { title: 'Gestione delle cartelle cliniche',               desc: 'Garantisci un accesso sicuro, accurato e in tempo reale ai dati dei pazienti su tutti i sistemi con sincronizzazione automatizzata.',                       image: "/elchai/healthcare/health-records.webp" },
      { title: 'Rilevamento delle frodi e sicurezza dei dati',       desc: 'Rileva immediatamente le anomalie, previeni le violazioni dei dati e mantieni la completa conformità normativa utilizzando le protezioni AI avanzate.',       image: "/elchai/healthcare/fraud-detection.webp" },
      { title: 'Analisi predittiva',                    desc: 'Sfrutta gli insight basati sui dati per prevedere le tendenze sanitarie, ottimizzare le risorse e migliorare la precisione della pianificazione del trattamento.',         image: "/elchai/healthcare/predictive-analytics.webp" },
      { title: 'AI-Imaging medico e diagnostica potenziati',desc: 'Accelera la diagnosi con modelli di machine learning che interpretano le scansioni in modo accurato e segnalano automaticamente le anomalie.',            image: "/elchai/healthcare/medical-imaging.webp" },
    ],
  },
  featureSections: [
    {
      position: "after-techStack",
      layout: "image-right",
      eyebrow: 'Rete conforme',
      heading: 'Crea oggi stesso applicazioni sanitarie AI sicure, scalabili e conformi',
      image: "/elchai/healthcare/ctaCompliant_Network.webp",
      body:
        'Collabora con il nostro team di sviluppo per creare sistemi sanitari intelligenti in linea con rigorosi standard medici.',
      cta: { label: 'Parla con i nostri esperti', href: "#consultation" },
    },
  ],
  industries: {
    eyebrow: 'Funzioni sanitarie',
    heading: 'AI in azione nelle funzioni sanitarie critiche',
    body: 'Scopri come le soluzioni AI personalizzate migliorano la precisione, l\'efficienza e l\'assistenza ai pazienti in diverse operazioni mediche.',
    items: [
      { title: 'Intelligenza clinica',            desc: 'Supporta i medici con approfondimenti basati su AI che migliorano l\'accuratezza diagnostica e le previsioni sugli esiti dei pazienti.' },
      { title: 'Accelerazione della scoperta dei farmaci',      desc: 'Utilizza l\'apprendimento automatico per identificare composti, ottimizzare le sperimentazioni e ridurre il time-to-market per nuove terapie.' },
      { title: 'Analisi sanitaria predittiva',  desc: 'Prevedi i rischi dei pazienti, la domanda di risorse e i risultati del trattamento attraverso la modellazione e l\'analisi dei dati in tempo reale.' },
      { title: 'Ottimizzazione dell\'efficienza operativa', desc: 'Semplifica i flussi di lavoro ospedalieri, riduci i costi amministrativi e automatizza le attività ripetitive per migliorare la produttività.' },
      { title: 'Infrastruttura dati unificata',      desc: 'Integra più fonti di dati sanitari per creare un ecosistema di informazioni centralizzato, sicuro e interoperabile.' },
      { title: 'Pianificazione del trattamento di precisione',     desc: 'Sfrutta i dati specifici del paziente per progettare piani di trattamento personalizzati per risultati migliori e complicazioni ridotte.' },
    ],
  },
  caseStudies: {
    eyebrow: 'Casi di studio',
    heading: 'AI Soluzioni sanitarie realizzate per un reale impatto clinico',
    body: 'Scopri come i sistemi AI personalizzati di Elchai aiutano gli operatori sanitari a migliorare la diagnostica, automatizzare i flussi di lavoro e migliorare i risultati per i pazienti.',
    items: [
      {
        tabLabel: 'MedAI Diagnostica',
        brand: 'MedAI Diagnostica',
        description: 'Piattaforma di imaging basata su AI che analizza raggi X, risonanze magnetiche e scansioni TC per informazioni diagnostiche più rapide e accurate.',
        image: "/elchai/healthcare/medical-imaging.webp",
        stats: [
          { value: "40%",    label: 'Elaborazione diagnostica più rapida' },
          { value: "35%",    label: 'Maggiore precisione di rilevamento' },
          { value: "5,000+", label: 'Pazienti diagnosticati più velocemente' },
        ],
        cta: { label: 'Mettiti in contatto', href: "#consultation" },
      },
      {
        tabLabel: 'Assistente SmartCare',
        brand: 'Assistente SmartCare',
        description: 'Assistente sanitario virtuale che utilizza la PNL e l\'analisi predittiva per gestire le domande, la pianificazione e il coinvolgimento dei pazienti.',
        image: "/elchai/healthcare/automate-workflow.webp",
        stats: [
          { value: "50,000+", label: 'Interazioni mensili con i pazienti' },
          { value: "30%",     label: 'Meno carico di lavoro amministrativo' },
          { value: "25%",     label: 'Maggiore coinvolgimento del paziente' },
        ],
        cta: { label: 'Mettiti in contatto', href: "#consultation" },
      },
      {
        tabLabel: "CareFlow AI",
        brand: "CareFlow AI",
        description: 'Piattaforma di analisi predittiva che ottimizza le operazioni ospedaliere, l\'allocazione delle risorse e l\'efficienza del flusso di lavoro clinico.',
        image: "/elchai/healthcare/predictive-analytics.webp",
        stats: [
          { value: "40%", label: 'Aumento dell’efficienza operativa' },
          { value: "35%", label: 'Migliore utilizzo del letto' },
          { value: "20%", label: 'Tempi di attesa dei pazienti più brevi' },
        ],
        cta: { label: 'Mettiti in contatto', href: "#consultation" },
      },
    ],
  },
  techStack: {
    eyebrow: 'Pila',
    heading: 'Stack tecnologico alla base di AI soluzioni sanitarie',
    body: 'Elchai combina framework avanzati di machine learning, infrastruttura cloud sicura e integrazioni di livello sanitario per creare sistemi AI scalabili e conformi.',
    displayStyle: "checklist-grid",
    groups: [
      { title: 'AI e framework di machine learning', items: ["TensorFlow", "PyTorch", "Keras", 'Scikit-impara'] },
      { title: 'Piattaforme cloud (conformi a HIPAA)', items: ['PostgreSQL/MySQL', "MongoDB – NoSQL", 'Standard FHIR/HL7', 'Fiocco di neve/BigQuery'] },
      { title: 'API e integrazioni',              items: ['API Google Cloud Healthcare', 'Apple HealthKit/Google Fit', 'API FHIR', 'Medprugna'] },
    ],
  },
  process: {
    eyebrow: 'Processo',
    heading: 'Processo strutturato Elchai per lo sviluppo di software sanitario AI',
    body: 'Dalla scoperta all\'implementazione, seguiamo un processo trasparente e basato sui dati che garantisce conformità, scalabilità e prestazioni di livello clinico.',
    displayStyle: "slider",
    steps: [
      { title: 'Scoperta del progetto',        desc: 'Identifica obiettivi, esigenze di conformità e lacune nel flusso di lavoro per definire una chiara tabella di marcia per lo sviluppo sanitario AI.' },
      { title: 'Preparazione dei dati',         desc: 'Raccogli, ripulisci e struttura set di dati medici garantendo privacy, accuratezza e conformità alle normative sanitarie.' },
      { title: 'Ingegneria dei modelli',        desc: 'Progetta, forma e ottimizza AI modelli su misura per attività di diagnostica, automazione e coinvolgimento dei pazienti.' },
      { title: 'Convalida della qualità',       desc: 'Esegui controlli su prestazioni, sicurezza e conformità per garantire che i modelli soddisfino gli standard di affidabilità di livello clinico.' },
      { title: 'Distribuzione del sistema',        desc: 'Integra i moduli AI nei sistemi sanitari esistenti con un\'implementazione sicura, scalabile e senza interruzioni.' },
      { title: 'Ottimizzazione continua',  desc: 'Monitora le prestazioni del mondo reale, perfeziona i modelli e aggiorna gli algoritmi per garantire precisione e stabilità durature.' },
    ],
  },
  whyChoose: {
    eyebrow: 'Perché Elchai',
    heading: 'Il tuo partner nella creazione di un\'intelligence sanitaria affidabile e conforme',
    body: 'Elchai combina competenze nel settore, comprensione delle normative e ingegneria AI avanzata per creare software sanitario affidabile e orientato ai risultati.',
    items: [
      { title: 'Comprovata AI competenza nel settore sanitario',   desc: 'Anni di esperienza nella fornitura di sistemi AI di livello medico apprezzati da ospedali, laboratori e startup sanitarie.', icon: "/elchai/ai-voice/ai_assist_choose_icn_1.svg" },
      { title: 'Conformità normativa',            desc: 'Soluzioni realizzate per soddisfare gli standard HIPAA, GDPR e FDA per la protezione dei dati e l\'affidabilità clinica.',          icon: "/elchai/ai-voice/ai_assist_choose_icn_2.svg" },
      { title: 'Servizi di sviluppo end-to-end',  desc: 'Dalla preparazione dei dati all\'implementazione e al supporto, ogni fase è gestita da specialisti AI sanitari dedicati.',  icon: "/elchai/ai-voice/ai_assist_choose_icn_3.svg" },
      { title: 'Soluzioni personalizzate',           desc: 'Software AI personalizzato, progettato in base ai flussi di lavoro clinici e ai requisiti operativi specifici.',            icon: "/elchai/ai-voice/ai_assist_choose_icn_4.svg" },
    ],
  },
  extraBanners: [
    {
      position: "after-industries",
      heading: 'Porta intelligenza e automazione a ogni livello dell\'assistenza sanitaria',
      cta: { label: 'Prenota una consulenza', href: "#consultation" },
    },
  ],
  faq: {
    eyebrow: "FAQ",
    heading: 'Domande frequenti',
    items: [
      { q: 'Quali tipi di soluzioni sanitarie AI vengono sviluppate?',
        a: 'Le soluzioni includono piattaforme di imaging diagnostico, applicazioni di telemedicina, sistemi di monitoraggio dei pazienti, dashboard di analisi sanitaria e software di automazione del flusso di lavoro.' },
      { q: 'In che modo viene garantita la conformità normativa nei AI progetti sanitari?',
        a: 'Tutti i sistemi sono realizzati secondo gli standard HIPAA, GDPR e FDA con gestione dei dati crittografati, anonimizzati e pronti per il controllo.' },
      { q: 'Il software sanitario AI può integrarsi con i sistemi medici esistenti?',
        a: 'L\'integrazione è supportata per EHR, EMR e piattaforme sanitarie di terze parti tramite API sicure e standard di interoperabilità.' },
      { q: 'Come vengono protetti i dati sanitari sensibili?',
        a: 'La sicurezza dei dati viene mantenuta utilizzando la crittografia end-to-end, l\'accesso controllato e valutazioni periodiche delle vulnerabilità in tutti gli ambienti.' },
      { q: 'Quali tecnologie vengono comunemente utilizzate per lo sviluppo di software sanitario AI?',
        a: 'Lo sviluppo utilizza in genere Python, TensorFlow, PyTorch, AWS e Azure, in linea con gli standard sanitari HL7 e FHIR.' },
      { q: 'Il supporto continuo è disponibile dopo la distribuzione?',
        a: 'La manutenzione post-distribuzione include il monitoraggio continuo, la riqualificazione del modello e l\'ottimizzazione delle prestazioni per garantire l\'affidabilità duratura del sistema.' },
    ],
  },
  closing: {
    heading: 'Trasforma le operazioni sanitarie con soluzioni AI intelligenti e personalizzate',
    body: 'Collabora con i nostri esperti per sviluppare sistemi AI sicuri e scalabili che migliorano l\'erogazione delle cure e la precisione del processo decisionale.',
    cta: { label: 'Inizia oggi', href: "#consultation" },
  },
};

export const aiEducationSoftware: ServiceDetailContent = {
  slug: "ai-education-software",
  category: 'Intelligenza Artificiale · Educazione',
  hideTrustedPartners: true,
  hero: {
    eyebrow: 'AI nell\'istruzione',
    heading: 'AI nelle soluzioni didattiche',
    body:
      'Sistemi educativi intelligenti che personalizzano l\'apprendimento, automatizzano le operazioni e forniscono analisi in tempo reale per il successo accademico basato sui dati.',
    primaryCta: { label: 'Parla con un esperto', href: "#consultation" },
    ghostCta: { label: 'Vedi Funzionalità', href: "#capabilities" },
  },
  stats: [
    { value: "10+",  label: 'Anni di esperienza',   icon: "/elchai/ai-development/ai-achievement-icn_1.svg" },
    { value: "120+", label: 'AI Soluzioni consegnate', icon: "/elchai/ai-development/ai-achievement-icn_2.svg" },
    { value: "100+", label: 'AI sviluppatori',         icon: "/elchai/ai-development/ai-achievement-icn_3.svg" },
    { value: "30+",  label: 'Paesi serviti',      icon: "/elchai/ai-development/ai-achievement-icn_4.svg" },
  ],
  capabilities: {
    eyebrow: 'Servizi',
    heading: 'AI Soluzioni didattiche per sistemi di apprendimento intelligenti e adattivi',
    body:
      'Dal tutoraggio personalizzato all\'automazione amministrativa, ogni soluzione è progettata per migliorare l\'efficienza dell\'insegnamento e il coinvolgimento degli studenti.',
    items: [
      { title: 'Sviluppo di software didattico AI personalizzato', desc: 'Sviluppa piattaforme didattiche intelligenti che personalizzano i percorsi di apprendimento, automatizzano la valutazione e forniscono analisi delle prestazioni.',                 icon: "/elchai/ai-voice/Workflow_icons1.svg" },
      { title: 'Sistemi di apprendimento personalizzati',            desc: 'Utilizza algoritmi adattivi per personalizzare lezioni, ritmo e valutazioni in base alle esigenze e al livello di abilità di ogni studente.',                                     icon: "/elchai/ai-voice/Workflow_icons2.svg" },
      { title: 'AItutor virtuali potenziati',                desc: 'Utilizza assistenti conversazionali AI che rispondano a domande, spieghino concetti e forniscano supporto accademico 24 ore su 24, 7 giorni su 7.',                                icon: "/elchai/ai-voice/Workflow_icons3.svg" },
      { title: 'Analisi predittiva delle prestazioni degli studenti', desc: 'Sfrutta i modelli AI per identificare precocemente gli studenti a rischio e consigliare interventi tempestivi per migliorare i risultati.',                                  icon: "/elchai/ai-voice/Workflow_icons4.svg" },
      { title: 'Automazione del flusso di lavoro amministrativo',       desc: 'Semplifica attività come le ammissioni, il monitoraggio delle presenze e l\'allocazione delle risorse utilizzando l\'automazione dei processi basata su AI.',                            icon: "/elchai/ai-voice/Workflow_icons5.svg" },
      { title: 'Consigli sui contenuti basati su AI',         desc: 'Consigliare materiali e risorse di apprendimento in modo dinamico in base al progresso, al comportamento e alle prestazioni di valutazione dell\'utente.',                            icon: "/elchai/ai-voice/Workflow_icons6.svg" },
      { title: 'Sistemi di valutazione e supervisione degli esami',     desc: 'Garantisci l\'integrità dell\'esame tramite il monitoraggio basato su AI, il riconoscimento facciale e il rilevamento delle anomalie in tempo reale.',                                         icon: "/elchai/ai-voice/Workflow_icons7.svg" },
      { title: 'Integrazione del sistema di gestione dell\'apprendimento',   desc: 'Integra le funzionalità AI nelle piattaforme LMS per abilitare dashboard intelligenti, automazione del feedback e approfondimenti basati sui dati.',                              icon: "/elchai/ai-voice/Workflow_icons8.svg" },
      { title: 'Strumenti di orientamento e consulenza professionale',       desc: 'Offri agli studenti una mappatura delle carriere supportata da AI basata su interessi, competenze e tendenze emergenti del settore.',                                                icon: "/elchai/ai-voice/Workflow_icons9.svg" },
      { title: 'Sistemi di riconoscimento vocale e linguistico',    desc: 'Supporta l\'apprendimento e l\'accessibilità delle lingue con gli strumenti AI per la trascrizione, il feedback sulla pronuncia e il monitoraggio della comprensione.',                 icon: "/elchai/ai-voice/Workflow_icons1.svg" },
      { title: 'Cruscotti di analisi educativa',           desc: 'Consenti il ​​monitoraggio in tempo reale dei progressi degli studenti, della frequenza e delle prestazioni istituzionali attraverso report intelligenti.',                         icon: "/elchai/ai-voice/Workflow_icons2.svg" },
      { title: 'AI Consulenza strategica per l\'istruzione',     desc: 'Definisci roadmap di adozione di AI in linea con gli obiettivi accademici, l\'infrastruttura digitale e gli standard sulla privacy dei dati.',                                     icon: "/elchai/ai-voice/Workflow_icons3.svg" },
    ],
  },
  featureSections: [
    {
      position: "after-capabilities",
      layout: "image-right",
      eyebrow: 'Potenziare l\'apprendimento',
      heading: 'Potenzia l\'apprendimento, l\'amministrazione e l\'insight con i sistemi intelligenti',
      image: "/elchai/education/Insight-workflow.webp",
      body:
        'Collabora con il team educativo AI di Elchai per automatizzare i flussi di lavoro, personalizzare l\'apprendimento e aumentare il coinvolgimento degli studenti in modo efficiente.',
      cta: { label: 'Discuti il ​​tuo progetto', href: "#consultation" },
    },
    {
      position: "after-industries",
      layout: "image-left",
      eyebrow: 'Reinventare l\'apprendimento',
      heading: 'Reinventa l\'apprendimento con soluzioni AI più intelligenti e scalabili',
      image: "/elchai/education/Learning_Network.webp",
      body:
        'Collabora con AI ingegneri per creare ecosistemi di apprendimento intelligenti che promuovano coinvolgimento e miglioramenti misurabili.',
      cta: { label: 'Inizia il tuo progetto educativo', href: "#consultation" },
    },
  ],
  solutions: {
    eyebrow: 'Caratteristiche',
    heading: 'Funzionalità che potenziano esperienze di apprendimento più intelligenti e adattive',
    body:
      'Ogni funzionalità è realizzata per migliorare il coinvolgimento, semplificare i processi e rafforzare il processo decisionale tra le istituzioni.',
    displayStyle: "photo",
    items: [
      { title: 'Percorsi di apprendimento adattivi',         desc: 'Offri esperienze di apprendimento personalizzate analizzando i dati sulle prestazioni e regolando la difficoltà del corso in tempo reale.', image: "/elchai/education/adaptive-learning-paths.webp" },
      { title: 'Valutazione e valutazione automatizzate',  desc: 'Riduci il carico di lavoro dell\'istruttore valutando istantaneamente quiz, saggi e compiti tramite la PNL e algoritmi di punteggio.', image: "/elchai/education/automated-grading.webp" },
      { title: 'Analisi accademica predittiva',   desc: 'Prevedi i risultati degli studenti, identifica le tendenze e ottimizza la pianificazione delle risorse utilizzando la modellazione predittiva basata sui dati.',     image: "/elchai/education/predictive-academic-analytics.webp" },
      { title: 'Distribuzione intelligente dei contenuti',          desc: 'Distribuisci materiali di studio mirati in base alle lacune di competenze, alla padronanza della materia e alle preferenze degli studenti.',                     image: "/elchai/education/smart-content-delivery.webp" },
      { title: 'Intelligenza sulla fidelizzazione degli studenti',  desc: 'Rileva i primi segnali di disimpegno e attiva strategie di intervento per migliorare la fidelizzazione e le prestazioni.',          image: "/elchai/education/student-retention-intelligence.webp" },
      { title: 'Assistenza virtuale basata su AI',   desc: 'Fornisci supporto agli studenti in tempo reale tramite AI conversazionale integrato in piattaforme web, chat e mobili.',          image: "/elchai/education/ai-virtual-assistance.webp" },
    ],
  },
  industries: {
    eyebrow: 'Spazi di apprendimento',
    heading: 'AI Soluzioni didattiche progettate per ogni spazio di apprendimento',
    body: 'Costruito per servire istituzioni, educatori e innovatori EdTech con precisione, adattabilità e impatto misurabile sull\'apprendimento.',
    items: [
      { title: 'Scuole primarie e secondarie' },
      { title: 'College e università' },
      { title: 'Istituti professionali' },
      { title: 'Programmi di educazione speciale' },
      { title: 'Piattaforme di apprendimento online' },
      { title: 'Programmi di formazione aziendale' },
      { title: 'Piattaforme di certificazione professionale' },
      { title: 'Centri di apprendimento linguistico' },
      { title: 'Startup EdTech' },
      { title: 'Editori educativi' },
      { title: 'Analisi dell\'apprendimento basato su AI' },
      { title: 'Strumenti del curriculum adattivo' },
    ],
  },
  process: {
    eyebrow: 'Processo',
    heading: 'Processo strutturato di Elchai per lo sviluppo di soluzioni didattiche per AI',
    body: 'Un flusso di lavoro trasparente e orientato alla ricerca, progettato per allineare tecnologia, pedagogia e scalabilità per un reale impatto educativo.',
    displayStyle: "slider",
    steps: [
      { title: 'Scoperta del progetto',        desc: 'Definisci obiettivi accademici, preparazione digitale e AI obiettivi per creare una roadmap di sviluppo precisa.' },
      { title: 'Preparazione dei dati',         desc: 'Aggrega e organizza i dati di apprendimento per formare modelli educativi AI adattivi ed etici.' },
      { title: 'Progettazione e sviluppo del modello', desc: 'Costruisci AI sistemi per la personalizzazione, l\'automazione e l\'analisi su misura per i requisiti istituzionali.' },
      { title: 'Convalida e test',     desc: 'Esegui programmi pilota per valutare l\'accuratezza del modello, il coinvolgimento degli utenti e l\'efficacia didattica.' },
      { title: 'Distribuzione e integrazione', desc: 'Integra i moduli AI all\'interno delle piattaforme LMS, CRM ed EdTech per migliorare i flussi di lavoro esistenti.' },
      { title: 'Ottimizzazione continua',  desc: 'Perfeziona gli algoritmi utilizzando il feedback sulle prestazioni per garantire il miglioramento continuo e l\'accuratezza dell\'apprendimento a lungo termine.' },
    ],
  },
  techStack: {
    eyebrow: 'Pila',
    heading: 'La base tecnologica dietro le soluzioni didattiche AI di Elchai',
    body: 'Un solido mix di strumenti di analisi dell\'apprendimento, framework di machine learning e infrastruttura cloud scalabile.',
    displayStyle: "checklist-grid",
    groups: [
      { title: 'AI e apprendimento automatico', items: ["TensorFlow", "PyTorch", 'Transformers con volti abbracciati', 'Panda'] },
      { title: 'Sviluppo back-end',   items: ['Pitone', 'Giava', "Django", "Node.js"] },
      { title: 'Sviluppo frontend',  items: ["React.js", 'Angolare', 'Svolazzare', 'Reagire nativo'] },
      { title: 'Cloud e DevOps',        items: ["AWS", 'GoogleNuvola', 'Azioni GitHub', "Docker"] },
    ],
  },
  whyChoose: {
    eyebrow: 'Perché Elchai',
    heading: 'Partner AI di fiducia per i leader dell\'istruzione globale',
    body: 'Fornire potere alle istituzioni di tutto il mondo con soluzioni orientate a AI che aumentano il coinvolgimento, migliorano i risultati e si adattano facilmente.',
    items: [
      { title: 'Competenza nel settore dell\'istruzione approfondita',  desc: 'Ottima conoscenza dei modelli pedagogici, dei quadri di valutazione e dei flussi di lavoro istituzionali.',                                  icon: "/elchai/ai-voice/ai_assist_choose_icn_1.svg" },
      { title: 'Funzionalità AI e ML comprovate',      desc: 'Vasta esperienza nella fornitura di soluzioni pronte per la produzione in analisi dell\'apprendimento, PNL e sistemi di apprendimento adattivo.',            icon: "/elchai/ai-voice/ai_assist_choose_icn_2.svg" },
      { title: 'Framework di sviluppo scalabili',  desc: 'Architetture flessibili progettate per crescere con il volume degli studenti, la complessità del corso e le esigenze istituzionali.',                          icon: "/elchai/ai-voice/ai_assist_choose_icn_3.svg" },
      { title: 'Modello di partenariato collaborativo',  desc: 'Sviluppo trasparente e informato sulla ricerca che garantisce l\'allineamento con gli obiettivi accademici e parametri di prestazione misurabili.',            icon: "/elchai/ai-voice/ai_assist_choose_icn_4.svg" },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    heading: 'Domande frequenti',
    items: [
      { q: 'In che modo AI può migliorare l\'esperienza di apprendimento?',
        a: 'AI personalizza le lezioni, tiene traccia dei progressi degli studenti e fornisce feedback in tempo reale per creare un\'esperienza di apprendimento più coinvolgente e adattiva.' },
      { q: 'I sistemi educativi AI sono adatti alle istituzioni tradizionali?',
        a: 'Sì, le nostre soluzioni AI si integrano perfettamente con le piattaforme LMS esistenti e l\'infrastruttura didattica in sede.' },
      { q: 'In che modo AI aiuta insegnanti e amministratori?',
        a: 'AI automatizza la valutazione, la pianificazione, il reporting e l\'analisi, consentendo agli insegnanti di concentrarsi maggiormente sull\'insegnamento e sul coinvolgimento degli studenti.' },
      { q: 'AI può affrontare le sfide legate al rendimento degli studenti?',
        a: 'L\'analisi predittiva identifica tempestivamente le lacune di apprendimento e consiglia azioni mirate per migliorare i risultati degli studenti.' },
      { q: 'Questi sistemi sono sicuri e conformi alla privacy?',
        a: 'Sì, tutte le soluzioni sono conformi agli standard FERPA, GDPR e globali sulla protezione dei dati per garantire la sicurezza dei dati degli studenti.' },
      { q: 'Offrite supporto continuo al modello dopo la distribuzione?',
        a: 'Sì, forniamo ottimizzazione continua, riqualificazione dei dati e supporto tecnico per mantenere prestazioni e accuratezza costanti.' },
    ],
  },
  closing: {
    heading: 'Reinventa l\'apprendimento con soluzioni AI più intelligenti e scalabili',
    body: 'Collabora con Elchai per offrire AI che migliori i risultati per gli studenti, non solo i parametri di coinvolgimento.',
    cta: { label: 'Pianifica una consulenza', href: "#consultation" },
  },
};

// ─────────────────────────────────────────────────────────────────────────
// Batch 6 (AI advanced): ChatGPT · Agents · ML · LLM · Computer Vision
// ─────────────────────────────────────────────────────────────────────────

// Kept (but not registered) as a draft for future /generative-ai-development
// refresh — see the REGISTRY entry below.
