// Service-detail content registry — multi-locale.
// Public API:
//   - getServiceDetailContent(slug, locale?)
//   - listServiceDetailSlugs()
//
// English remains the source of truth; AR/IT mirror files are generated by
// `node scripts/translate-content.mjs <source> <locale> <out>`. If a slug
// is missing in a non-EN registry we fall back to the EN entry so pages
// never break during a partial translation run.

import type { ServiceDetailContent } from "../service-detail-types";

// --- English (source of truth) --------------------------------------------
import * as enBlockchain from "./blockchain";
import * as enNft from "./nft";
import * as enCrypto from "./crypto";
import * as enAi from "./ai";
import * as enAiVertical from "./ai-vertical";
import * as enMisc from "./misc";

// --- Arabic mirrors --------------------------------------------------------
import * as arBlockchain from "./blockchain.ar";
import * as arNft from "./nft.ar";
import * as arCrypto from "./crypto.ar";
import * as arAi from "./ai.ar";
import * as arAiVertical from "./ai-vertical.ar";
import * as arMisc from "./misc.ar";

// --- Italian mirrors -------------------------------------------------------
import * as itBlockchain from "./blockchain.it";
import * as itNft from "./nft.it";
import * as itCrypto from "./crypto.it";
import * as itAi from "./ai.it";
import * as itAiVertical from "./ai-vertical.it";
import * as itMisc from "./misc.it";

type AnyServices = Record<string, ServiceDetailContent | unknown>;

function buildRegistry(modules: AnyServices[]): Record<string, ServiceDetailContent> {
  const out: Record<string, ServiceDetailContent> = {};
  for (const m of modules) {
    for (const value of Object.values(m)) {
      if (value && typeof value === "object" && "slug" in (value as object)) {
        const svc = value as ServiceDetailContent;
        out[svc.slug] = svc;
      }
    }
  }
  return out;
}

const REGISTRY_EN = buildRegistry([enBlockchain, enNft, enCrypto, enAi, enAiVertical, enMisc]);
const REGISTRY_AR = buildRegistry([arBlockchain, arNft, arCrypto, arAi, arAiVertical, arMisc]);
const REGISTRY_IT = buildRegistry([itBlockchain, itNft, itCrypto, itAi, itAiVertical, itMisc]);

// Build-time sanity check — every EN slug must round-trip its key.
for (const [key, svc] of Object.entries(REGISTRY_EN)) {
  if (svc.slug !== key) {
    throw new Error(`[services] EN slug mismatch — key "${key}" but slug "${svc.slug}"`);
  }
}

export type ServiceLocale = "EN" | "AR" | "IT";

export function getServiceDetailContent(
  slug: string,
  locale: ServiceLocale = "EN",
): ServiceDetailContent | null {
  const reg =
    locale === "AR" ? REGISTRY_AR :
    locale === "IT" ? REGISTRY_IT :
    REGISTRY_EN;
  return reg[slug] ?? REGISTRY_EN[slug] ?? null;
}

export function listServiceDetailSlugs(): string[] {
  return Object.keys(REGISTRY_EN);
}
