// AUTO-GENERATED by scripts/translate-content.mjs (locale: AR)
// Source: src/lib/services/misc.ts
// DO NOT EDIT BY HAND — re-run the script to regenerate.
// Generated: 2026-05-25T08:39:03.825Z

// AUTO-GENERATED by scripts/split-registry.mjs.
// Edits to this file may be overwritten — edit the legacy file and re-run
// `node scripts/split-registry.mjs` to regenerate.

import type { ServiceDetailContent } from "../service-detail-types";

export const aboutUs: ServiceDetailContent = {
  slug: "about-us",
  category: 'شركة',
  hero: {
    eyebrow: 'معلومات عنا',
    heading: 'نحن شركاؤك التكنولوجيون الرقميون',
    subheading: 'لقد قمنا بتمكين الشركات والبلدان والصناعات.',
    body:
      'Elchai هو شريك في التحول الرقمي يعتمد على Dubai ويجمع بين البصيرة الإستراتيجية والهندسة العليا. نحن نساعد المؤسسات على تصميم وبناء أنظمة AI و blockchain التي تقود الفصل التالي.',
    primaryCta: { label: 'العمل معنا', href: "#consultation" },
    ghostCta: { label: 'تعرف على الفريق', href: "#capabilities" },
  },
  stats: [
    { value: "80+", label: 'تمكين الشركات' },
    { value: "80+", label: 'الدول المخدومة' },
    { value: "80+", label: 'المهندسين' },
    { value: "80+", label: 'AI ومشاريع Blockchain' },
  ],
  capabilities: {
    eyebrow: 'قيم',
    heading: 'ما ندافع عنه',
    items: [
      { title: 'التميز الهندسي',   desc: 'كبار المهندسين الذين قاموا بشحن أنظمة الإنتاج AI و blockchain على المستوى المؤسسي - وليسوا عموميين بملصق Web3.' },
      { title: 'الاستشراف الاستراتيجي',      desc: 'اختيارات التكنولوجيا ترتكز على الربح والخسارة. نحن نصمم الأعمال التي تريد أن تصبح عليها، وليس فقط العرض التوضيحي الذي تحتاجه.' },
      { title: 'تسليم شفاف',     desc: 'افتح خرائط الطريق والعروض التوضيحية الأسبوعية والتسليم المستند إلى المعالم. أنت تعرف دائمًا ما يتم شحنه وما هو التالي ولماذا.' },
      { title: 'شراكة طويلة الأمد',    desc: 'نحن نستثمر في النتائج، وليس في الارتباطات. تمتد العديد من العلاقات مع العملاء لسنوات عبر برامج متعددة.' },
      { title: 'الوعي التنظيمي',     desc: 'تم تصميم الامتثال والسلطة القضائية والأمان في البنية منذ اليوم الأول - ولم يتم تثبيتها في وقت التدقيق.' },
      { title: 'البصمة العالمية، Dubai الجذور', desc: 'يقع مقرها الرئيسي في Dubai وتتمتع بحضور تشغيلي في جميع أنحاء أوروبا والخليج وخارجهما. تغطية 24/7 عبر المناطق الزمنية.' },
    ],
  },
  whyChoose: {
    eyebrow: 'فريق',
    heading: 'القيادة التي يمكنك التحدث إليها',
    items: [
      { title: 'المؤسسون بعمق المجال',  desc: 'المشغلون الذين أنشأوا أعمالًا تكنولوجية وخرجوا منها عبر التمويل وسلسلة الكتل وبرامج المؤسسات.' },
      { title: 'مقعد الهندسة العليا',    desc: 'يتمتع المهندسون المعماريون والتقنيون بخبرة تزيد عن عقد من الزمن عبر أنظمة الإنتاج التي تتعامل مع الحجم الحقيقي.' },
      { title: 'القدرة عبر التخصصات', desc: 'الإستراتيجية والتصميم والهندسة والعمليات تحت سقف واحد - لا يوجد عمليات تسليم بين الشركات الاستشارية وشركاء التسليم.' },
    ],
  },
  closing: {
    heading: 'أنشئ الفصل التالي باستخدام Elchai',
    body: 'تحدث إلى قيادتنا حول برنامج AI أو blockchain أو برنامج التحول الرقمي.',
    cta: { label: 'جدولة التشاور', href: "#consultation" },
  },
};

export const mobileAppDevelopment: ServiceDetailContent = {
  slug: "mobile-app-development",
  category: 'تطوير التطبيقات',
  hideTrustedPartners: true,
  hero: {
    eyebrow: 'تطوير تطبيقات الهاتف المحمول',
    heading: 'شريك تطوير تطبيقات الهاتف المحمول النخبة للنطاق والذكاء',
    body:
      'Elchai هو فريق يعتمد على Dubai ويعمل على إنشاء تطبيقات الجوال مع التركيز بقوة على الجودة الهندسية. نحن نعمل عبر أطر عمل Android وiOS والمنصات المشتركة، ونجلب أكثر من عقد من الخبرة لكل مشروع. تعطي تصميماتنا الأولوية للبنية النظيفة والأمان والأداء طويل الأمد، مع استخدام AI بشكل مدروس حيثما يؤدي ذلك إلى تقوية المنتج.',
    primaryCta: { label: 'حدد موعدًا لاستشارتك الإستراتيجية', href: "#consultation" },
    ghostCta: { label: 'انظر القدرات', href: "#capabilities" },
    image: "/elchai/mobile-app/mobileapp-banner-img.webp",
  },
  stats: [
    { value: "5000+", label: 'التطبيقات المطورة',   icon: "/elchai/mobile-app/mad-growth-icn_1.webp" },
    { value: "750+",  label: 'مطورو التطبيقات',  icon: "/elchai/mobile-app/mad-growth-icn_1.webp" },
    { value: "35+",   label: 'الصناعات المخدومة', icon: "/elchai/mobile-app/mad-growth-icn_1.webp" },
    { value: "4.7",   label: 'تم تقييمه على القابض — معترف به للتميز في تطوير AI', icon: "/elchai/mobile-app/clutchco-1.webp" },
  ],
  caseStudies: {
    eyebrow: 'دراسات الحالة',
    heading: 'قيادة النجاح التجاري، مدعومًا بالذكاء',
    body: 'انغمس في قصص نجاحنا الواقعية وتحولات العملاء المدفوعة بهندسة الأجهزة المحمولة عالية الأداء والتكامل الاستراتيجي AI.',
    items: [
      {
        tabLabel: 'AI حلول للصحة واللياقة البدنية',
        brand: 'سمارت فيت',
        description: 'توصيات مخصصة بشأن التغذية والتمارين الرياضية، مدعومة بخوارزميات AI المتقدمة والتعلم الآلي والتحليلات التنبؤية.',
        image: "/elchai/about/smartfit-app.webp",
        stats: [
          { value: "80%",  label: 'معدل الاحتفاظ بالمستخدمين' },
          { value: "20K+", label: 'تم إنشاء خطط الوجبات' },
        ],
        cta: { label: 'تحميل دراسة الحالة', href: "#consultation" },
      },
      {
        tabLabel: 'محفظة للتكنولوجيا المالية',
        brand: 'فينتكس',
        description: 'تم تطوير محفظة تشفير آمنة متعددة السلاسل مع بروتوكولات أمان على مستوى مؤسسي وتكامل العقود الذكية.',
        image: "/elchai/about/fintex-app.webp",
        stats: [
          { value: "20%",    label: 'العملات المشفرة مدعومة' },
          { value: "$100K+", label: 'حجم المعاملات اليومية' },
        ],
        cta: { label: 'تحميل دراسة الحالة', href: "#consultation" },
      },
      {
        tabLabel: 'ميتافيرس للعقارات',
        brand: 'الكون',
        description: 'تم إنشاء تجربة metaverse غامرة باستخدام تقنية AR/VR وتكامل blockchain لسوق العقارات الرئيسي في Dubai.',
        image: "/elchai/about/theuneverse-app.webp",
        stats: [
          { value: "1000+", label: 'الخصائص الافتراضية المدرجة' },
          { value: "45%",   label: 'زيادة في مشاهدات العقارات' },
        ],
        cta: { label: 'تحميل دراسة الحالة', href: "#consultation" },
      },
      {
        tabLabel: 'إدارة علاقات العملاء (CRM) للوسائط',
        brand: 'نيلسن',
        description: 'تحويل بيانات الوسائط المعقدة إلى معلومات استخباراتية قابلة للتنفيذ، مما يتيح تحليل السوق في الوقت الفعلي ونمذجة الجمهور التنبؤي.',
        image: "/elchai/about/nielsen-app.webp",
        stats: [
          { value: "85%", label: 'وقت تحليل أسرع' },
          { value: "60%", label: 'اتخاذ القرار بشكل أسرع' },
        ],
        cta: { label: 'تحميل دراسة الحالة', href: "#consultation" },
      },
      {
        tabLabel: 'تطبيق مخصص للألعاب',
        brand: 'جرينتافي',
        description: 'منصة ألعاب فريدة من نوعها مع ميزات اجتماعية، تتيح البطولات الحية، وإحصائيات اللاعبين، ومشاركة المجتمع.',
        image: "/elchai/mobile-app/grintafy-app.webp",
        stats: [
          { value: "1M+", label: 'تنزيلات المستخدم' },
          { value: "90%", label: 'مشاركة المستخدم' },
        ],
        cta: { label: 'تحميل دراسة الحالة', href: "#consultation" },
      },
    ],
  },
  featureSections: [
    {
      position: "after-hero",
      layout: "no-image",
      eyebrow: 'موثوق به من قبل المطورين والشركات',
      heading: 'موثوق به بواسطة AI - العلامات التجارية الأولى التي ساعدنا في بنائها',
      itemsLayout: "logo-grid",
      tileTheme: "dark",
      items: [
        { title: "INGENI",      icon: "/elchai/chatgpt/ai-newbrand-logo_1.webp" },
        { title: "HealthSense", icon: "/elchai/chatgpt/ai-newbrand-logo_2.webp" },
        { title: "aihiredesk",  icon: "/elchai/chatgpt/ai-newbrand-logo_3.webp" },
        { title: "Nyra",        icon: "/elchai/chatgpt/ai-newbrand-logo_4.webp" },
        { title: "Route AI",    icon: "/elchai/chatgpt/ai-newbrand-logo_5.webp" },
        { title: 'ماكس هيلث',   icon: "/elchai/chatgpt/ai-newbrand-logo_6.webp" },
      ],
    },
    {
      position: "after-capabilities",
      layout: "image-left",
      eyebrow: 'ابدأ',
      heading: 'هل أنت جاهز لبدء مشروعك؟',
      image: "/elchai/mobile-app/mobileapp-banner-img.webp",
      body:
        'اعمل مع شركة تطوير تطبيقات الهاتف المحمول الأكثر ثقة في Dubai، حيث يمكنك تقديم أكثر من 5000 تطبيق. سنقوم بالتحقق من صحة المفهوم الخاص بك، وتخطيط البنية التقنية، وإنشاء تطبيق يدفع نمو الأعمال القابل للقياس.',
      cta: { label: 'جدولة التشاور الخاص بك', href: "#consultation" },
    },
    {
      position: "before-faq",
      layout: "no-image",
      eyebrow: 'الرؤى',
      heading: 'تمكين أصحاب الرؤى عبر جميع مستويات الأعمال باستخدام AI',
      body: 'بدءًا من الشركات الناشئة الجريئة ووصولاً إلى المؤسسات العالمية، نعمل على تمكين المبتكرين في كل مجال من مجالات البناء بشكل أكثر ذكاءً باستخدام الجيل التالي AI.',
      itemsLayout: "logo-grid",
      items: [
        { title: 'هيئة رعاية الأسرة', icon: "/elchai/elchai_partner_logo_1.webp" },
        { title: 'جرينتافي',              icon: "/elchai/elchai_partner_logo_2.webp" },
        { title: 'لوجستي',               icon: "/elchai/elchai_partner_logo_3.webp" },
        { title: "NAFFCO",                icon: "/elchai/elchai_partner_logo_4.webp" },
        { title: "ISUZU",                 icon: "/elchai/elchai_partner_logo_5.webp" },
        { title: 'زاجل',                 icon: "/elchai/elchai_partner_logo_6.webp" },
        { title: 'مرافق الإمارات',   icon: "/elchai/elchai_partner_logo_7.webp" },
        { title: "REDTAG",                icon: "/elchai/elchai_partner_logo_8.webp" },
        { title: 'دكتور حكيم كير',       icon: "/elchai/elchai_partner_logo_9.webp" },
        { title: 'دو الدفع',                icon: "/elchai/elchai_partner_logo_10.webp" },
        { title: 'شوبا العقارية',          icon: "/elchai/elchai_partner_logo_11.webp" },
        { title: 'عبد الرستماني',          icon: "/elchai/elchai_partner_logo_12.webp" },
        { title: 'INGENI الصحة',         icon: "/elchai/elchai_partner_logo_13.webp" },
        { title: "u-vault",               icon: "/elchai/elchai_partner_logo_14.webp" },
        { title: 'فيديكس',                 icon: "/elchai/elchai_partner_logo_15.webp" },
        { title: 'المعزوفات المنفردة',                 icon: "/elchai/elchai_partner_logo_16.webp" },
      ],
    },
  ],
  capabilities: {
    eyebrow: 'المنصات',
    heading: 'حلول تطوير تطبيقات الهاتف المحمول الكاملة',
    body:
      'نحن نتعامل مع دورة التطوير بأكملها — بدءًا من التحقق الأولي من صحة المفهوم وحتى التحسين بعد الإطلاق. يقوم فريقنا ببناء حلول Android وiOS وعبر الأنظمة الأساسية التي تحل مشاكل العمل الحقيقية من خلال كود الجودة والهندسة المعمارية القابلة للتطوير وتجارب المستخدم الجذابة.',
    items: [
      { title: 'تطوير الروبوت',       desc: 'أنشئ تطبيقات Android عالية الأداء لكل جهاز. تطبيقات Android الأصلية مصممة لتحقيق الأداء وقابلية التوسع. بدءًا من واجهة المستخدم المخصصة وحتى عمليات التكامل على مستوى المؤسسات، نضمن الأداء السلس واتصال واجهة برمجة التطبيقات والاختبار والصيانة. يعمل التخصيص المدعوم AI والتحليلات التنبؤية على زيادة تفاعل المستخدمين والاحتفاظ بهم.', icon: "/elchai/mobile-app/mad-platform-icn_1.webp" },
      { title: 'تطوير دائرة الرقابة الداخلية',           desc: 'تقديم تجارب سلسة عبر أجهزة Apple. نقوم بتصميم وتطوير تطبيقات iOS التي تلبي معايير Apple العالية - عبر iPhone وiPad وApple Watch وApple TV. يستخدم مطورونا أطر عمل Core ML وSwift لإنشاء تطبيقات آمنة وعالية الأداء وتضع الخصوصية في المقام الأول والتي يحبها المستخدمون.', icon: "/elchai/mobile-app/mad-platform-icn_2.webp" },
      { title: 'تطوير عبر المنصات', desc: 'قم بالإنشاء مرة واحدة، ثم قم بتشغيله في كل مكان باستخدام التطبيقات الهجينة. باستخدام أطر العمل الحديثة مثل React Native وIonic وFlutter، نقدم تطبيقات تعمل بسلاسة على كل من iOS وAndroid. استمتع بأداء مشابه للأداء الأصلي، ووقت أسرع للتسويق، وإمكانات AI المتكاملة - كل ذلك من قاعدة تعليمات برمجية واحدة.', icon: "/elchai/mobile-app/mad-platform-icn_3.webp" },
      { title: 'رد فعل المتخصصين الأصليين',  desc: 'تطوير سلس عبر الأنظمة الأساسية مع قاعدة بيانات مشتركة. يقوم مطورو React Native بإنشاء تطبيقات عالية الجودة لكل من Android وiOS. نحن نتعامل مع تحسين واجهة المستخدم/UX، وتطوير الميزات المخصصة، والدعم الفني - من خلال تكامل SDK الموحد AI عبر الأنظمة الأساسية للحصول على وظائف متسقة.', icon: "/elchai/mobile-app/mad-platform-icn_4.webp" },
    ],
  },
  industries: {
    eyebrow: 'الصناعات',
    heading: 'إحداث تغيير جذري في الصناعات من خلال حلول AI الذكية',
    body: 'نحن نقدم خبرة عميقة في هذا المجال والتميز AI إلى كل قطاع نخدمه.',
    items: [
      { title: 'الرعاية الصحية',              desc: 'AI برامج التشخيص التنبؤية · أنظمة تحليل بيانات المرضى · مساعدو الصحة الافتراضيون · حلول أتمتة سير العمل', image: "/elchai/mobile-app/mobile_app_Healthcare_industry.webp" },
      { title: 'المالية والمصرفية',     desc: 'كشف الاحتيال · تسجيل نقاط الائتمان المدعومة بنظام AI · المستشارون الآليون · أتمتة الامتثال',                                              image: "/elchai/mobile-app/mobile_app_Finance_industry.webp" },
      { title: 'البيع بالتجزئة والتجارة الإلكترونية',     desc: 'توصيات مخصصة · التسعير الديناميكي · البحث المرئي · AI روبوتات الدردشة لدعم العملاء',                                  image: "/elchai/mobile-app/mobile_app_Retail_industry.webp" },
      { title: 'تصنيع',           desc: 'الصيانة التنبؤية · مراقبة الجودة التي تعمل بالطاقة AI · التنبؤ بالطلب · أتمتة الروبوتات',                                     image: "/elchai/mobile-app/mobile_app_Manufacturing_industry.webp" },
      { title: 'السيارات',              desc: 'القيادة الذاتية · الصيانة التنبؤية · إدارة حركة المرور · أنظمة مساعدة السائق',                                       image: "/elchai/mobile-app/mobile_app_Automotive_industry.webp" },
      { title: 'الخدمات اللوجستية وسلسلة التوريد',desc: 'تحسين المسار المستند إلى AI · أتمتة المستودعات · التنبؤ بالمخزون · اكتشاف المخاطر في الوقت الفعلي',                              image: "/elchai/mobile-app/mobile_app_Logistics_industry.webp" },
      { title: 'تعليم',               desc: 'التعلم التكيفي · الدرجات الآلية · المعلم الافتراضي · التنبؤ بالأداء',                                                      image: "/elchai/mobile-app/mobile_app_Education_industry.webp" },
      { title: 'أجريتك',                desc: 'التنبؤ بإنتاجية المحاصيل · الزراعة الدقيقة · التنبؤ بحالة المناخ · الكشف عن الآفات',                                      image: "/elchai/mobile-app/mobile_app_Agritech_industry.webp" },
      { title: 'العقارات',             desc: 'AI تقييم العقارات القائم على · جولات العقارات الافتراضية · تسجيل العملاء المحتملين الذكي · الصيانة التنبؤية',                          image: "/elchai/mobile-app/mobile_app_Realestate_industry.webp" },
      { title: 'وسائل الإعلام والترفيه',   desc: 'توصية مخصصة · محتوى تم إنشاؤه بواسطة AI · تحليل المشاعر · اكتشاف Deepfake',                                       image: "/elchai/mobile-app/mobile_app_Media_industry.webp" },
      { title: 'السفر والضيافة',    desc: 'AI روبوتات الدردشة للحجز · التسعير الديناميكي · توصيات السفر · الصيانة التنبؤية',                                        image: "/elchai/mobile-app/mobile_app_Travel_industry.webp" },
      { title: 'تأمين',               desc: 'المعالجة الآلية للمطالبات · كشف الاحتيال · توصيات السياسة · روبوتات الدردشة التي تعمل بنظام AI',                                       image: "/elchai/mobile-app/mobile_app_Insurance_industry.webp" },
    ],
  },
  midBanner: {
    heading: 'تحدث إلى المطورين الذين قاموا بتوسيع نطاق أعمالهم',
    cta: { label: 'التحويل باستخدام AI', href: "#consultation" },
  },
  process: {
    eyebrow: 'مخطط',
    heading: 'مخططنا المثبت والمكون من 5 خطوات للإطلاق',
    body: 'عمليتنا تضمن النجاح. نحن نؤمن بتوفير كل شيء تحت سقف واحد، مسترشدين بمنهجية منضبطة ومبتكرة.',
    displayStyle: "slider",
    steps: [
      { title: 'المشاورة الاستراتيجية',     desc: 'نبدأ بالتحقق من صحة فكرتك الأساسية. يقوم خبراؤنا بإجراء تحليلات عميقة للسوق ودراسات الجدوى، وتحليل المتطلبات والمنافسة لتحديد نطاق المشروع الذي يضمن نتائج عالية العائد على الاستثمار.' },
      { title: 'استراتيجية المنتج',           desc: 'تحديد مخطط النجاح. نحن نقوم بمواءمة أهداف المنتج، وتحديد الجمهور المستهدف، ووضع مقاييس النجاح الرئيسية، مما يضمن أن تطبيق الهاتف المحمول الخاص بك يروي قصة نمو معقدة.' },
      { title: 'التميز في التصميم',          desc: 'بعيدًا عن الجماليات، نحن نخلق تجارب مبهجة. يقوم نهجنا في التفكير التصميمي بصياغة واجهات وتجارب مستخدم سهلة الاستخدام وبديهية، وذلك باستخدام النماذج بالحجم الطبيعي والنماذج الأولية لتعزيز المشاركة والاحتفاظ بالعملاء.' },
      { title: 'التطوير الهندسي',    desc: 'بناء النواة القوية. نحن نستخدم مجموعات التكنولوجيا المتطورة لتطوير التطبيقات المخصصة بنسبة 100%، مما يضمن حلاً قابلاً للتطوير وآمنًا وجاهزًا للمستقبل مع كود المصدر الكامل وحقوق الملكية الفكرية.' },
      { title: 'الإطلاق والتحسين',      desc: 'إطلاقك هو معيارنا. نحن نتعامل مع النشر السلس في App Store وPlay Store، يليه تحسين ما بعد الإطلاق، وترخيص البرامج، والدعم المخصص على مدار الساعة طوال أيام الأسبوع لضمان النجاح على المدى الطويل.' },
    ],
  },
  techStack: {
    eyebrow: 'كومة',
    heading: 'هل تبحث عن شريك لتطوير تطبيقات الهاتف المحمول يتوافق مع رؤية الصناعة الخاصة بك؟',
    body: 'نحن نبني منتجات رقمية ذكية تتكامل بسلاسة مع النظام البيئي لمؤسستك. يجمع فريق تطوير التطبيقات لدينا بين سياق الصناعة العميق والتفكير التصميمي والهندسة المتقدمة لمساعدة المؤسسات على إطلاق قيمة جديدة عبر مشهد الأجهزة المحمولة.',
    displayStyle: "tabs",
    groups: [
      { title: 'أطر عمل البلوكشين', items: [
        { name: "Ethereum",          logo: "/elchai/mobile-app/Ethereum_logo.webp" },
        { name: "Polygon",           logo: "/elchai/mobile-app/Polygon_logo.webp" },
        { name: "Solana",            logo: "/elchai/mobile-app/Solana_logo.webp" },
        { name: 'المنقط',          logo: "/elchai/mobile-app/Polkadot_logo.webp" },
        { name: 'كوزموس SDK',        logo: "/elchai/mobile-app/Cosmos_SDK_logo.webp" },
        { name: 'انهيار جليدي',         logo: "/elchai/mobile-app/Avalanche_logo.webp" },
        { name: 'Hyperledger القماش', logo: "/elchai/mobile-app/1Hyperledger_Fabric_logo.webp" },
      ] },
      { title: 'الذكاء الاصطناعي', items: [
        { name: "OpenAI",          logo: "/elchai/mobile-app/white_Models_APIs-icn_1.webp" },
        { name: "Fetch.ai",        logo: "/elchai/mobile-app/Fetch.ai-icon.webp" },
        { name: 'التفردNET',  logo: "/elchai/mobile-app/SingularityNET-icn.webp" },
        { name: 'بيتينسور',       logo: "/elchai/mobile-app/Bittensor-icn.webp" },
      ] },
      { title: 'لغات البرمجة', items: [
        { name: 'صلابة',   logo: "/elchai/mobile-app/ProgrammingLanguages-icn_1.webp" },
        { name: 'الصدأ',       logo: "/elchai/mobile-app/ProgrammingLanguages-icn_3.webp" },
        { name: "GO",         logo: "/elchai/mobile-app/go-icn.webp" },
        { name: 'تايب سكريبت', logo: "/elchai/mobile-app/TypeScript-icn.webp" },
        { name: 'بايثون',     logo: "/elchai/mobile-app/ProgrammingLanguages-icn_5.webp" },
      ] },
      { title: 'الأطر', items: [
        { name: 'هاردهات', logo: "/elchai/mobile-app/HardHat_icn.webp" },
        { name: 'مسبك', logo: "/elchai/mobile-app/Foundry_icn.webp" },
        { name: 'الكمأة', logo: "/elchai/mobile-app/Truffle-icn.webp" },
        { name: "Nextjs",  logo: "/elchai/mobile-app/Nextjs-icn.webp" },
        { name: "Node.js", logo: "/elchai/mobile-app/Frameworks-icn_2.webp" },
      ] },
      { title: 'محافظ', items: [
        { name: 'قناع ميتا',     logo: "/elchai/mobile-app/Wallets-icn_2.webp" },
        { name: 'قوس قزح',      logo: "/elchai/mobile-app/Rainbow-icn.webp" },
        { name: 'محفظة الثقة', logo: "/elchai/mobile-app/Wallets-icn_3.webp" },
        { name: 'فانتوم',      logo: "/elchai/mobile-app/Phantom-icn.webp" },
        { name: 'كوين بيس',     logo: "/elchai/mobile-app/Coinbase-icn.webp" },
      ] },
      { title: 'العقود الذكية', items: [
        { name: 'Ethereum الجهاز الظاهري', logo: "/elchai/mobile-app/Ethereum-Virtual-Machine-icn.webp" },
        { name: 'صلابة',                 logo: "/elchai/mobile-app/Solidity-icn.webp" },
        { name: 'فايبر',                    logo: "/elchai/mobile-app/Vyper-icn.webp" },
        { name: 'كوزمواسم',                 logo: "/elchai/mobile-app/CosmWasm-icn.webp" },
        { name: 'يتحرك',                     logo: "/elchai/mobile-app/Move-icn.webp" },
      ] },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    heading: 'تطوير تطبيقات الهاتف المحمول – الأسئلة الشائعة',
    items: [
      { q: 'Native أو React Native أو Flutter - بماذا تنصح؟',
        a: 'أصلي (SwiftUI / Kotlin) للتطبيقات ذات الأداء الحرج أو ذات ميزات نظام التشغيل الثقيلة أو التطبيقات ذات الأنظمة الأساسية الصارمة. React Native أو Flutter للسرعة عبر الأنظمة الأساسية مع تجربة مستخدم قريبة من الأصل. نحن نوصي بكل مشروع، وليس كإجراء افتراضي، ونشرح المقايضات بأمانة.' },
      { q: 'كم من الوقت يستغرق شحن تطبيق الهاتف المحمول؟',
        a: 'أفضل لاعب: 12-16 أسبوعًا. الإصدار الأول المصقول المزود بالواجهة الخلفية والمصادقة والمدفوعات والتحليلات: من 16 إلى 24 أسبوعًا. أضف 2-4 أسابيع لمراجعة App Store / Play Store وأصول التسويق وتدفقات الإعداد.' },
      { q: 'هل تتعامل مع عمليات إرسال App Store وPlay Store؟',
        a: 'نعم - بما في ذلك البيانات الوصفية، ولقطات الشاشة، وإفصاحات خصوصية التطبيق/أمان البيانات، وعمليات تصعيد المراجعة، وتحديثات ما بعد الإطلاق. لقد قمنا بالشحن عبر كلا المتجرين بموجب قيود مراجعة صارمة (التشفير، والتمويل، والطبي).' },
      { q: 'هل سيعمل تطبيقي دون اتصال بالإنترنت؟',
        a: 'نعم، إذا كانت حالة الاستخدام تتطلب ذلك. تعتبر طبقات البيانات المحلية الأولى (SQLite، وRealm، وWatermelon)، واستراتيجيات حل النزاعات، ومحركات المزامنة (مثل PowerSync، وY.js) شائعة في إصداراتنا غير المتصلة بالإنترنت.' },
      { q: 'كيف يمكنك التعامل مع الأداء على الأجهزة المنخفضة؟',
        a: 'يتم تعيين الميزانيات عند التصميم (البدء البارد < 2 ثانية، والتمرير 60 إطارًا في الثانية، والرسوم المتحركة 60 إطارًا في الثانية) ويتم فرضها عبر اختبارات أداء CI على الأجهزة الحقيقية. نحن نقوم بالاختبار على iPhone SE وAndroid منخفض المستوى، وليس فقط على الأجهزة الرئيسية.' },
      { q: 'من يملك التطبيق وكود المصدر عند الإطلاق؟',
        a: 'أنت. عمليات إعادة شراء المصدر ومفاتيح التوقيع وحسابات المتجر ونقل البنية التحتية إلى فريقك. تعد عمليات الاحتفاظ بعد الإطلاق (الصيانة، وأعمال الميزات، وASO) اختيارية ويتم تحديد نطاقها بشكل منفصل.' },
    ],
  },
  closing: {
    heading: 'هل تبحث عن شريك لتطوير تطبيقات الهاتف المحمول يتوافق مع رؤية الصناعة الخاصة بك؟',
    body: 'تحدث إلى فريق هندسة الهاتف المحمول لدى Elchai حول عملية الإطلاق التالية.',
    cta: { label: 'حدد موعدًا لاستشارتك الإستراتيجية', href: "#consultation" },
  },
};

// ─────────────────────────────────────────────────────────────────────────
// Registry
// ─────────────────────────────────────────────────────────────────────────
