// AUTO-GENERATED by scripts/translate-content.mjs (locale: IT)
// Source: src/lib/services/misc.ts
// DO NOT EDIT BY HAND — re-run the script to regenerate.
// Generated: 2026-05-25T08:39:10.005Z

// AUTO-GENERATED by scripts/split-registry.mjs.
// Edits to this file may be overwritten — edit the legacy file and re-run
// `node scripts/split-registry.mjs` to regenerate.

import type { ServiceDetailContent } from "../service-detail-types";

export const aboutUs: ServiceDetailContent = {
  slug: "about-us",
  category: 'Azienda',
  hero: {
    eyebrow: 'Chi siamo',
    heading: 'Siamo i tuoi partner tecnologici digitali',
    subheading: 'Abbiamo dato potere ad aziende, paesi e industrie.',
    body:
      'Elchai è un partner per la trasformazione digitale con sede a Dubai che combina lungimiranza strategica e ingegneria senior. Aiutiamo le organizzazioni a progettare e costruire i sistemi AI e blockchain che guideranno il loro prossimo capitolo.',
    primaryCta: { label: 'Lavora con noi', href: "#consultation" },
    ghostCta: { label: 'Incontra la squadra', href: "#capabilities" },
  },
  stats: [
    { value: "80+", label: 'Potenziamento delle imprese' },
    { value: "80+", label: 'Paesi serviti' },
    { value: "80+", label: 'Ingegneri' },
    { value: "80+", label: 'AI e progetti Blockchain' },
  ],
  capabilities: {
    eyebrow: 'Valori',
    heading: 'Ciò che rappresentiamo',
    items: [
      { title: 'Eccellenza ingegneristica',   desc: 'Ingegneri senior che hanno distribuito sistemi di produzione AI e blockchain su scala istituzionale, non generalisti con un adesivo Web3.' },
      { title: 'Previsione strategica',      desc: 'Scelte tecnologiche basate sui profitti e sulle perdite. Progettiamo per l\'azienda che stai diventando, non solo per la demo di cui hai bisogno.' },
      { title: 'Consegna trasparente',     desc: 'Roadmap aperte, demo settimanali e consegna basata su traguardi. Sai sempre cosa viene spedito, cosa c\'è dopo e perché.' },
      { title: 'Partenariato a lungo termine',    desc: 'Siamo investiti nei risultati, non negli impegni. Molte relazioni con i clienti durano anni attraverso più programmi.' },
      { title: 'Consapevolezza normativa',     desc: 'Conformità, giurisdizione e sicurezza integrate nell\'architettura fin dal primo giorno, non integrate al momento dell\'audit.' },
      { title: 'Impronta globale, Dubai radici', desc: 'Con sede centrale a Dubai e presenza operativa in tutta Europa, nel Golfo e oltre. Copertura 24 ore su 24, 7 giorni su 7, in tutti i fusi orari.' },
    ],
  },
  whyChoose: {
    eyebrow: 'Squadra',
    heading: 'Leadership con cui puoi parlare',
    items: [
      { title: 'Fondatori con profondità di dominio',  desc: 'Operatori che hanno creato ed abbandonato attività tecnologiche nel campo della finanza, della blockchain e del software aziendale.' },
      { title: 'Banco di ingegneria senior',    desc: 'Architetti e responsabili tecnologici con oltre dieci anni di esperienza nei sistemi di produzione che gestiscono volumi reali.' },
      { title: 'Capacità interdisciplinare', desc: 'Strategia, progettazione, ingegneria e operazioni sotto lo stesso tetto: nessun passaggio di consegne tra società di consulenza e partner di consegna.' },
    ],
  },
  closing: {
    heading: 'Costruisci il prossimo capitolo con Elchai',
    body: 'Parla con la nostra leadership del tuo programma AI, blockchain o trasformazione digitale.',
    cta: { label: 'Pianifica una consulenza', href: "#consultation" },
  },
};

export const mobileAppDevelopment: ServiceDetailContent = {
  slug: "mobile-app-development",
  category: 'Sviluppo di app',
  hideTrustedPartners: true,
  hero: {
    eyebrow: 'Sviluppo di app mobili',
    heading: 'Partner d\'élite per lo sviluppo di app mobili per scalabilità e intelligenza',
    body:
      'Elchai è un team con sede a Dubai che crea app mobili con una forte attenzione alla qualità tecnica. Lavoriamo su Android, iOS e framework multipiattaforma, portando oltre un decennio di esperienza in ogni progetto. Le nostre build danno priorità all\'architettura pulita, alla sicurezza e alle prestazioni a lungo termine, utilizzando AI in modo ponderato ovunque rafforzi il prodotto.',
    primaryCta: { label: 'Pianifica la tua consulenza strategica', href: "#consultation" },
    ghostCta: { label: 'Vedi Funzionalità', href: "#capabilities" },
    image: "/elchai/mobile-app/mobileapp-banner-img.webp",
  },
  stats: [
    { value: "5000+", label: 'App sviluppate',   icon: "/elchai/mobile-app/mad-growth-icn_1.webp" },
    { value: "750+",  label: 'Sviluppatori di app',  icon: "/elchai/mobile-app/mad-growth-icn_1.webp" },
    { value: "35+",   label: 'Industrie servite', icon: "/elchai/mobile-app/mad-growth-icn_1.webp" },
    { value: "4.7",   label: 'Valutato su Clutch: riconosciuto per l\'eccellenza nello sviluppo AI', icon: "/elchai/mobile-app/clutchco-1.webp" },
  ],
  caseStudies: {
    eyebrow: 'Casi di studio',
    heading: 'Promuovere il successo commerciale, alimentato dall\'intelligenza',
    body: 'Immergiti nelle nostre storie di successo reali e nelle trasformazioni dei clienti guidate dalla progettazione mobile ad alte prestazioni e dall\'integrazione strategica AI.',
    items: [
      {
        tabLabel: 'AI Soluzioni per salute e fitness',
        brand: "SmartFit",
        description: 'Consigli personalizzati su alimentazione e allenamento, supportati da algoritmi AI avanzati, apprendimento automatico e analisi predittiva.',
        image: "/elchai/about/smartfit-app.webp",
        stats: [
          { value: "80%",  label: 'Tasso di fidelizzazione degli utenti' },
          { value: "20K+", label: 'Piani pasto generati' },
        ],
        cta: { label: 'Scarica il caso di studio', href: "#consultation" },
      },
      {
        tabLabel: 'Portafoglio per Fintech',
        brand: "Fintex",
        description: 'Sviluppato un portafoglio crittografico multicatena sicuro con protocolli di sicurezza di livello istituzionale e integrazione di contratti intelligenti.',
        image: "/elchai/about/fintex-app.webp",
        stats: [
          { value: "20%",    label: 'Criptovalute supportate' },
          { value: "$100K+", label: 'Volume delle transazioni giornaliere' },
        ],
        cta: { label: 'Scarica il caso di studio', href: "#consultation" },
      },
      {
        tabLabel: 'Metaverso per il settore immobiliare',
        brand: 'L\'Universo',
        description: 'Ho creato un\'esperienza coinvolgente nel metaverso utilizzando la tecnologia AR/VR e l\'integrazione blockchain per il principale mercato immobiliare di Dubai.',
        image: "/elchai/about/theuneverse-app.webp",
        stats: [
          { value: "1000+", label: 'Proprietà virtuali elencate' },
          { value: "45%",   label: 'Aumento delle visualizzazioni delle proprietà' },
        ],
        cta: { label: 'Scarica il caso di studio', href: "#consultation" },
      },
      {
        tabLabel: 'CRM per i media',
        brand: "Nielsen",
        description: 'Trasformare dati multimediali complessi in informazioni utilizzabili, consentendo analisi di mercato in tempo reale e modellazione predittiva del pubblico.',
        image: "/elchai/about/nielsen-app.webp",
        stats: [
          { value: "85%", label: 'Tempi di analisi più rapidi' },
          { value: "60%", label: 'Processo decisionale più rapido' },
        ],
        cta: { label: 'Scarica il caso di studio', href: "#consultation" },
      },
      {
        tabLabel: 'App personalizzata per i giochi',
        brand: "Grintafy",
        description: 'Piattaforma di gioco unica con funzionalità social che consente tornei dal vivo, statistiche dei giocatori e coinvolgimento della comunità.',
        image: "/elchai/mobile-app/grintafy-app.webp",
        stats: [
          { value: "1M+", label: 'Download degli utenti' },
          { value: "90%", label: 'Coinvolgimento degli utenti' },
        ],
        cta: { label: 'Scarica il caso di studio', href: "#consultation" },
      },
    ],
  },
  featureSections: [
    {
      position: "after-hero",
      layout: "no-image",
      eyebrow: 'Scelto da sviluppatori e aziende',
      heading: 'Scelto da AI: i primi marchi che abbiamo contribuito a creare',
      itemsLayout: "logo-grid",
      tileTheme: "dark",
      items: [
        { title: "INGENI",      icon: "/elchai/chatgpt/ai-newbrand-logo_1.webp" },
        { title: "HealthSense", icon: "/elchai/chatgpt/ai-newbrand-logo_2.webp" },
        { title: "aihiredesk",  icon: "/elchai/chatgpt/ai-newbrand-logo_3.webp" },
        { title: "Nyra",        icon: "/elchai/chatgpt/ai-newbrand-logo_4.webp" },
        { title: "Route AI",    icon: "/elchai/chatgpt/ai-newbrand-logo_5.webp" },
        { title: 'Maxsalute',   icon: "/elchai/chatgpt/ai-newbrand-logo_6.webp" },
      ],
    },
    {
      position: "after-capabilities",
      layout: "image-left",
      eyebrow: 'Inizia',
      heading: 'Pronto per iniziare il tuo progetto?',
      image: "/elchai/mobile-app/mobileapp-banner-img.webp",
      body:
        'Collabora con l\'azienda di sviluppo di app per dispositivi mobili più affidabile in Dubai, offrendo oltre 5.000 app. Convalideremo il tuo concetto, pianificheremo l\'architettura tecnica e creeremo un\'app che favorirà una crescita aziendale misurabile.',
      cta: { label: 'Pianifica la tua consulenza', href: "#consultation" },
    },
    {
      position: "before-faq",
      layout: "no-image",
      eyebrow: 'Visionari',
      heading: 'Dare potere ai visionari su tutte le scale aziendali con AI',
      body: 'Dalle startup audaci alle imprese globali, consentiamo agli innovatori di ogni settore di costruire in modo più intelligente con AI di nuova generazione.',
      itemsLayout: "logo-grid",
      items: [
        { title: 'Autorità per l\'assistenza familiare', icon: "/elchai/elchai_partner_logo_1.webp" },
        { title: "Grintafy",              icon: "/elchai/elchai_partner_logo_2.webp" },
        { title: 'Logistica',               icon: "/elchai/elchai_partner_logo_3.webp" },
        { title: "NAFFCO",                icon: "/elchai/elchai_partner_logo_4.webp" },
        { title: "ISUZU",                 icon: "/elchai/elchai_partner_logo_5.webp" },
        { title: "Zajel",                 icon: "/elchai/elchai_partner_logo_6.webp" },
        { title: 'Strutture degli Emirati',   icon: "/elchai/elchai_partner_logo_7.webp" },
        { title: "REDTAG",                icon: "/elchai/elchai_partner_logo_8.webp" },
        { title: 'Cura del dottor Hakeem',       icon: "/elchai/elchai_partner_logo_9.webp" },
        { title: "du Pay",                icon: "/elchai/elchai_partner_logo_10.webp" },
        { title: 'SOBHA Immobiliare',          icon: "/elchai/elchai_partner_logo_11.webp" },
        { title: "AW ROSTAMANI",          icon: "/elchai/elchai_partner_logo_12.webp" },
        { title: 'INGENI Salute',         icon: "/elchai/elchai_partner_logo_13.webp" },
        { title: "u-vault",               icon: "/elchai/elchai_partner_logo_14.webp" },
        { title: 'Fedex',                 icon: "/elchai/elchai_partner_logo_15.webp" },
        { title: 'assoli',                 icon: "/elchai/elchai_partner_logo_16.webp" },
      ],
    },
  ],
  capabilities: {
    eyebrow: 'Piattaforme',
    heading: 'Soluzioni complete per lo sviluppo di app mobili',
    body:
      'Gestiamo l\'intero ciclo di sviluppo, dalla convalida del concetto iniziale all\'ottimizzazione post-lancio. Il nostro team crea soluzioni Android, iOS e multipiattaforma che risolvono problemi aziendali reali con codice di qualità, architettura scalabile ed esperienze utente coinvolgenti.',
    items: [
      { title: 'Sviluppo Android',       desc: 'Crea app Android ad alte prestazioni per ogni dispositivo. App Android native create per prestazioni e scalabilità. Dall\'interfaccia utente personalizzata alle integrazioni di livello aziendale, garantiamo funzionalità fluide, connettività API, test e manutenzione. La personalizzazione basata su AI e l\'analisi predittiva favoriscono il coinvolgimento e la fidelizzazione degli utenti.', icon: "/elchai/mobile-app/mad-platform-icn_1.webp" },
      { title: 'Sviluppo iOS',           desc: 'Offri esperienze fluide su tutti i dispositivi Apple. Progettiamo e sviluppiamo app iOS che soddisfano gli elevati standard di Apple: su iPhone, iPad, Apple Watch e Apple TV. I nostri sviluppatori utilizzano i framework Core ML e Swift per creare applicazioni sicure, ad alte prestazioni e incentrate sulla privacy, apprezzate dagli utenti.', icon: "/elchai/mobile-app/mad-platform-icn_2.webp" },
      { title: 'Sviluppo multipiattaforma', desc: 'Crea una volta, avvia ovunque con le app ibride. Utilizzando framework moderni come React Native, Ionic e Flutter, forniamo app che funzionano perfettamente sia su iOS che su Android. Goditi prestazioni di tipo nativo, time-to-market più rapido e funzionalità AI integrate, il tutto da un\'unica base di codice.', icon: "/elchai/mobile-app/mad-platform-icn_3.webp" },
      { title: 'Reagisci agli specialisti nativi',  desc: 'Sviluppo multipiattaforma senza soluzione di continuità con codebase condiviso. I nostri sviluppatori React Native creano app di alta qualità sia per Android che per iOS. Ci occupiamo dell\'ottimizzazione dell\'interfaccia utente/UX, dello sviluppo di funzionalità personalizzate e del supporto tecnico, con l\'integrazione unificata dell\'SDK AI su tutte le piattaforme per garantire funzionalità coerenti.', icon: "/elchai/mobile-app/mad-platform-icn_4.webp" },
    ],
  },
  industries: {
    eyebrow: 'Industrie',
    heading: 'Rivoluzionare le industrie attraverso soluzioni AI intelligenti',
    body: 'Portiamo una profonda esperienza nel settore e l\'eccellenza AI in ogni settore che serviamo.',
    items: [
      { title: 'Assistenza sanitaria',              desc: 'AI Software di diagnostica predittiva · Sistemi di analisi dei dati dei pazienti · Assistenti sanitari virtuali · Soluzioni di automazione del flusso di lavoro', image: "/elchai/mobile-app/mobile_app_Healthcare_industry.webp" },
      { title: 'Finanza e banche',     desc: 'Rilevamento delle frodi · Credit scoring basato su AI · Robo-advisor · Automazione della conformità',                                              image: "/elchai/mobile-app/mobile_app_Finance_industry.webp" },
      { title: 'Vendita al dettaglio ed e-commerce',     desc: 'Consigli personalizzati · Prezzi dinamici · Ricerca visiva · AI chatbot per l\'assistenza clienti',                                  image: "/elchai/mobile-app/mobile_app_Retail_industry.webp" },
      { title: 'Produzione',           desc: 'Manutenzione predittiva · Controllo qualità basato su AI · Previsione della domanda · Automazione robotica',                                     image: "/elchai/mobile-app/mobile_app_Manufacturing_industry.webp" },
      { title: 'Automobilistico',              desc: 'Guida autonoma · Manutenzione predittiva · Gestione del traffico · Sistemi di assistenza alla guida',                                       image: "/elchai/mobile-app/mobile_app_Automotive_industry.webp" },
      { title: 'Logistica e catena di fornitura',desc: 'Ottimizzazione del percorso basata su AI · Automazione del magazzino · Previsione dell\'inventario · Rilevamento dei rischi in tempo reale',                              image: "/elchai/mobile-app/mobile_app_Logistics_industry.webp" },
      { title: 'Istruzione',               desc: 'Apprendimento adattivo · Valutazione automatizzata · Tutor virtuale · Previsione delle prestazioni',                                                      image: "/elchai/mobile-app/mobile_app_Education_industry.webp" },
      { title: "Agritech",                desc: 'Previsione della resa delle colture · Agricoltura di precisione · Previsione delle condizioni climatiche · Rilevamento dei parassiti',                                      image: "/elchai/mobile-app/mobile_app_Agritech_industry.webp" },
      { title: 'Immobiliare',             desc: 'Valutazione immobiliare basata su AI · Tour virtuali della proprietà · Lead scoring intelligente · Manutenzione predittiva',                          image: "/elchai/mobile-app/mobile_app_Realestate_industry.webp" },
      { title: 'Media e intrattenimento',   desc: 'Consigli personalizzati · Contenuti generati da AI · Analisi del sentiment · Rilevamento deepfake',                                       image: "/elchai/mobile-app/mobile_app_Media_industry.webp" },
      { title: 'Viaggi e ospitalità',    desc: 'AI chatbot per la prenotazione · Prezzi dinamici · Consigli di viaggio · Manutenzione predittiva',                                        image: "/elchai/mobile-app/mobile_app_Travel_industry.webp" },
      { title: 'Assicurazione',               desc: 'Elaborazione automatizzata dei reclami · Rilevamento delle frodi · Raccomandazioni sulle norme · Chatbot basati su AI',                                       image: "/elchai/mobile-app/mobile_app_Insurance_industry.webp" },
    ],
  },
  midBanner: {
    heading: 'Parla con gli sviluppatori che hanno ampliato le aziende',
    cta: { label: 'Trasforma con AI', href: "#consultation" },
  },
  process: {
    eyebrow: 'Progetto',
    heading: 'Il nostro comprovato progetto in 5 passaggi per il lancio',
    body: 'Il nostro processo garantisce il successo. Crediamo nel fornire tutto sotto lo stesso tetto, guidati da una metodologia disciplinata e innovativa.',
    displayStyle: "slider",
    steps: [
      { title: 'Consultazione strategica',     desc: 'Iniziamo convalidando la tua idea principale. I nostri esperti eseguono analisi approfondite di mercato e studi di fattibilità, analizzando i requisiti e la concorrenza per definire un ambito di progetto che garantisca un risultato con un ROI elevato.' },
      { title: 'Strategia di prodotto',           desc: 'Definire il progetto per il successo. Allineiamo gli obiettivi del prodotto, identifichiamo il pubblico target e stabiliamo parametri chiave di successo, garantendo che la tua applicazione mobile racconti un\'intricata storia di crescita.' },
      { title: 'Eccellenza progettuale',          desc: 'Al di là dell\'estetica, creiamo esperienze deliziose. Il nostro approccio progettuale crea interfacce ed esperienze utente semplici e intuitive, utilizzando modelli e prototipi per favorire il coinvolgimento e la fidelizzazione dei clienti.' },
      { title: 'Sviluppo ingegneristico',    desc: 'Costruire il nucleo robusto. Utilizziamo stack tecnologici all\'avanguardia per lo sviluppo di app personalizzate al 100%, garantendo una soluzione scalabile, sicura e pronta per il futuro con codice sorgente completo e diritti di proprietà intellettuale.' },
      { title: 'Lancio e ottimizzazione',      desc: 'Il tuo lancio è il nostro punto di riferimento. Gestiamo l\'implementazione senza soluzione di continuità su App Store e Play Store, seguita dall\'ottimizzazione post-lancio, dalla concessione di licenze software e dal supporto dedicato 24 ore su 24, 7 giorni su 7 per garantire il successo a lungo termine.' },
    ],
  },
  techStack: {
    eyebrow: 'Pila',
    heading: 'Cerchi un partner per lo sviluppo di app mobili in linea con la tua visione del settore?',
    body: 'Realizziamo prodotti digitali intelligenti che si integrano perfettamente con il tuo ecosistema aziendale. Il nostro team di sviluppo di app combina un profondo contesto di settore, design thinking e ingegneria avanzata per aiutare le organizzazioni a sbloccare nuovo valore nel panorama mobile.',
    displayStyle: "tabs",
    groups: [
      { title: 'Framework Blockchain', items: [
        { name: "Ethereum",          logo: "/elchai/mobile-app/Ethereum_logo.webp" },
        { name: "Polygon",           logo: "/elchai/mobile-app/Polygon_logo.webp" },
        { name: "Solana",            logo: "/elchai/mobile-app/Solana_logo.webp" },
        { name: 'A pois',          logo: "/elchai/mobile-app/Polkadot_logo.webp" },
        { name: 'SDK Cosmos',        logo: "/elchai/mobile-app/Cosmos_SDK_logo.webp" },
        { name: 'Valanga',         logo: "/elchai/mobile-app/Avalanche_logo.webp" },
        { name: 'Hyperledger Tessuto', logo: "/elchai/mobile-app/1Hyperledger_Fabric_logo.webp" },
      ] },
      { title: 'Intelligenza artificiale', items: [
        { name: "OpenAI",          logo: "/elchai/mobile-app/white_Models_APIs-icn_1.webp" },
        { name: 'Recupera.ai',        logo: "/elchai/mobile-app/Fetch.ai-icon.webp" },
        { name: "SingularityNET",  logo: "/elchai/mobile-app/SingularityNET-icn.webp" },
        { name: 'Morso',       logo: "/elchai/mobile-app/Bittensor-icn.webp" },
      ] },
      { title: 'Linguaggi di programmazione', items: [
        { name: 'Solidità',   logo: "/elchai/mobile-app/ProgrammingLanguages-icn_1.webp" },
        { name: 'Ruggine',       logo: "/elchai/mobile-app/ProgrammingLanguages-icn_3.webp" },
        { name: "GO",         logo: "/elchai/mobile-app/go-icn.webp" },
        { name: 'Dattiloscritto', logo: "/elchai/mobile-app/TypeScript-icn.webp" },
        { name: 'Pitone',     logo: "/elchai/mobile-app/ProgrammingLanguages-icn_5.webp" },
      ] },
      { title: 'Quadri', items: [
        { name: 'Elmetto protettivo', logo: "/elchai/mobile-app/HardHat_icn.webp" },
        { name: 'Fonderia', logo: "/elchai/mobile-app/Foundry_icn.webp" },
        { name: 'Tartufo', logo: "/elchai/mobile-app/Truffle-icn.webp" },
        { name: "Nextjs",  logo: "/elchai/mobile-app/Nextjs-icn.webp" },
        { name: "Node.js", logo: "/elchai/mobile-app/Frameworks-icn_2.webp" },
      ] },
      { title: 'Portafogli', items: [
        { name: 'Metamaschera',     logo: "/elchai/mobile-app/Wallets-icn_2.webp" },
        { name: 'Arcobaleno',      logo: "/elchai/mobile-app/Rainbow-icn.webp" },
        { name: 'Portafoglio di fiducia', logo: "/elchai/mobile-app/Wallets-icn_3.webp" },
        { name: 'Fantasma',      logo: "/elchai/mobile-app/Phantom-icn.webp" },
        { name: "Coinbase",     logo: "/elchai/mobile-app/Coinbase-icn.webp" },
      ] },
      { title: 'Contratti intelligenti', items: [
        { name: 'Ethereum macchina virtuale', logo: "/elchai/mobile-app/Ethereum-Virtual-Machine-icn.webp" },
        { name: 'Solidità',                 logo: "/elchai/mobile-app/Solidity-icn.webp" },
        { name: "Vyper",                    logo: "/elchai/mobile-app/Vyper-icn.webp" },
        { name: "CosmWasm",                 logo: "/elchai/mobile-app/CosmWasm-icn.webp" },
        { name: 'Mossa',                     logo: "/elchai/mobile-app/Move-icn.webp" },
      ] },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    heading: 'Sviluppo di app mobili: domande comuni',
    items: [
      { q: 'Native, React Native o Flutter: cosa consigliate?',
        a: 'Nativo (SwiftUI/Kotlin) per app critiche in termini di prestazioni, con numerose funzionalità del sistema operativo o con piattaforma rigorosa. React Native o Flutter per velocità multipiattaforma con UX quasi nativa. Consigliamo per progetto, non come impostazione predefinita, e spieghiamo onestamente i compromessi.' },
      { q: 'Quanto tempo ci vuole per spedire un\'app mobile?',
        a: 'Un MVP: 12-16 settimane. Una versione v1 raffinata con backend, autenticazione, pagamenti e analisi: 16–24 settimane. Aggiungi 2-4 settimane per la revisione dell\'App Store/Play Store, le risorse di marketing e i flussi di onboarding.' },
      { q: 'Gestisci gli invii all\'App Store e al Play Store?',
        a: 'Sì, inclusi metadati, screenshot, informative sulla privacy delle app/sicurezza dei dati, escalation delle revisioni e aggiornamenti post-lancio. Abbiamo spedito attraverso entrambi i negozi sotto rigorosi vincoli di revisione (criptovaluta, finanza, medicina).' },
      { q: 'La mia app funzionerà offline?',
        a: 'Sì, se il caso d\'uso lo richiede. I livelli di dati locali (SQLite, Realm, Watermelon), le strategie di risoluzione dei conflitti e i motori di sincronizzazione (ad esempio PowerSync, Y.js) sono comuni nelle nostre build offline.' },
      { q: 'Come gestisci le prestazioni sui dispositivi di fascia bassa?',
        a: 'Budget impostati in fase di progettazione (avvio a freddo < 2 s, scorrimento 60 fps, animazione 60 fps) e applicati tramite controlli delle prestazioni CI su dispositivi reali. Testiamo su iPhone SE e Android di basso livello, non solo su hardware di punta.' },
      { q: 'Chi possiede l\'app e il codice sorgente al momento del lancio?',
        a: 'Voi. Repository di origine, chiavi di firma, account del negozio e trasferimento dell\'infrastruttura al tuo team. Gli interventi di conservazione post-lancio (manutenzione, lavoro sulle funzionalità, ASO) sono facoltativi e hanno un ambito separato.' },
    ],
  },
  closing: {
    heading: 'Cerchi un partner per lo sviluppo di app mobili in linea con la tua visione del settore?',
    body: 'Parla con il team tecnico mobile di Elchai del tuo prossimo lancio.',
    cta: { label: 'Pianifica la tua consulenza strategica', href: "#consultation" },
  },
};

// ─────────────────────────────────────────────────────────────────────────
// Registry
// ─────────────────────────────────────────────────────────────────────────
