// AUTO-GENERATED by scripts/split-registry.mjs.
// Source of truth: src/lib/_legacy/service-detail-content.legacy.ts.
// Edits to this file may be overwritten — edit the legacy file and re-run
// `node scripts/split-registry.mjs` to regenerate.

import type { ServiceDetailContent } from "../service-detail-types";

export const aboutUs: ServiceDetailContent = {
  slug: "about-us",
  category: "Company",
  hero: {
    eyebrow: "About Us",
    heading: "We're Your Digital Technological Partners",
    subheading: "We've Empowered Businesses, Countries, and Industries.",
    body:
      "Elchai is a Dubai-based digital transformation partner combining strategic foresight with senior engineering. We help organisations design and build the AI and blockchain systems that drive their next chapter.",
    primaryCta: { label: "Work With Us", href: "#consultation" },
    ghostCta: { label: "Meet The Team", href: "#capabilities" },
  },
  stats: [
    { value: "80+", label: "Businesses Empowered" },
    { value: "80+", label: "Countries Served" },
    { value: "80+", label: "Engineers" },
    { value: "80+", label: "AI & Blockchain Projects" },
  ],
  capabilities: {
    eyebrow: "Values",
    heading: "What We Stand For",
    items: [
      { title: "Engineering Excellence",   desc: "Senior engineers who have shipped production AI and blockchain systems at institutional scale — not generalists with a Web3 sticker." },
      { title: "Strategic Foresight",      desc: "Technology choices grounded in your P&L. We architect for the business you're becoming, not just the demo you need." },
      { title: "Transparent Delivery",     desc: "Open roadmaps, weekly demos, and milestone-based delivery. You always know what's shipped, what's next, and why." },
      { title: "Long-Term Partnership",    desc: "We're invested in outcomes, not engagements. Many client relationships span years across multiple programmes." },
      { title: "Regulatory Awareness",     desc: "Compliance, jurisdiction, and security designed into the architecture from day one — not bolted on at audit time." },
      { title: "Global Footprint, Dubai Roots", desc: "Headquartered in Dubai with operating presence across Europe, the Gulf, and beyond. 24/7 coverage across time zones." },
    ],
  },
  whyChoose: {
    eyebrow: "Team",
    heading: "Leadership You Can Talk To",
    items: [
      { title: "Founders With Domain Depth",  desc: "Operators who have built and exited technology businesses across finance, blockchain, and enterprise software." },
      { title: "Senior Engineering Bench",    desc: "Architects and tech leads with decade-plus experience across production systems handling real volume." },
      { title: "Cross-Disciplinary Capacity", desc: "Strategy, design, engineering, and operations under one roof — no handoffs between consultancies and delivery partners." },
    ],
  },
  closing: {
    heading: "Build the Next Chapter With Elchai",
    body: "Talk to our leadership about your AI, blockchain, or digital transformation programme.",
    cta: { label: "Schedule a Consultation", href: "#consultation" },
  },
};

export const mobileAppDevelopment: ServiceDetailContent = {
  slug: "mobile-app-development",
  category: "App Development",
  hideTrustedPartners: true,
  hero: {
    eyebrow: "Mobile App Development",
    heading: "Elite Mobile App Development Partner for Scale and Intelligence",
    body:
      "Elchai is a Dubai-based team that builds mobile apps with a strong focus on engineering quality. We work across Android, iOS, and cross-platform frameworks, bringing over a decade of experience to each project. Our builds prioritise clean architecture, security, and long-term performance, with AI used thoughtfully wherever it strengthens the product.",
    primaryCta: { label: "Schedule Your Strategic Consultation", href: "#consultation" },
    ghostCta: { label: "See Capabilities", href: "#capabilities" },
    image: "/elchai/mobile-app/mobileapp-banner-img.webp",
  },
  stats: [
    { value: "5000+", label: "Apps Developed",   icon: "/elchai/mobile-app/mad-growth-icn_1.webp" },
    { value: "750+",  label: "Apps Developers",  icon: "/elchai/mobile-app/mad-growth-icn_1.webp" },
    { value: "35+",   label: "Industries Served", icon: "/elchai/mobile-app/mad-growth-icn_1.webp" },
    { value: "4.7",   label: "Rated on Clutch — Recognized for Excellence in AI Development", icon: "/elchai/mobile-app/clutchco-1.webp" },
  ],
  caseStudies: {
    eyebrow: "Case Studies",
    heading: "Driving Commercial Success, Powered by Intelligence",
    body: "Dive into our real-world success stories and client transformations driven by high-performance mobile engineering and strategic AI integration.",
    items: [
      {
        tabLabel: "AI Solutions for Health & Fitness",
        brand: "SmartFit",
        description: "Personalized nutrition and workout recommendations, backed by advanced AI algorithms, machine learning, and predictive analytics.",
        image: "/elchai/about/smartfit-app.webp",
        stats: [
          { value: "80%",  label: "User Retention Rate" },
          { value: "20K+", label: "Meal Plans Generated" },
        ],
        cta: { label: "Download Case Study", href: "#consultation" },
      },
      {
        tabLabel: "Wallet for Fintech",
        brand: "Fintex",
        description: "Developed a secure multi-chain crypto wallet with institutional-grade security protocols and smart contract integration.",
        image: "/elchai/about/fintex-app.webp",
        stats: [
          { value: "20%",    label: "Cryptocurrencies Supported" },
          { value: "$100K+", label: "Daily Transaction Volume" },
        ],
        cta: { label: "Download Case Study", href: "#consultation" },
      },
      {
        tabLabel: "Metaverse for Real Estate",
        brand: "Theuneverse",
        description: "Created an immersive metaverse experience using AR/VR technology and blockchain integration for Dubai's premier real estate market.",
        image: "/elchai/about/theuneverse-app.webp",
        stats: [
          { value: "1000+", label: "Virtual Properties Listed" },
          { value: "45%",   label: "Increase in Property Views" },
        ],
        cta: { label: "Download Case Study", href: "#consultation" },
      },
      {
        tabLabel: "CRM for Media",
        brand: "Nielsen",
        description: "Transforming complex media data into actionable intelligence, enabling real-time market analysis and predictive audience modeling.",
        image: "/elchai/about/nielsen-app.webp",
        stats: [
          { value: "85%", label: "Faster Analysis Time" },
          { value: "60%", label: "Faster Decision Making" },
        ],
        cta: { label: "Download Case Study", href: "#consultation" },
      },
      {
        tabLabel: "Custom App for Gaming",
        brand: "Grintafy",
        description: "Unique gaming platform with social features, enabling live tournaments, player statistics, and community engagement.",
        image: "/elchai/mobile-app/grintafy-app.webp",
        stats: [
          { value: "1M+", label: "User Downloads" },
          { value: "90%", label: "User Engagement" },
        ],
        cta: { label: "Download Case Study", href: "#consultation" },
      },
    ],
  },
  featureSections: [
    {
      position: "after-hero",
      layout: "no-image",
      eyebrow: "Trusted by developers and businesses",
      heading: "Trusted by AI-First Brands We've Helped Build",
      itemsLayout: "logo-grid",
      tileTheme: "dark",
      items: [
        { title: "INGENI",      icon: "/elchai/chatgpt/ai-newbrand-logo_1.webp" },
        { title: "HealthSense", icon: "/elchai/chatgpt/ai-newbrand-logo_2.webp" },
        { title: "aihiredesk",  icon: "/elchai/chatgpt/ai-newbrand-logo_3.webp" },
        { title: "Nyra",        icon: "/elchai/chatgpt/ai-newbrand-logo_4.webp" },
        { title: "Route AI",    icon: "/elchai/chatgpt/ai-newbrand-logo_5.webp" },
        { title: "Maxhealth",   icon: "/elchai/chatgpt/ai-newbrand-logo_6.webp" },
      ],
    },
    {
      position: "after-capabilities",
      layout: "image-left",
      eyebrow: "Get Started",
      heading: "Ready To Start Your Project?",
      image: "/elchai/mobile-app/mobileapp-banner-img.webp",
      body:
        "Work with the most trusted mobile app development company in Dubai, delivering over 5,000+ apps. We'll validate your concept, plan technical architecture, and build an app that drives measurable business growth.",
      cta: { label: "Schedule Your Consultation", href: "#consultation" },
    },
    {
      position: "before-faq",
      layout: "no-image",
      eyebrow: "Visionaries",
      heading: "Empowering Visionaries Across All Business Scales With AI",
      body: "From bold startups to global enterprises, we empower innovators in every industry to build smarter with next-gen AI.",
      itemsLayout: "logo-grid",
      items: [
        { title: "Family Care Authority", icon: "/elchai/elchai_partner_logo_1.webp" },
        { title: "Grintafy",              icon: "/elchai/elchai_partner_logo_2.webp" },
        { title: "Logisty",               icon: "/elchai/elchai_partner_logo_3.webp" },
        { title: "NAFFCO",                icon: "/elchai/elchai_partner_logo_4.webp" },
        { title: "ISUZU",                 icon: "/elchai/elchai_partner_logo_5.webp" },
        { title: "Zajel",                 icon: "/elchai/elchai_partner_logo_6.webp" },
        { title: "Emirates Facilities",   icon: "/elchai/elchai_partner_logo_7.webp" },
        { title: "REDTAG",                icon: "/elchai/elchai_partner_logo_8.webp" },
        { title: "Dr. Hakeem Care",       icon: "/elchai/elchai_partner_logo_9.webp" },
        { title: "du Pay",                icon: "/elchai/elchai_partner_logo_10.webp" },
        { title: "SOBHA Realty",          icon: "/elchai/elchai_partner_logo_11.webp" },
        { title: "AW ROSTAMANI",          icon: "/elchai/elchai_partner_logo_12.webp" },
        { title: "INGENI Health",         icon: "/elchai/elchai_partner_logo_13.webp" },
        { title: "u-vault",               icon: "/elchai/elchai_partner_logo_14.webp" },
        { title: "FedEx",                 icon: "/elchai/elchai_partner_logo_15.webp" },
        { title: "solos",                 icon: "/elchai/elchai_partner_logo_16.webp" },
      ],
    },
  ],
  capabilities: {
    eyebrow: "Platforms",
    heading: "Complete Mobile App Development Solutions",
    body:
      "We handle the entire development cycle — from initial concept validation to post-launch optimization. Our team builds Android, iOS, and cross-platform solutions that solve real business problems with quality code, scalable architecture, and engaging user experiences.",
    items: [
      { title: "Android Development",       desc: "Build High-Performance Android Apps for Every Device. Native Android apps built for performance and scalability. From custom UI to enterprise-grade integrations, we ensure seamless functionality, API connectivity, testing, and maintenance. AI-powered personalization and predictive analytics drive user engagement and retention.", icon: "/elchai/mobile-app/mad-platform-icn_1.webp" },
      { title: "iOS Development",           desc: "Deliver Seamless Experiences Across Apple Devices. We design and develop iOS apps that meet Apple's high standards — across iPhone, iPad, Apple Watch, and Apple TV. Our developers use Core ML and Swift frameworks to build secure, high-performing, and privacy-first applications users love.", icon: "/elchai/mobile-app/mad-platform-icn_2.webp" },
      { title: "Cross-Platform Development", desc: "Build Once, Launch Everywhere with Hybrid Apps. Using modern frameworks like React Native, Ionic, and Flutter, we deliver apps that run seamlessly on both iOS and Android. Enjoy native-like performance, faster time to market, and integrated AI capabilities — all from a single codebase.", icon: "/elchai/mobile-app/mad-platform-icn_3.webp" },
      { title: "React Native Specialists",  desc: "Seamless Cross-Platform Development with Shared Codebase. Our React Native developers build high-quality apps for both Android and iOS. We handle UI/UX optimization, custom feature development, and technical support — with unified AI SDK integration across platforms for consistent functionality.", icon: "/elchai/mobile-app/mad-platform-icn_4.webp" },
    ],
  },
  industries: {
    eyebrow: "Industries",
    heading: "Disrupting Industries Through Intelligent AI Solutions",
    body: "We bring deep domain expertise and AI excellence to every sector we serve.",
    items: [
      { title: "Healthcare",              desc: "AI Predictive diagnostic Software · Patient Data Analysis Systems · Virtual health assistants · Workflow Automation Solutions", image: "/elchai/mobile-app/mobile_app_Healthcare_industry.webp" },
      { title: "Finance and Banking",     desc: "Fraud detection · AI-powered Credit scoring · Robo-advisors · Compliance automation",                                              image: "/elchai/mobile-app/mobile_app_Finance_industry.webp" },
      { title: "Retail & E-commerce",     desc: "Personalized recommendations · Dynamic pricing · Visual search · AI chatbots for customer support",                                  image: "/elchai/mobile-app/mobile_app_Retail_industry.webp" },
      { title: "Manufacturing",           desc: "Predictive maintenance · AI-powered quality control · Demand forecasting · Robotics automation",                                     image: "/elchai/mobile-app/mobile_app_Manufacturing_industry.webp" },
      { title: "Automotive",              desc: "Autonomous driving · Predictive maintenance · Traffic management · Driver assistance systems",                                       image: "/elchai/mobile-app/mobile_app_Automotive_industry.webp" },
      { title: "Logistics & Supply Chain",desc: "AI-based route optimization · Warehouse automation · Inventory forecasting · Real-time risk detection",                              image: "/elchai/mobile-app/mobile_app_Logistics_industry.webp" },
      { title: "Education",               desc: "Adaptive learning · Automated grading · Virtual tutor · Performance prediction",                                                      image: "/elchai/mobile-app/mobile_app_Education_industry.webp" },
      { title: "Agritech",                desc: "Crop yield prediction · Precision agriculture · Climate condition forecasting · Pest detection",                                      image: "/elchai/mobile-app/mobile_app_Agritech_industry.webp" },
      { title: "Real Estate",             desc: "AI-driven property valuation · Virtual property tours · Intelligent lead scoring · Predictive maintenance",                          image: "/elchai/mobile-app/mobile_app_Realestate_industry.webp" },
      { title: "Media & Entertainment",   desc: "Personalized recommendation · AI-generated content · Sentiment analysis · Deepfake detection",                                       image: "/elchai/mobile-app/mobile_app_Media_industry.webp" },
      { title: "Travel & Hospitality",    desc: "AI chatbots for booking · Dynamic pricing · Travel recommendations · Predictive maintenance",                                        image: "/elchai/mobile-app/mobile_app_Travel_industry.webp" },
      { title: "Insurance",               desc: "Automated claims processing · Fraud detection · Policy recommendations · AI-powered chatbots",                                       image: "/elchai/mobile-app/mobile_app_Insurance_industry.webp" },
    ],
  },
  midBanner: {
    heading: "Talk to Developers Who've Scaled Businesses",
    cta: { label: "Transform With AI", href: "#consultation" },
  },
  process: {
    eyebrow: "Blueprint",
    heading: "Our Proven 5-Step Blueprint for Launch",
    body: "Our process guarantees success. We believe in providing everything under one roof, guided by a disciplined, innovative methodology.",
    displayStyle: "slider",
    steps: [
      { title: "Strategic Consultation",     desc: "We begin by validating your core idea. Our experts perform deep market analysis and feasibility studies, analyzing requirements and competition to define a project scope that guarantees a high-ROI outcome." },
      { title: "Product Strategy",           desc: "Defining the blueprint for success. We align product objectives, identify the target audience, and establish key success metrics, ensuring your mobile application tells an intricate story of growth." },
      { title: "Design Excellence",          desc: "Beyond aesthetics, we create delightful experiences. Our design-thinking approach crafts effortless, intuitive user interfaces and experiences, utilizing mockups and prototyping to drive engagement and customer retention." },
      { title: "Engineering Development",    desc: "Building the robust core. We utilize cutting-edge technology stacks for 100% custom app development, ensuring a scalable, secure, and future-ready solution with complete source code and Intellectual Property rights." },
      { title: "Launch & Optimization",      desc: "Your launch is our benchmark. We handle seamless deployment to the App Store and Play Store, followed by post-launch optimization, software licensing, and dedicated 24/7 support to secure long-term success." },
    ],
  },
  techStack: {
    eyebrow: "Stack",
    heading: "Seeking a Mobile App Development Partner Aligned With Your Industry Vision?",
    body: "We build intelligent digital products that integrate seamlessly with your enterprise ecosystem. Our app development team combines deep industry context, design thinking, and advanced engineering to help organizations unlock new value across the mobile landscape.",
    displayStyle: "tabs",
    groups: [
      { title: "Blockchain Frameworks", items: [
        { name: "Ethereum",          logo: "/elchai/mobile-app/Ethereum_logo.webp" },
        { name: "Polygon",           logo: "/elchai/mobile-app/Polygon_logo.webp" },
        { name: "Solana",            logo: "/elchai/mobile-app/Solana_logo.webp" },
        { name: "Polkadot",          logo: "/elchai/mobile-app/Polkadot_logo.webp" },
        { name: "Cosmos SDK",        logo: "/elchai/mobile-app/Cosmos_SDK_logo.webp" },
        { name: "Avalanche",         logo: "/elchai/mobile-app/Avalanche_logo.webp" },
        { name: "Hyperledger Fabric", logo: "/elchai/mobile-app/1Hyperledger_Fabric_logo.webp" },
      ] },
      { title: "Artificial Intelligence", items: [
        { name: "OpenAI",          logo: "/elchai/mobile-app/white_Models_APIs-icn_1.webp" },
        { name: "Fetch.ai",        logo: "/elchai/mobile-app/Fetch.ai-icon.webp" },
        { name: "SingularityNET",  logo: "/elchai/mobile-app/SingularityNET-icn.webp" },
        { name: "Bittensor",       logo: "/elchai/mobile-app/Bittensor-icn.webp" },
      ] },
      { title: "Programming Languages", items: [
        { name: "Solidity",   logo: "/elchai/mobile-app/ProgrammingLanguages-icn_1.webp" },
        { name: "Rust",       logo: "/elchai/mobile-app/ProgrammingLanguages-icn_3.webp" },
        { name: "GO",         logo: "/elchai/mobile-app/go-icn.webp" },
        { name: "TypeScript", logo: "/elchai/mobile-app/TypeScript-icn.webp" },
        { name: "Python",     logo: "/elchai/mobile-app/ProgrammingLanguages-icn_5.webp" },
      ] },
      { title: "Frameworks", items: [
        { name: "HardHat", logo: "/elchai/mobile-app/HardHat_icn.webp" },
        { name: "Foundry", logo: "/elchai/mobile-app/Foundry_icn.webp" },
        { name: "Truffle", logo: "/elchai/mobile-app/Truffle-icn.webp" },
        { name: "Nextjs",  logo: "/elchai/mobile-app/Nextjs-icn.webp" },
        { name: "Node.js", logo: "/elchai/mobile-app/Frameworks-icn_2.webp" },
      ] },
      { title: "Wallets", items: [
        { name: "Metamask",     logo: "/elchai/mobile-app/Wallets-icn_2.webp" },
        { name: "Rainbow",      logo: "/elchai/mobile-app/Rainbow-icn.webp" },
        { name: "Trust Wallet", logo: "/elchai/mobile-app/Wallets-icn_3.webp" },
        { name: "Phantom",      logo: "/elchai/mobile-app/Phantom-icn.webp" },
        { name: "Coinbase",     logo: "/elchai/mobile-app/Coinbase-icn.webp" },
      ] },
      { title: "Smart Contracts", items: [
        { name: "Ethereum Virtual Machine", logo: "/elchai/mobile-app/Ethereum-Virtual-Machine-icn.webp" },
        { name: "Solidity",                 logo: "/elchai/mobile-app/Solidity-icn.webp" },
        { name: "Vyper",                    logo: "/elchai/mobile-app/Vyper-icn.webp" },
        { name: "CosmWasm",                 logo: "/elchai/mobile-app/CosmWasm-icn.webp" },
        { name: "Move",                     logo: "/elchai/mobile-app/Move-icn.webp" },
      ] },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    heading: "Mobile App Development — Common Questions",
    items: [
      { q: "Native, React Native or Flutter — what do you recommend?",
        a: "Native (SwiftUI / Kotlin) for performance-critical, OS-feature-heavy or strict-platform apps. React Native or Flutter for cross-platform speed with near-native UX. We recommend per project, not as a default — and explain the trade-offs honestly." },
      { q: "How long does it take to ship a mobile app?",
        a: "An MVP: 12–16 weeks. A polished v1 with backend, auth, payments and analytics: 16–24 weeks. Add 2–4 weeks for App Store / Play Store review, marketing assets and onboarding flows." },
      { q: "Do you handle App Store and Play Store submissions?",
        a: "Yes — including the metadata, screenshots, App Privacy / Data Safety disclosures, review escalations and post-launch updates. We've shipped through both stores under strict review constraints (crypto, finance, medical)." },
      { q: "Will my app work offline?",
        a: "Yes, if the use case calls for it. Local-first data layers (SQLite, Realm, Watermelon), conflict-resolution strategies, and sync engines (e.g. PowerSync, Y.js) are common in our offline-aware builds." },
      { q: "How do you handle performance on low-end devices?",
        a: "Budgets set at design (cold-start < 2s, scroll 60fps, animation 60fps) and enforced via CI perf checks on real devices. We test on iPhone SE and a low-tier Android, not just flagship hardware." },
      { q: "Who owns the app and source code at launch?",
        a: "You. Source repos, signing keys, store accounts and infrastructure transfer to your team. Post-launch retainers (maintenance, feature work, ASO) are optional and scoped separately." },
    ],
  },
  closing: {
    heading: "Seeking a Mobile App Development Partner Aligned With Your Industry Vision?",
    body: "Talk to Elchai's mobile engineering team about your next launch.",
    cta: { label: "Schedule Your Strategic Consultation", href: "#consultation" },
  },
};

// ─────────────────────────────────────────────────────────────────────────
// Registry
// ─────────────────────────────────────────────────────────────────────────
